### ISSUE TITLE
[FEATURE] Export/Import custom calendar configuration

### ISSUE THREAD

**Issue by Bolt7** [vigoren/foundryvtt-simple-calendar#101]
Because you can't save your custom calendar configuration, I'm unable to switch back and forth from other calendars without loosing everything.

I'd like for there to be way to save calendar configuration. Either into a text format which I could save in a journal entry and latter import, or into the calendars dropdown (the one with gregorian, golarion, etc.)

Those specific methods aren't necessary, they're suggestions. I'd just like to be able to use multiple calendars, and not have the custom one's configuration dissapear.

**Comment by vigoren** [comment]
This is something I am wanting to add I just hadn't made an issue for it yet so it's definitely on the list to get added. 😁

**Comment by vigoren** [comment]
You can now export and import calendar configurations in version 1.2.107!
A json file is generated when exporting that you can save

When importing chose that json file and it will apply the content of that file to the calendar configuration.

I would like to have the ability to add to the predefined dropdown but this isn't there yet.
