### ISSUE TITLE
Allow for 12/24 hour clocks, option to remove seconds shown

### ISSUE THREAD

**Issue by ckdragons** [vigoren/foundryvtt-simple-calendar#102]
It would be nice to allow for a 12 AM/PM clock instead of a 24 "military" time clock. Also, since I'm using this to track only hours in the day, having the option for seconds is additional clutter and makes the clock harder to read.

**Comment by vigoren** [comment]
With the new Date and Time formatting options in v1.3.62 you can absolutely set up the clock to display in 12 hour format with AM/PM indicators and drop the seconds from the display!
