### ISSUE TITLE
[BUG] Advanced settings don't all collapse

### ISSUE THREAD

**Issue by Bolt7** [vigoren/foundryvtt-simple-calendar#104]
The "Include Intercalary Month In Total Day Count" toggle shows even when "Show Advanced" show advanced is collapsed.

1. Go to Month Settings
2. Toggle "Intercalary Month" for one of the months.
3. Toggle between "Show Advanced" and "Hide Advanced" for that month
4. See that while other advanced settings collapse, the "Include Intercalary Month In Total Day Count" toggle does not.

I expected collapsing to hide the toggle, but it doesn't

![image](https://user-images.githubusercontent.com/75871317/119211166-7fefce00-ba7e-11eb-8910-472de4f3ea36.png)

It takes up a lot of space if there are multiple intercalary months, and having them not collapse defeats the purpose of collapsing some settings.

**Comment by vigoren** [comment]
This has been fixed in the most recent version of Simple Calendar.

**Comment by Bolt7** [comment]
Thanks!
