### ISSUE TITLE
Notes text is hard to read (nearly invisible)

### ISSUE THREAD

**Issue by morrgans** [vigoren/foundryvtt-simple-calendar#106]
Hi, 
I tried this already on the Foundry Discord but so far nobody could help me.
When using simple calendar in Warhammer Foundry module, the text when writing notes is not visible. This is because the standard text colour is a dark brown which blends in nicely with the background motive of the books,
![image](https://user-images.githubusercontent.com/84732920/119379183-72755680-bcbf-11eb-99e4-b66fa0ab9532.png)

Is there an easy way to fix this? 
I was thinking changing the notes colour or using the standard background from the journal etc.
Thanks in advance.
Olaf

**Comment by vigoren** [comment]
This looks more like a bug I will have to address on the next release.

I should be able to fix it but until I get the next release done there isn't a quick fix o know of. Sorry.

**Comment by morrgans** [comment]
So, I was able to fix it (or more correctly, the people on discord responded and then I was able to change it).
So I installed the custom css module and dependencies and added this rule

#simpleCalendar {
      background: url(/systems/wfrp4e/ui/frames/parchment-texture.png); <<- relative path to the parchement texture
}
    background-position: -43px -120px;
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    overflow-y: auto;
    padding: 0px 7px 3px 7px;
    margin: 0px;
    box-shadow: 0px 0px 20px black inset;
    border: 1px solid blue;
    border-width: 10px;
    border-image: url(/systems/wfrp4e/ui/window-app-dialog-content.png) 5 repeat; <<-- relative path to the frame
    border-image-slice: 10 13 13 13;
    border-image-width: 10px 13px 13px 13px;
    border-image-outset: 0px;
    height: fit-content;
    max-height: none;
    color: #d6d6d6;
}

#simpleCalendarNotes {
    background: url(/systems/wfrp4e/ui/frames/parchment-texture.png); <<- relative path to the parchement texture
}

#simpleCalendarNotes p {
    font-family: var(--actor-input-font-family);
    font-size: var(--actor-input-font-size);
    font-weight: var(--actor-input-font-weight);
    color: black;
}

#simpleCalendarNotes h1 {
    font-size: 2em;
    border-bottom: 2px solid #782e22;
    color: black;
}

.date-notes {
    color: black;
}

.simple-calendar #simpleCalendar .controls .date-controls {
    padding: .5rem;
    /* box-shadow: 2px 2px 5px #b9b9b9; /
    margin-bottom: .5rem;
    background-color: #fff0;
    color: #191813;
}

.simple-calendar #simpleCalendar .controls .date-apply-wrapper {
    padding: 0 .5rem .5rem;
    / box-shadow: 2px 5px 5px #b9b9b9; */
    margin-bottom: .5rem;
    background-color: #fff0;
    margin-top: -0.5rem;
}
and that did it.
cheers
Olaf

**Comment by vigoren** [comment]
I have updated Simple Calendar so the text should be easier to read now without having to add the CSS module and the above css
