### ISSUE TITLE
[BUG] No whitespace between year and year suffix after editing the suffix

### ISSUE THREAD

**Issue by marcstraube** [vigoren/foundryvtt-simple-calendar#107]
When I set a year suffix in the settings dialogue, there is no whitespace between the suffix and the year. If I add the whitespace into the suffix input box and press save, the whitespace gets stripped again.

**To Reproduce**
1. Open the "Simple Calendar" settings
2. Go to the "Year settings" tab
3. Edit the "Year suffix" string
4. Save the settings

**Expected behavior**
Either there should be a whitespace added by default, or the whitespace should not be stripped.

**Browser (please complete the following information):**
 - OS: Linux
 - Electron App

**Comment by vigoren** [comment]
This should be fixed in the latest version of Simple Calendar. It will add a space between the Postfix/Prefix and the year

**Comment by marcstraube** [comment]
Works like a charm! Thanks!
