### ISSUE TITLE
[FEATURE] Implement Calendar/Weather functionality

### ISSUE THREAD

**Issue by marcstraube** [vigoren/foundryvtt-simple-calendar#108]
Fist up: I really like this module! Nice features and a clean UI!

It would be nice to see the functionality from the Calendar/Weather module being implemented, because its maintainer has stopped the development and Simple Calendar would be the perfect replacement for it.

**Comment by vigoren** [comment]
Simple calendar has most of the functionality that calendar/weather has. The latest notable difference is the lack of weather, but that is planned to be done.

Just finishing up some bug fixes and updates to make sure everything is good to go for foundries 0.8.6 release. 

Then have some bigger changes to notes that I have started and am currently working through.

Then it's on to adding weather.

Was there anything in particular that is missing?

**Comment by marcstraube** [comment]
If lighting is included in the weather task, it sounds complete to me.
Thank you for your work!
