### ISSUE TITLE
Notes not appearing at all in 7.10[BUG] 

### ISSUE THREAD

**Issue by Avitale34** [vigoren/foundryvtt-simple-calendar#109]
**Describe the bug**
Adding notes as a player does not add anything to the calendar.

**To Reproduce**
1. add a note as a player.

**Expected behavior**
Would appear at the bottom.
**Screenshots**

**Browser (please complete the following information):**
- windows 10
- forge
- chrome

**Additional context**

**Comment by vigoren** [comment]
I have been unable to reproduce this error.

There are a couple of things to make sure:
- The GM needs to allow players to add notes with the permission options. (assuming that this is the case).
- Players are unable to create notes without a GM logged into the game. 

If these conditions are being met then there may be something else going on.

Are there any errors being thrown in the console?

**Comment by vigoren** [comment]
Haven't heard any more details about this issue in over a week. Closing it.
