### ISSUE TITLE
[FEATURE] Unified pause/resume button with game pause

### ISSUE THREAD

**Issue by scooper4711** [vigoren/foundryvtt-simple-calendar#112]
**Is your feature request related to a problem? Please describe.**
If the game is un-paused then game time should be running. If game time is paused the game should be paused (Foundry VTT pause state). I'd like to have a singular location for controlling that.

**Describe the solution you'd like**
You can make this a toggle option in your configuration if you'd like.
I'd like to have in the condensed and full window mode a single button that alternates between play/pause icons and controls both game time start/stop as well as Foundry VTT pause state.
If you press the play button, then Foundry VTT is un-paused, game time starts progressing at the rate specified in the Simple Calender settings and the play button becomes a pause button.
If you press the pause button, then Foundry VTT is paused (the big rotating 'game paused' appears), game time is paused and the pause button becomes a play button.

If the active scene has an active combat ongoing, then time progresses according to the combat rounds of course

**Comment by vigoren** [comment]
This makes sense though I think I will add it as a toggle option for those you do not want this particular behavior.

**Comment by vigoren** [comment]
This has been added in the v1.2.93 release!
