### ISSUE TITLE
[FEATURE] Easy to review permission indicator for calendar notes

### ISSUE THREAD

**Issue by scooper4711** [vigoren/foundryvtt-simple-calendar#113]
**Is your feature request related to a problem? Please describe.**
Some calendar notes should not be visible to players, while other notes should be. As a GM, when I want to review the notes for a day, it requires opening each note and pressing edit to see if a note is visible to players.

**Describe the solution you'd like**
I'd like a clear indicator next to the title of each note in the full view showing if a note is player visible or not without having to open the note.

**Describe alternatives you've considered**
You could use icons similar to Permissions Viewer plugin.

**Comment by vigoren** [comment]
Great idea, I will add this as part of #64 the note interface refresh
