### ISSUE TITLE
[FEATURE] Ability to link Calendar Notes in Journal Entries

### ISSUE THREAD

**Issue by scooper4711** [vigoren/foundryvtt-simple-calendar#114]
**Is your feature request related to a problem? Please describe.**
I have started putting the day's weather as a calendar note on each day. I use Journal entries for the preparation of various scenes that the players will encounter. I'd like to be able to link from the journal entry to a Calendar Note so that I can have easy access to the weather. 
There can be other uses for this 

**Describe the solution you'd like**
I can drag a calendar note from the full view to an open edit Journal Entry. When the journal entry is saved, it looks like any other journal entry link and I can click it to open the Calendar Note for that day.

**Describe alternatives you've considered**
I could make Journal entries for the weather for each day, but then it becomes difficult to find a particular day.

**Comment by vigoren** [comment]
I will look into this for sure with my next update to notes. I think this should be something that can be done.
