### ISSUE TITLE
[FEATURE] Incorporate weather from now-discontinued Calendar/Weather module 

### ISSUE THREAD

**Issue by ctbritt** [vigoren/foundryvtt-simple-calendar#119]
Would love to see my favorite feature of Calendar/Weather ported over to Simple Calendar, now that the former is no longer maintained.

**Comment by vigoren** [comment]
Yup this is planned to be added. Just working on some other features first.

**Comment by Nordiii** [comment]
I would commission this feature if you're interested, wrote an e-mail to your address given on your homepage but got no feedback.

**Comment by ctbritt** [comment]
oh, which email? I'm not seeing anything in my spam folders or inbox.

**Comment by Nordiii** [comment]
i send it to vig@vig.vg, can i reach you somewhere else?

**Comment by Nordiii** [comment]
oh wait i did send an email to @vigoren not you. Sorry for the confusion

**Comment by vigoren** [comment]
@Nordiii hey sorry I'm out camping at the moment (don't have reliable service) I'll get back to you as soon as I'm back in civilization lol

**Comment by TheBird956** [comment]
Hi @ctbritt, I picked up development of Calendar/Weather a few weeks ago so the module is still alive!

@vigoren this might interest you, there are a few changes that will happen soon on our side and we will partially switch date management from About-Time to Simple Calendar.

We will still take care of events, season and weather so you don't have to worry about this ;) I am still trying to figure out what the new responsibilities of Calendar/Weather will be, but my main goal is to avoid duplicating efforts on features across modules.

I have an open discussion thread on my repo if anyone wants to stay up to date with the discussions we have on our side: https://gitlab.com/jstebenne/foundryvtt-calendar-weather/-/issues/37

**Comment by vigoren** [comment]
I am going to close this issue as the [calendar/weather](https://gitlab.com/jstebenne/foundryvtt-calendar-weather/-/milestones/3) module is being repurposed to add weather support to Simple Calendar. This move names not sense to me as the weather module can then be added if people want. Make sure to keep tabs on their progress for when it is ready 😁
