### ISSUE TITLE
[BUG] Predefined calendar is not saved after I change it in the setup screen

### ISSUE THREAD

**Issue by JoeBossi** [vigoren/foundryvtt-simple-calendar#122]
When I try to Apply or Save the configuration after changing the Predefined calendar in the Quick setup, my choice in the drop-box is discarded and it always revert back to Gregorian, no matter what is my choice. I'm using Forge Hosting and my Foundry version is still 0.7.9

1. Go to 'Configure' in the simple calendar main window
2. Change the predefined calendar
3. Apply the changes with the 'Apply' button or save with 'Save configuration'
4. The predefined calendar goes back to 'Gregorian'

Expect behavior:
I would expect to find the calendar I choose and not the Gregorian

 - OS: Windows 10
 - Browser: chrome
 - Browser Version: 91.0.4472.77 (Official Build) (64-bit)

**Comment by vigoren** [comment]
The predefined option isn't really a setting in of itself. It is just used to update all of the other configuration settings with the relevant options for that calendar.

When you click apply and save the configuration the calendar should still update to reflect the calendar that you selected and all of the other configuration settings should be updated to that calendar as well.  Which is the most important part.

This probably isn't something I will change.
