### ISSUE TITLE
[FEATURE] Multiple clocks/calanders

### ISSUE THREAD

**Issue by Iankid** [vigoren/foundryvtt-simple-calendar#126]
I'm using the Starfinder System, and want a way to track times for planets with longer/shorter hours, without ignoring the universal calendar.

Having the option for another clock/calendar would help with this, perhaps accusable by dropdown menu?

Even just a secondary clock alone would be useful. If only just letting me track the currently used planet's time without messing with the universal time.

**Comment by vigoren** [comment]
This isa neat idea. Right now simple calendar can only support 1 type of Calendar/clock. This is something I can look into though it w will require a bit of reworking simple calendar to accomplish so it may take a bit too get it right.

**Comment by SwordofSpirit** [comment]
I would absolutely love to have this also. I came here and signed up just to request it. I'm running a world with multiple worlds within it, and without the ability to have multiple calendars, it's difficult for me to get full use out of the mod.

In my case, it's not about the clock, but about having actual different calendars that include all the features (moons, holidays, ability to place notes, etc). Ideally they could be coordinated with a master calendar, but I could deal with just having them be separate as long as I can have them all exist and keep their information. Heck, even the ability to run multiple instances of the mod at once would be better than nothing. :-)

**Comment by vigoren** [comment]
This is something I have begun working on. The first major steps are a bunch of structural changes to how I have my code set up (to support multiple calendars better).

Unfortunately this will take time to properly complete and test but it is something I am interested and eager to get done
