### ISSUE TITLE
[Note saving][BUG]

### ISSUE THREAD

**Issue by argetlam59** [vigoren/foundryvtt-simple-calendar#128]
**Describe the bug**
If you create a note, then save down the note. If you go back in to change any of the details, there is no save function to hold those changes into the note. 
**To Reproduce**
1. Create a Note
2. Save and Close
3. Go back into the note that was just created and change any details. 
4. There is no Save that holds the changes. 
**Expected behavior**
Save button should be top bar

**Browser (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Game Version 8.6
 
**Additional context**
If there is anything I can help with on this project more than happy to. Just have bare basics of javas.

**Comment by vigoren** [comment]
I have been unable to reproduce this bug.
When I add a note and then edit that note the save button appears at the bottom of the note (you may have to scroll down within the note after editing to see the save button or expand the note window).
Clicking that save button then saves any changes you made to note as expected.

**Comment by argetlam59** [comment]
I am indeed a fool. 
Scrolling found the save button.
