### ISSUE TITLE
[BUG] Offset not working correctly

### ISSUE THREAD

**Issue by DarKDinDoN** [vigoren/foundryvtt-simple-calendar#133]
**Describe the bug**
I'm trying to create a calendar where a month is interrupted by a day. I use a month (1 day length) to represent that day with the "Intercalary" option activated.
Then I wrap this month with the same month twice and an offset on the second occurrence.

Problem is that when I get to the second occurrence of the same month (configured with an offset) the calendar jumps to the next month in the list, skipping the second occurrence

Example of what I'm trying to achieve:
- ...
- 15 of the month
- 16 of the month
- 17 of the month
- **special day, not part of the month but interrupting it**
- 18 of the month
- 19 of the month
- ...

**To Reproduce**
See the following screenshot 
![image](https://user-images.githubusercontent.com/1687854/122647345-1ec22580-d124-11eb-8806-9398d122d7ac.png)

**Expected behavior**
Skipping days should not skip a whole month.

**Screenshots**
Video of the issue:

https://user-images.githubusercontent.com/1687854/122647710-da378980-d125-11eb-8505-63c6f927c534.mp4

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 91.0.4472.114 

**Additional context**
- FVTT: 0.8.6
- Simple calendar: latest

**Comment by vigoren** [comment]
Interesting bug with this. Good catch I'll look into fixing it for the next release. Thanks for the detailed report!

**Comment by vigoren** [comment]
This should be fixed now in the latest release!
