### ISSUE TITLE
[FEATURE] Additional information to timestampToDate Api function

### ISSUE THREAD

**Issue by DarKDinDoN** [vigoren/foundryvtt-simple-calendar#134]
**Is your feature request related to a problem? Please describe.**
Other modules can't display dates like SimpleCalendar does.

**Describe the solution you'd like**
Add more data to timestampToDate function (API)

- Year prefix
- Year postfix
- Season
- Show weekday heading boolean (so other modules can show/hide the weekday as well)

If it's implemented in SimpleCalendar, I'll make a PR to smalltime author 👍

**Comment by vigoren** [comment]
These will be added in the next release :)

**Comment by vigoren** [comment]
These have been added to the results of timestampToDate in the latest release!
