### ISSUE TITLE
[FEATURE] Import Moons from Calendar/Weather

### ISSUE THREAD

**Issue by landauer** [vigoren/foundryvtt-simple-calendar#135]
**Describe the solution you'd like**
I have Moon names, cycles, phases, and current states already set up in Calendar/Weather, but I vastly prefer the layout and aesthetic of SimpleCalendar.  I don't want to re-enter all that data, and since there's already a Calendar/Weather import feature, could it include Moons data?

**Comment by vigoren** [comment]
I'll look into enhancing the calendar weather importer, especially now that calendar weather will be requiring simple calendar.

**Comment by vigoren** [comment]
The importer better accounts for moons in the latest release. The caveat being that Simple Calendar and Calendar/Weather seem to calculate the moon phases differently so they do not match up to one another.
