### ISSUE TITLE
[FEATURE] Customized Date Formats and Month Abbreviations

### ISSUE THREAD

**Issue by landauer** [vigoren/foundryvtt-simple-calendar#137]
In my game world, dates are written and read in the common non-American format: numeric day, Month name or abbreviation, and year plus year postfix.  For example, any of:
* 19th of Newsummer, 110 SA
* 19 Newsummer, 110 SA
* 19 Nsm, 110 SA
* 19/4/110

There are other date formats I could imagine wanting, but all dates that I can see in Simple Calendar are reading in American format of month, day, year, and I can't find a place to change that:
* "Newsummer 19, 110 SA"

To go along with customized formats, I'd like to see the ability to add custom month abbreviations: multiple, preferably, for short abbreviations (like "Jan" for January) and for minimal abbreviations (like "1" for January) to go along with the format options mentioned above.

**Comment by landauer** [comment]
An additional feature to go along with this: an option for removing certain elements in the display format for specific days/months.  The example use case here is Intercalary months.  In my setting, each intercalary month has a single day, and I don't want to include the day number in the display.

Currently, an intercalary month shows as:
* "Year's Renewal 1, 110 SA"

I'd like to be able to remove the day from intercalary months when displaying the date, so it would read:
* "Year's Renewal, 110 SA"
* "YR, 110 SA"
* "YR/110"

**Comment by vigoren** [comment]
Date formatting is something I am working on for the 1.3 0 release. These are good suggestions though for enhancing how date furthering would work.

**Comment by vigoren** [comment]
The new Date and Time formatting options in v1.3.62 should allow you to customize how dates are displayed in any way you like.
