### ISSUE TITLE
[FEATURE] Better explain the "Include Intercalary Month in Total Day Count" Setting

### ISSUE THREAD

**Issue by landauer** [vigoren/foundryvtt-simple-calendar#138]
Some settings and calendars may have intercalary days not have a weekday as such, and be "outside" the standard weekday calculation (e.g. Sunday, Monday, Tuesday, IC MONTH DAY 1, Wednesday, Thursday).  I would like this to be an additional option for Intercalary months.

Currently, I have to manually set the starting weekday for every month to get this effect for my Intercalary months.

**Comment by vigoren** [comment]
Intercalary months shouldn't affect the day of the week subsequent months fall on.

I will look and see if this may be a bug that was introduced.

**Comment by vigoren** [comment]
From all my testing this works as expected.
Month 1 ends on a Thursday
Month 2 is an intercalary month.
Month 3 starts on Friday.

So perhaps I am misunderstanding the issue or feature you are asking?

**Comment by landauer** [comment]
This is what I'm seeing.  My months are 30 days with 6-day weeks, so every month should start on Sowersday, but I have to set the first month to Sowersday to guarantee that for some reason:
![image](https://user-images.githubusercontent.com/4087356/123492087-5110ce80-d5cd-11eb-8cdd-718550739bbc.png)
![image](https://user-images.githubusercontent.com/4087356/123492099-59690980-d5cd-11eb-8911-f6aff3cf5c9b.png)
![image](https://user-images.githubusercontent.com/4087356/123492107-61c14480-d5cd-11eb-962e-cc7d3071e6ba.png)
![image](https://user-images.githubusercontent.com/4087356/123492113-68e85280-d5cd-11eb-91c9-8d52a86d925b.png)

**Comment by landauer** [comment]
And an example of the intercalary day breaking the flow:
![image](https://user-images.githubusercontent.com/4087356/123492187-ae0c8480-d5cd-11eb-8f80-ee09788452cc.png)
![image](https://user-images.githubusercontent.com/4087356/123492195-b5339280-d5cd-11eb-8fd6-60962c75ecf4.png)
![image](https://user-images.githubusercontent.com/4087356/123492205-bbc20a00-d5cd-11eb-9138-ab83588daebb.png)
and the config for these three months:
![image](https://user-images.githubusercontent.com/4087356/123492234-d09e9d80-d5cd-11eb-8828-8a6aaff0dc0b.png)

**Comment by landauer** [comment]
It looks like this may be a side-effect of using "Include Intercalary Month in Total Day Count".  When I unchecked that for all Intercalary months, they returned to the expected behavior.

**Comment by vigoren** [comment]
Ah yes I may need to clarify that setting better.
It is basically means that the days in an intercalary month affect week days for other days as they are counted when doing that calculation.

It really just makes an intercalary month behave like a normal month but be listed as an intercalary month. Its kind of an odd setting haha

**Comment by landauer** [comment]
I understand now.  I thought it was going to be for "days elapsed/days remaining" calculations for future features or something like that.  Feel free to rename this issue for clarifying the setting instead.

**Comment by vigoren** [comment]
Will do, sorry for the confusion!
