### ISSUE TITLE
[FEATURE] Informational popups for months and weekdays

### ISSUE THREAD

**Issue by landauer** [vigoren/foundryvtt-simple-calendar#140]
I would like to be able to click on a weekday or the name of a month, and add a small amount of informational text about that weekday for easy access by my players when they click the weekday or name of the month.

**Comment by vigoren** [comment]
A small descriptive text field shouldn't be too bad to add. To months and weekdays

**Comment by vigoren** [comment]
This has been added in version 2.1.18. Months, weekdays and seasons have been given description fields. When a user clicks on the month name, weekday name or season name on the calendar display the description (if set) will appear for them to see
