### ISSUE TITLE
[FEATURE] highlight specific weekdays as "weekend"

### ISSUE THREAD

**Issue by landauer** [vigoren/foundryvtt-simple-calendar#141]
Much like some calendars have a grey highlight over Saturday and Sunday, I'd like to be able to designate specific weekdays to have a similar highlight as "rest days".

**Comment by vigoren** [comment]
This should be fairly easy to add and makes sense.

**Comment by vigoren** [comment]
This has been added in version 2.1.18. In the configuration you can specify which days of the week are rest days and those weekdays will be highlighted on the calendar.
