### ISSUE TITLE
Missing settings & interface

### ISSUE THREAD

**Issue by jagoe** [vigoren/foundryvtt-simple-calendar#155]
**Describe the bug**
Simple calendar settings do not show up under Module Settings.\
There also seems to be no way to display the calendar without calling `SimpleCalendar.show()` (in console or as a macro).

**To Reproduce**
1. Go to Module Settings
2. Search for "Simple"
3. "Simple Calendar" settings do not show up

**Expected behavior**
The settings show up under Module Settings and there is a way to display the calendar without using macros.

**Screenshots**
![image](https://user-images.githubusercontent.com/2989750/124871230-14c57100-dfc4-11eb-8568-25f1d2a1c9c2.png)

**Browser (please complete the following information):**
 - OS: occurred on Windows 10 and Linux Mint Cinnamon
 - Browser: Google Chrome
 - Browser Version: 91.0.4472.114 (Official Build) (64-bit)

**Additional context**

* FoundryVTT Version: 0.8.8
* Simple Calendar version: 1.2.113
* About-Time version: 1.0.3

Once displayed, the calendar behaves normally.\
I also don't see any console errors.

**Comment by jagoe** [comment]
Sorry for the issue conjunction, but I have a feeling they might be connected.

**Comment by vigoren** [comment]
There is a button to open the calendar in the left tool menu (the calendar icon)
![image](https://user-images.githubusercontent.com/1746488/124872711-d5c2fb80-df82-11eb-8afd-0d951233ab6c.png)

Clicking that will open up the calendar interface.

That said In the next release I have also added a button to the module settings that will open up the calendar configuration.

**Comment by jagoe** [comment]
Of course it's right there :facepalm: \
Thanks for the quick reply!

Can I suggest adding that screenshot and explanation to the readme? Other people with cluttered tool menus will thank you, haha.
