### ISSUE TITLE
Simple Calendar not showing up in Configure Settings [BUG] 

### ISSUE THREAD

**Issue by doctorgalactic** [vigoren/foundryvtt-simple-calendar#157]
**Describe the bug**
Simple Calendar is installed and the module is set to active, however there is no settings page in the Configure Settings > Module Settings tab.  

![image](https://user-images.githubusercontent.com/8406396/125216231-196b7d00-e283-11eb-8de7-d9b2848b682e.png)
![image](https://user-images.githubusercontent.com/8406396/125216246-2a1bf300-e283-11eb-8161-03b1c7030350.png)

 - OS: Windows 10
 - Browser: N/A (using software)
 - FoundryVTT Version: 0.8.8

**Comment by vigoren** [comment]
Please see this comment
https://github.com/vigoren/foundryvtt-simple-calendar/issues/155#issuecomment-876165667

It is in a different location
