### ISSUE TITLE
[BUG] The "Konfiguration speichern" button is displaced (System: DSA5)

### ISSUE THREAD

**Issue by tomsaath** [vigoren/foundryvtt-simple-calendar#162]
**Describe the bug**
The "Konfiguration speichern" (german) Button isnt fixed in the bottom of the windows. So it appears to scroll in the middle of the confuguration Settings. Maybe it is an incompatibility with the System Design?

**Screenshots**
Start of the window:
![grafik](https://user-images.githubusercontent.com/80099175/125615977-b7398930-adc5-461c-af53-ee8165b480dc.png)

Scrolled down:
![grafik](https://user-images.githubusercontent.com/80099175/125616017-5239f564-5fbb-4249-8a03-0bd31d72b91a.png)

**Browser (please complete the following information):**
 - Browser [Chrome and Full Client]

**Comment by tomsaath** [comment]
That was very fast, thank you.

**Comment by vigoren** [comment]
I am hoping to release it in the next couple of days. Have a couple of other bugs I'm working on fixing at the moment. Once they are done it will be released 😁
