### ISSUE TITLE
Export Events into a Journal Entry

### ISSUE THREAD

**Issue by baileymh** [vigoren/foundryvtt-simple-calendar#17]
Would be very useful for me as a GM, as well as my players, to be able to create a singular log of events as a journal entry.

**Comment by vigoren** [comment]
Good idea, I will look into adding this!

**Comment by scooper4711** [comment]
I'd like players to be able to create notes which *are* journal entries, not ones you export. Essentially another way to do session notes.
In the settings, you specify where session notes would be stored and perhaps a template for session notes. Players can then make said session notes.

**Comment by DesktopMan** [comment]
> 
> 
> I'd like players to be able to create notes which _are_ journal entries, not ones you export. Essentially another way to do session notes.
> In the settings, you specify where session notes would be stored and perhaps a template for session notes. Players can then make said session notes.

Seconded. We are using calendar notes for session notes and having them automatically be journal entries (named and sorted on date) would be great.
