### ISSUE TITLE
[TRANSLATION] Czech

### ISSUE THREAD

**Issue by robertjunek** [vigoren/foundryvtt-simple-calendar#172]
Hi, I've made Czech translation of your module so I'm sending localization file :)

[simple-calendar-cs.zip](https://github.com/vigoren/foundryvtt-simple-calendar/files/6868180/simple-calendar-cs.zip)

**Comment by robertjunek** [comment]
Btw I can fork it, if you prefere it :)

**Comment by vigoren** [comment]
This is great thank you!

It is up to you if you want to do a pull request or not, I can work with the files you have given :)
