### ISSUE TITLE
Problem with notes of a different year

### ISSUE THREAD

**Issue by lorion1985** [vigoren/foundryvtt-simple-calendar#18]
If you created a note and change the current day to a future year you won't see any of the "last years notes". Likewise if your current day is today and you watch the calender entry of the next year, you will see the same notes there marked with the current date.

**Comment by vigoren** [comment]
Thanks for the bug report and sorry about that. These issues should be fixed in the newest version of the module (v1.0.3).

Please update to that version and let me know if you see any other issues.
