### ISSUE TITLE
New Settings and quicker Flow to simplify note-adding

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#20]
New Setting: Player Visible by Default
Usage: DM that only uses the internal calendar to mark player events, and does not need to click Player Visible every time.

New Setting: Turn Off Detailed Note
Usage: DM that only uses the title to write a note and does not go into further detail, and does not need to copy the same title into the body of the note just to be able to save.

**Comment by vigoren** [comment]
You should be able to save the note dialog if you Just change the title and don't touch the details text editor.

I can make the change to set notes to be player visible by default.

**Comment by vigoren** [comment]
The player visibility setting has been added in version 1.1.0

Saving with no note details should be more reliable

**Comment by apoapostolov** [comment]
Hello, thanks a lot!

For me, it would be best if the focus field was the title, not the note. I did not find an option to set Player Visibility to on by default, I would love that a lot - or behavior to remember turned on between notes.

**Comment by vigoren** [comment]
The setting for player visibility on by default should be under the module settings area of the game settings.
https://foundryvtt.com/article/settings/

I can definitely look into having the title be the default focus on the note

**Comment by vigoren** [comment]
I moved the "Default Player Visibility for Notes" setting from the module settings area of the foundry game settings and placed it under the General settings for the calendar configuration. This makes more sense to me.

I have also changed the behavior of the note dialog so that the title text box is the one that is in focus by default.
