### ISSUE TITLE
[FEATURE] Option to reduce/increase the font size in the widget

### ISSUE THREAD

**Issue by sladecraven** [vigoren/foundryvtt-simple-calendar#200]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but compared to the previous "Calendar/Weather" widget, the SimpleCalendar one is very big, mainly because of font size.

**Describe the solution you'd like**
Allow an option in the settings to reduce (or increase) font size.

**Describe alternatives you've considered**
No alternative ...

**Additional context**
Nor applicable

**Comment by sladecraven** [comment]
In addition, I would suggest to remove the border/title of the window, to gain space, and to pack small buttons inside the frame instead.
![image](https://user-images.githubusercontent.com/1085008/132129010-d8063ec1-6f4e-4a86-b5c2-09b5fe4b084f.png)

**Comment by vigoren** [comment]
Well I don't see me adding a font size option to the settings, I will take these points into consideration when I tackle updating how the calendar interfaces look.

**Comment by sladecraven** [comment]
Hi, 
On this topic, the 'compact' widget is really big compared to the previous (and nice) Calendar/Weather one. Could you at least remove the window brdoer and header to reduce it (ie as it was the case in Calendar/Weather) ?
