### ISSUE TITLE
Day doesn't change when hour in a day finish [BUG] 

### ISSUE THREAD

**Issue by AllsiHell** [vigoren/foundryvtt-simple-calendar#202]
**Describe the bug**
When i set the first day of the week, the time start but when it must change day it doesn't work, and remain on the first day setted. If i change the day, the problem continue but at the day setted.

**To Reproduce**
1. Open Configuration
2. Set Self or Mixed Game World Time Integration
3. Click on Weekday Settings, 
4. Create multiple Weekday after 
5. Set Starting Week Day (it's equal for every day you set)
4. Save Configuration 

**Expected behavior**
When it finish the Hours in a Day  setted it will change the day. 

**Screenshots**
![screen bug](https://user-images.githubusercontent.com/28911822/132318173-b2f77477-2331-4e39-84f3-991ef341ed10.gif)

**Foundry Information**
 - Foundry Version: [e.g. 0.8.8/0.8.9]
 - Game System: [e.g. 3.5e SRD]
 - Simple Calendar Configuration: [Custom]

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 93.0.4577.63 (Build ufficiale) (a 64 bit)

**Additional context**
it affect Calendar Weather ad Small Time when Mixed

**Comment by vigoren** [comment]
I haven't been able to reproduce this issue. Could you send me the calendar export file that is causing the issue so I can see what's going on?

You can generate a file by going to the calendar configuration dialog and exporting the configuration.

Thanks!

**Comment by AllsiHell** [comment]
Hi, yep this is my configuration
I hope it can help.
[simple-calendar-export_Issue.zip](https://github.com/vigoren/foundryvtt-simple-calendar/files/7132314/simple-calendar-export_Issue.zip)

**Comment by vigoren** [comment]
This was actually a bug around setting the hours in day to any value other than 24. I have fixed the bug v1.3.39 and your example calendar seems to be working as expected now :)
