### ISSUE TITLE
[BUG] simple-calendar-date-time-change emits multiple times

### ISSUE THREAD

**Issue by SDoehren** [vigoren/foundryvtt-simple-calendar#205]
**Describe the bug**
simple-calendar-date-time-change hook emits multiple times at, what seems to be, every tenth second.

**To Reproduce**
have time running

with the following macro

Hooks.on('simple-calendar-date-time-change', async (time) => {
    console.log("time-change "+time.time.hour+":" +time.time.minute+":"+time.time.second)
});

![image](https://user-images.githubusercontent.com/41287460/132891783-921633f4-a0ec-4f6a-ad87-f8fbcc8896d0.png)

**Expected behavior**
To not emit multiple times

**Foundry Information**
 - Foundry Version:0.8.9
 - Game System:  DnD5e
 - Simple Calendar Configuration: default

**Browser (please complete the following information):**
 - OS: win10
 - Browser chrome/foundry

**Comment by vigoren** [comment]
This should no longer be duplicated in version 1.3.44. Thanks for the report!
