### ISSUE TITLE
[BUG] Seasons not working as expected

### ISSUE THREAD

**Issue by DarKDinDoN** [vigoren/foundryvtt-simple-calendar#207]
**Describe the bug**
Hello, I have created a calendar with seasons.
Although seasons are correctly defined in the configuration window, the calendar always displays the same season name below the month name.

![image](https://user-images.githubusercontent.com/1687854/133578477-90ba7043-6ac2-417d-bc80-ac979f2b6881.png)

The season name is stuck on "Printemps" and color is stuck on green.
Same over the API with `SimpleCalendar.api.getCurrentSeason()`

**To Reproduce**
Here is the exported calendar configuration: [simple-calendar-export.zip](https://github.com/vigoren/foundryvtt-simple-calendar/files/7176181/simple-calendar-export.zip)

**Expected behavior**
Season name and color should change when clicking on the calendar arrows.
This was working correctly a while back.

**Foundry Information**
 - Foundry Version: 0.8.9
 - Game System: 5e 1.4.3
 - Simple Calendar Configuration: 1.3.39

**Browser (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 93.0.4577.82

**Comment by vigoren** [comment]
Sorry about this. Seems to be because the seasons start on intercalary months, which with the new way I sort seasons I overlooked that. My mistake, I'll have a fix out for it hopefully tomorrow.

**Comment by vigoren** [comment]
Again sorry this took me longer to get out, real life got in the way. That said it should be all fixed up in version 1.3.44

**Comment by DarKDinDoN** [comment]
@vigoren Hey thx! Works like a charm 😄
