### ISSUE TITLE
[BUG] Uncaught (in promise) Error

### ISSUE THREAD

**Issue by tagnullde** [vigoren/foundryvtt-simple-calendar#208]
This bug manifests itself differently every time I try to get a hold of it.
In a nutshell there are two or three main errors.

Player Side:

When reloading the browser as a player these error occurs. 
![image](https://user-images.githubusercontent.com/44159008/133938710-7a42b156-1651-4fe7-9adb-628245495085.png)

Sometimes only one of them shows up.
![image](https://user-images.githubusercontent.com/44159008/133938788-017a4fde-e875-48b6-81a3-f33dd3c16e1e.png)

GM Side:

When logging out as a GM or shutting down the world - I also get an error. But I can't screenshot it because the world shuts down as soon as the error is shown. I think because it tries to write something to the database but can't as a GM aswell.

![image](https://user-images.githubusercontent.com/44159008/133939088-9169a907-ea13-4407-93cb-1c1d85127ee1.png)
Modules are all up to date. Errors don't show up with this module disabled.

Let me know if I can' help you out by providing more data.

EDIT:
It also fills up the error.log & debug logs. 

![image](https://user-images.githubusercontent.com/44159008/133939338-e0e74944-d868-4cf7-a9dd-66f6d4abbf0b.png)

**Comment by vigoren** [comment]
Hey!

These seem to be an error with the core foundry system not specifically my module.

You can try asking the question on the official [Discord](https://discord.gg/foundryvtt) or submit an issue on [GitLab](https://gitlab.com/foundrynet/foundryvtt)

**Comment by tagnullde** [comment]
Interessting. I thought it was this module because of "ticks" (like time intervals) and because I couldn't reproduce the error with simple calendar disabled. Sorry for bothering you. Will head over foundry. Thanks.

**Comment by vigoren** [comment]
No worries. My module could be the symptom as it ticks but to save and tell other clients of each tick it uses internal functions of foundry.

The longer explanation.
Foundry has a global internal variable for world time. This is a number that represents seconds like a time stamp. This is only updated by systems (combat round changes) or by modules.

Simple Calendar will set this value to the timestamp for the date of your calendar. It is set by a single function call to an internal foundry function `game.time.advance(seconds)`. That function is then responsible for saving the new time and letting all connected users know if the update.

My guess is the issue with be with that for some reason. Though this is the first time I have seen this particular issue.

Hope that helps explain it a bit better.
