### ISSUE TITLE
[API FEATURE] getAllMonths and other get functions

### ISSUE THREAD

**Issue by Biglulux** [vigoren/foundryvtt-simple-calendar#212]
**Is your feature request related to a problem? Please describe.**
I need to calculate the number of days passed between two timestamps. I'm using secondsToInterval, which gives me months and years. The problem is that I don't know how many days are in a month and how many months in a year for custom calendars, and so I can't easily convert the number of months and years into days. The DateTimeChange hook has a Month object, but that is deprecated. There's no current way to access a Month object of the current month or all months.

**Describe the solution you'd like**
Add .getCurrentMonth and .getAllMonths that will return a Month object, where I will be able to see numberOfDays. For good measure, add .get functions to get any time object, such as Year objects, Weekday objects, etc.

**Describe alternatives you've considered**
My only option right now is to include a module setting where the user has to manually input the number of days in a month. I can't find any way to access the number of days in a month otherwise.

**Additional context**
Would also be cool if .dateToTimestamp accepted a Date object, and not just a Date Time object. I have to spend an extra line converting the object.

**Comment by vigoren** [comment]
Good suggestions I will look at adding these for the next release!

**Comment by vigoren** [comment]
These and many other get* API functions have been added in v1.3.62 

Thanks for the suggestions!
