### ISSUE TITLE
Dawn and Dusk are defaulting to 12:00 AM[BUG] 

### ISSUE THREAD

**Issue by ckdragons** [vigoren/foundryvtt-simple-calendar#218]
Using Golarian calendar. How do I change the times for Dawn and Dusk? They are currently defaulting to 12:00 AM. I'd like to set them to 6:00 AM and 6:00 PM, respectively.

**Comment by vigoren** [comment]
Dawn and dusk times are configured through seasons. It sounds like no seasons are configured, it you add a season you can set when dawn and dusk are. 

If you add more seasons with different dawn and dusk times the calendar will slowly adjust the dawn and dusk times to meet the new season as days pass.

**Comment by ckdragons** [comment]
Thank you. See that option now.

**Comment by ckdragons** [comment]
After messing with these options, possible to configure it so it's static 7:00 AM sunrise and 6:00 PM sunset year-round? It's nice that the seasons seem to change these times but it's too granular for my campaigns.
![image](https://user-images.githubusercontent.com/84493092/135213896-ec48c7cc-e403-4de5-985a-b19f4f57c678.png)

**Comment by vigoren** [comment]
How you have it set in your screenshots will have dawn always be 7am and dusk always be 6pm. 

It just looks at the difference between the current seasons sunrise/sunset and the next season's sunrise/sunset time and evenly distributes the difference among the days. If there is no difference then it will be the same every day.

**Comment by ckdragons** [comment]
Again, thank you. It took me a few times to save/reload/correct/save/reload because the options weren't saving each dusk time as I set them, but eventually it stuck. It's working now.
