### ISSUE TITLE
Note labels to differentiate between Campaign, Holidays, etc. notes

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#22]
Settings functionality to add labels and assign colors to them. Then when creating a label, dropdown to choose a label. The last used label is the default choice when opening the form. The note titles in the main window have a label ticket before or after their name and are colored in the label color. 

This will help create separate labels for Holidays aside from Campaign notes.

**Comment by vigoren** [comment]
I like this idea, will be looking at adding it.

**Comment by scooper4711** [comment]
I would love labels, and the ability for players to filter what labels they're interested in.

E.g. a cleric of deity X would see all notes (holy days) related to her deity, but could exclude the notes for other deities.
