### ISSUE TITLE
Notes that repeat annually

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#23]
For the purpose of creating holidays that happen on the same day every year.

**Comment by vigoren** [comment]
Good idea, I will look into adding this.

**Comment by vigoren** [comment]
I added the ability to repeat notes weekly, monthly or yearly. This will be part of the 1.1.x release which should hopefully be ready in the next few days.

**Comment by vigoren** [comment]
This has been added in version 1.1.0
