### ISSUE TITLE
[QUESTION] Formating Time Dispaly

### ISSUE THREAD

**Issue by webmaster94** [vigoren/foundryvtt-simple-calendar#238]
I am trying to configure the clock to display in 12-hour format with the AM/PM appended but I can't seem to get it to work. I was able to set the hour format to hh instead of HH but when I attempt to append A with a space, put A in the hour section, use a comma or a semicolon to separate A, nothing works. Any help would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/85364225/136662265-1843b357-6e28-48b0-b43a-8c9fe67457e0.png)
![image](https://user-images.githubusercontent.com/85364225/136662292-f0d67bfb-0d45-4083-8f80-be1cfa60860a.png)

**Comment by vigoren** [comment]
You have it right you should be able to set the format to `hh:mm:ss A` to have the time change to 12 hour.

When it doesn't work what's happening? Is the setting not saving it is the clock not changing?

**Comment by vigoren** [comment]
Can you show me a screenshot of the clock? It updates properly with my testing.

As for the setting not saving the a after you add it try clicking anywhere else in the configuration dialog then clicking the save button
