### ISSUE TITLE
Method to assign a weekday to specific date in order to ensure the calendar matches official calendars

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#24]
Any method would be fine, such as assigning one exact date to be a Monday and then building all the calendar weekdays based on that date.

**Comment by vigoren** [comment]
Right now the week days are based on the first day of the week falling on the first day of the first month of year 0.
I can look into an easy way to adjust that so days of the week can fall on the correct date.

**Comment by vigoren** [comment]
Would the addition of leap years and intercalary months satisfy this need?

If not which official calendar are you trying to match up with?

**Comment by apoapostolov** [comment]
Hello,
Thank you very much for the new version, it implemented many of my requests.

I am running PF2 and using Golarion Calendar. I am trying to fix the discrepancies between calendar services that I use and the Simple Calendar. For example, so far I manage my calendar at Fantasy-Calendar.com before I move to internal management in Simple Calendar. 

On Fantasy Calendar, 20th of Desnus 4720 is Wealday. On Simple Calendar it is Toikday.
https://app.fantasy-calendar.com/calendars/ad16fcecc6b137db2c462ada513fcfa4

![image](https://user-images.githubusercontent.com/4083812/110089071-55a34400-7d9e-11eb-9432-4e90dace4884.png)

If I could set a specific date to be specific weekday, then it would immediately sync the whole calendar to that specific date and fix the calendar.

**Comment by apoapostolov** [comment]
Ok please ignore the above post and this issue is not a problem, because I checked other websites providing calendar for Golarion and I found that all other sites match the date as Oathday. When I changed the calendar to Golarion using your new presets, it immediately matched the date (20th of Desnus) to Oathday.

It seems the Fantasy-Calendar is wrongly matching it as Wealday. 

So no problem anymore using your predefined Golarian calendar.

**Comment by vigoren** [comment]
Glad to hear the update helped get the dates aligned for you.

Thanks for all the feedback it is greatly welcome.
