### ISSUE TITLE
Year in calendar header not updating when navigating the calendar with header arrows

### ISSUE THREAD

**Issue by archeresky** [vigoren/foundryvtt-simple-calendar#242]
When using the header arrows to navigate through the Calendar in case a month from the previous/next year is viewed, the year displayed in the header does not change.
![image](https://user-images.githubusercontent.com/73297245/137558599-0f1fac5e-08e0-488d-959e-1f333bb2bdca.png)
On the picture you can see that the notes display the correct year while the year in the header is incorrect and comes from actual date in the setting.
This was observed in version 1.3.75 on Foundry 0.8.9 and DnD5e 1.5.2

**Comment by vigoren** [comment]
I was able to reproduced the bug, thanks. I will fix it up and get a release out in the next day or so. Just finishing up some other changes.

**Comment by Moongoyzer** [comment]
Got this bug as well, Foundry vesrion 0.9.242, appears in different systems (Cortex Prime, AGE, L5R)

**Comment by iamthetot** [comment]
Also happens to me in Firefox, and Edge. It didn't use to be this way, not sure when it started being broken. You can still advance the years with other methods.

Thanks for your work on this project. It's probably the most important foundry module I run in my games. Players absolutely love it. Cheers!
