### ISSUE TITLE
[FEATURE] Multiple Calendars

### ISSUE THREAD

**Issue by jasharen** [vigoren/foundryvtt-simple-calendar#243]
**Is your feature request related to a problem? Please describe.**

I have multiple groups that I run off the same instance of Foundry. I would like to be able to have a different calendar for each group that has the same configuration, but different dates as the different groups progress at different speeds.

**Describe the solution you'd like**

Multiple current date values.

**Describe alternatives you've considered**

Currently I need to track the date in a journal for each group, and then at the start of each session set the current date.

**Additional context**

**Comment by vigoren** [comment]
This is something that had been request (#126) and it's something I am working on. It will be added hopefully soon
