### ISSUE TITLE
Unable to change Predefined Calendar[BUG] 

### ISSUE THREAD

**Issue by thealkaizer** [vigoren/foundryvtt-simple-calendar#245]
**Describe the bug**
I installed Simple Calendar along with some Forbidden Lands modules. I tried to change the Simple Calendar predefined calendar to something else then Gregorian (which is the default). However, it doesn't work. It doesn't matter what I change it to (Forbidden Lands or any of the other calendars that come with Simple Calendar).

I can click the dropdown menu, select another calendar. Then I hit Apply, I do get the confirmation window warning me that it will overwrite all existing calendar configurations. I hit Apply again. As expected, the confirmation window disappears but the dropdown menu goes back to Gregorian.

**To Reproduce**
1. Open Simple Calendar configuration.
2. Under General Settings, under the header Quick Setup, change the value of Predefined Calendars to something else.
3. Click on the green Apply button.
4. Click on the Apply button in the confirmation window.

**Expected behavior**
I would expect to either get an error message if something is wrong, or for the Predefined Calendar change to be applied.

**Screenshots**

**Foundry Information**
 - Foundry Version: 0.8.9
 - Game System: Forbidden Lands
 - Simple Calendar Configuration: Default configuration.

**Browser (please complete the following information):**
 - OS: Windows 10 Pro 64-bit (10.0, Build 19042)
 - Browser: Not applicable
 - Browser Version Not applicable

**Additional context**

**Comment by vigoren** [comment]
The predefined option isn't really a setting in of itself. It is just used to update all of the other configuration settings with the relevant options for that calendar.

When you click apply and save the configuration the calendar should still update to reflect the calendar that you selected and all of the other configuration settings should be updated to that calendar as well. Which is the most important part.
