### ISSUE TITLE
Auto-fire a Macro @ Date/Time as part of a Note Event

### ISSUE THREAD

**Issue by Shuggaloaf** [vigoren/foundryvtt-simple-calendar#247]
It would be great if you could add a feature to fire off a user-chosen macro on a given date/time. It would be really great if this could just be added to the notes functionality (with a default of midnight for all-day events). That way I can set a note, visible to GM only or all, but also have it fire off a macro at a certain time. 
This could be extremely useful in general but I can see possible combat uses for this as well.

**Comment by Shuggaloaf** [comment]
Hi Vigoren, I typically don't "check in" on issues but I know this one was on hold due to the work on 2.0. Since it didn't get incorporated into 2.0 I thought I'd check in on it. (To be clear not to rush you, just for curiosity's sake) 

Is this still a viable request to implement? With the code redesign did you run into anything that might make this more difficult to now implement?

Now that 2.0 is published, what would you consider the priority of this feature vs other issues?

Thanks!

**Comment by vigoren** [comment]
This is very much something I plan on adding. I just didn't want to delay version 2 any longer than I needed to. I was going to give the new version a week or so to iron out any bugs before adding new features. This was one of the first new features I plan on adding after that.

**Comment by vigoren** [comment]
This feature has been added in version 2.0.13!

**Comment by Shuggaloaf** [comment]
Thank you very much!

**Comment by Shuggaloaf** [comment]
Upgraded to try out the macro feature and I can't seem to get any macros to fire. Thought I' check with you before opening an issue.

I set a date and time, select a macro in the dropdown under Advanced and then save the note. If I then advance the time to when the macro should execute, it doesn't do anything. If I setup a note with reminder and without a macro, that works fine. 

Perhaps I'm missing another setting?

**Comment by vigoren** [comment]
Macros only fire once like note reminders but they are working for me in my environment.

I create a macro called test (it can output text to chat or run a script l

Then on a day ahead of the current date I add a note and in the advanced section choose the test macro from the drop down. I  save the note.

Then in the calendar i advance the date and time to that of the notes and I see the needful get executed (script is run out message sent to the chat). After that the macro doesn't fire again unless the page is reloaded (like note reminders, though a macro should never fire on page reload it just means reaching that date again will trigger the macro)

Things I would check is that the macro was actually saved to the note. After setting the macro close and open the note to make sure the drop down is set to the macro you selected.

Make sure that the macro actually runs.

If those are both true maybe provide me an example of the macro you are trying to run so I can see if anything in there stands out. I only personally tested pretty basic script macros.

**Comment by Shuggaloaf** [comment]
I figured out the issue. The macro doesn't fire again for repeated notes. 

So if I have an event repeated weekly, it fires the first date, but does not fire every week as would be the desired behavior.

**Comment by vigoren** [comment]
Yeah this is the same issues as note reminders on repeating notes. Fall into the same issue that it is only triggered once and not again until the browser is refreshed.

This is due to a limitation in how I implemented the note repeating code. I am working on an big update to that code and when it is done this limitation would go away.

You can open another issue if you wish to make sure it isn't missed but it is on my list of things to check when I get that code implemented properly.

**Comment by Shuggaloaf** [comment]
I actually did test refreshing to see if it would then run the macro and it still didn't. Tested by going to a day that hadn't been triggered yet as well. It's late here now but I can double check that tomorrow. I won't open a new issue though since this is on your radar.

**Comment by Shuggaloaf** [comment]
OK that did work. Sorry for the misinformation!!

>I am working on an big update to that code and when it is done this limitation would go away.

Would you have a rough idea on the time frame? Don't get me wrong, not trying to be pushy at all. Just trying to determine if I want to re-implement my hackish way to do this or just wait for the update.  Thanks!

**Comment by vigoren** [comment]
Sadly I don't have a good timeline for it. I am actively working on it but life is pretty busy for me at the moment so I can't guarantee a specific date.

My priorities right now are the improved note repeat update and support for foundry v10 (for when it is released)

**Comment by Shuggaloaf** [comment]
I perfectly understand. 

Oh and I'd never ask for a specific date (I hope no one would!) I meant more of a general days/weeks/months kind of thing. (which you just gave me)  :)
