### ISSUE TITLE
Note view dialog needs to have max width because single line large paragraphs stretch it to screen width.

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#25]
Example how it looks when I enter Golarion Holiday information:

![image](https://user-images.githubusercontent.com/4083812/109191748-1faf0000-779f-11eb-88a0-b93cb3b5331d.png)

**Comment by vigoren** [comment]
oh oops yeah need to set a maximum width for sure, will adjust.

**Comment by vigoren** [comment]
This has been fixed in version 1.1.0
