### ISSUE TITLE
[FEATURE] Player Notes while GM Offline

### ISSUE THREAD

**Issue by bugbeersandflagons** [vigoren/foundryvtt-simple-calendar#250]
Could we have an option to enable players to create notes while the GM is offline?  My players will often log in to update various journal notes etc out of game, but cannot do so to the calendar notes unless I am online at the time

**Comment by vigoren** [comment]
This is a current limitation with foundry and how notes are being saved right now.

That said I am currently looking into saving notes as journal entries instead which should allow players to save notes without needing the GM to be present.
