### ISSUE TITLE
[FEATURE] Make "compact view" more compact

### ISSUE THREAD

**Issue by sladecraven** [vigoren/foundryvtt-simple-calendar#252]
The compact view is still "vig" compared to the previous Calendar/Weather version.

Proposed solution : 
Remove the "application window frame", to make the "compact view" more compact.

**Comment by Shuggaloaf** [comment]
Hey @sladecraven check out the mod Small Time by Unsoluble. It integrates perfectly with Simple Cal and (mostly) gives you what you're looking for.

I used to use Calendar/Weather and switched to a combo of Simple Cal and Small Time. Works very well and the ST interface looks very similar to C/W but also has some other very cool features (such as auto-scene darkness based on time of day, and so on)

Also check out [this suggestion](https://github.com/unsoluble/smalltime/issues/80) for a more compact calendar integration with Small Time that I posted in the ST repo. Vigoren (Simple Cal dev) has already created a method for Small Time to incorporate this. I'm sure more support for the suggestion could help it get realized.
