### ISSUE TITLE
[BUG] Using wrong Format Token breaks configuration

### ISSUE THREAD

**Issue by MOAM-Biggles** [vigoren/foundryvtt-simple-calendar#255]
**Describe the bug**
Entering a wrong Format Token in the display options will stop both the calendar dialog as well as the calendar configuration dialog from opening. Consequently the wrong Format Token cannot be corrected from within the application.

**To Reproduce**
1. Open **Simple Calendar** dialog
2. Click on '**Configuration**'
3. Scroll down to '**Display Options**'
4. Enter a wrong Format Token like '**MMMM YAYYYYY Z**' for '**Month/Year Format**', e.g. a typo
5. Click '**Save Configuration**'
6. Click on '**Configuration**' again or close and try to reopen **Simple Calendar** dialog
7. Dialogs won't open. The following error message is displayed in the console:

```js
foundry.js:2013 TypeError: a[t] is not a function
[Detected 1 package: foundryvtt-simple-calendar]
at index.js:1
at String.replace (<anonymous>)
at Function.FormatDateTime (index.js:1)
at J.toTemplate (index.js:1)
at ee.getData (index.js:1)
at ee._render (foundry.js:2049)
at Z.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:502)
at ee.🎁Application.prototype._render#lib-wrapper (listeners.js:110)
at ee.🎁Application.prototype._render#0 (libWrapper-wrapper.js:182)
at ee.render (foundry.js:2011)
at ee.showApp (index.js:1)
at SceneControls._onClickTool (foundry.js:27752)
at HTMLLIElement.dispatch (jquery.min.js:2)
at HTMLLIElement.v.handle (jquery.min.js:2)
``` 

**Expected behavior**
Either wrong Format Tokens should not be accepted in the first place, or if they are, they should not result in a module-breaking error that can only be fixed by editing the settings.db of the current world.

**Foundry Information**
 - Foundry Version: 0.8.9
 - Simple Calendar Version: 1.3.75

**Comment by vigoren** [comment]
Sorry about that it is just capital Z that causes the issue (I accidentally left it in as a token that can be parsed but it doesn't do anything)
I will fix it for the next release.

Guessing that you were able to fix the issue on your end by editing the settings.db

**Comment by MOAM-Biggles** [comment]
Thanks for the quick response.

> Sorry about that it is just capital Z that causes the issue

This seems indeed to be the case, just my luck that this was part of my typo. 
So to clarify: The problem seems to occur with any Format Token ‘word' that contains a capital Z other than the valid 'YZ'.

>Guessing that you were able to fix the issue on your end by editing the settings.db

Yes, I could return to a valid configuration by editing that file while the game world instance was stopped.

**Comment by Elmaro** [comment]
How can this be fixed in Forge VTT? Deleting, uninstalling and cloning the world have not worked

**Comment by MOAM-Biggles** [comment]
> How can this be fixed in Forge VTT? Deleting, uninstalling and cloning the world have not worked

You need to first stop the game world instance.

Then you edit the file `settings.db` of your game world instance, located in  the folder `Data/worlds/[name_of_your_world_instance]`. 

In that file you'll have to replace the faulty entry for `foundryvtt-simple-calendar.general-configuration`. 

In my case it was simply replacing 

`\"dateFormat\":{\"date\":\"DD. MMMM YYYY Z\",\"time\":\"HH:mm:ss\",\"monthYear\":\"MMMM YAYYYY Z\"}`

with 

`\"dateFormat\":{\"date\":\"DD. MMMM YYYY YZ\",\"time\":\"HH:mm:ss\",\"monthYear\":\"MMMM YAYYYY YZ\"}`

Then save the file and restart your game world instance again.

Doing this while the instance is still running will have no effect, as your changes will be immediately overwritten by the game again.
