### ISSUE TITLE
[FEATURE] Multiple Calendars

### ISSUE THREAD

**Issue by B14d3r11** [vigoren/foundryvtt-simple-calendar#256]
Hi there, is it possible to add a feature to have multiple calendars "swappable"? My campaign setting has multiple moons and there are currently (up to 4) two calendars based on two of the moons. 

Both Calendars have the following in common
- There are 8 days a week
- There are 7 months a year
- There are 314 days in a year

The differences is that the month names are different and the day distribution to them is also different so say if you are 93 days into the year you are on Month 3, Day 15 but on the other calendar you are Month 3 Day 9

I am basically asking if its possible to have a drop down menu on the "floating widget" to "hot-swap" between the two calendars. Which basically takes its current day/year place and shifts it over to the other calendar.

**Comment by vigoren** [comment]
Support for multiple calendars is something I am currently working on so this will be coming!
