### ISSUE TITLE
Time Control Advance Round button

### ISSUE THREAD

**Issue by DariusWolfe** [vigoren/foundryvtt-simple-calendar#264]
**Is your feature request related to a problem? Please describe.**
I use PF2E which has some of its own time controls built in, but for a lot of purposes, Simple Calendar's UI is more convenient. There is one exception: If I want to bump time forward by 1 round. Simple Calendar has a setting to select how long a round is, but no simple way to advance by 1 round. 

**Describe the solution you'd like**
On the Time Controls section of Simple Calendar's UI, I'd like the option to advance by 1 round, in addition to the Second/Minute/Hour options

**Describe alternatives you've considered**
I can currently just click the Second button 6 times (or the 5 and 1, I suppose) or I can open the World Clock window within PF2E's options, but a simple one-click method would be greatly appreciated.

**Comment by vigoren** [comment]
I can look at adding something like this, it makes sense to me.
