### ISSUE TITLE
[BUG] Notes Re-Post to Chat On Refresh

### ISSUE THREAD

**Issue by Shuggaloaf** [vigoren/foundryvtt-simple-calendar#266]
**Describe the bug**
When refreshing Foundry, all notes for that day that triggered (displayed to chat) before the current time will trigger again. This happens on both all-day events as well as specific timed events. 

**To Reproduce**
1. Add a few notes.
2. Advance time past when events fire.
3. Refresh Foundry. All events post to chat again.  

**Expected behavior**
Would expect events to only fire once. Perhaps a flag can be used for each added note that is destroyed at 12:00AM the next day?

**Foundry Information**
 - Foundry Version: 0.8.9
 - Game System: DnD5e 1.5.3
 - Simple Calendar Version: 1.3.75

**Browser (please complete the following information):**
 - OS: Win 10 x64
 - Browser: Chrome/Electron
 - Browser Version: Chrome ver. 96.0.4664.93

**Comment by vigoren** [comment]
The behavior around this is on loading in I run a check to see if any notes on the current day have passed then post them as a reminder. The idea is that you logged in again for the next session and these would be a reminder for what happened. 

There is no technical difference between loading the page for the first time or refreshing the page so I can't tell the difference there.

What I can do is add a setting to disable the note reminders on loading in.

**Comment by Shuggaloaf** [comment]
> The idea is that you logged in again for the next session and these would be a reminder for what happened.

OK makes sense. Unfortunately, in practice, I think many people may be refreshing at least a time or two per game. 

>There is no technical difference between loading the page for the first time or refreshing the page so I can't tell the difference there.

Totally understood. And using flags wouldn't really help because I would assume that closing foundry also looks the same as refreshing as well. So no way to reset the flag to say "ok session over, not just refreshing". Ah, too bad. 

Actually... now that I think about it, is that the case? I know some things like the .db files don't update until FVTT is actually closed, not just refreshed. Any way to build off of that? Flag, Journal Entry, whatever that gets updated when the .db files get updated. That way it would know Foundry was actually shut down (not just refreshed) and the flag (or whatever) could be set at shut down to display notes on the next login, then set to not display. And since a refresh wouldn't change it, it would not display the notes until the next shutdown when the flag was again changed. 
Hopefully that made any kind of sense. lol

>What I can do is add a setting to disable the note reminders on loading in.

If the above is not possible, or just too much work, then I think this would be a good work-around. 

Thanks @vigoren!

**Comment by Shuggaloaf** [comment]
_Edited point 2 above for readability. Hopefully the thought is expressed more clearly._

**Comment by vigoren** [comment]
I think I will just keep this as a setting to disable the reminders on loading in. Not everyone shuts their severs down after a session (myself included) so tying it to the shutdown and restart of foundry wouldn't work for those situations.

**Comment by Shuggaloaf** [comment]
>Not everyone shuts their severs down after a session

Perfectly valid point that I had not considered. I know a lot of people use Forge (or similar) or host on a rPi. Thought I had a good idea there too! lol
