### ISSUE TITLE
[BUG] Raw day in API starts at 0 instead of 1

### ISSUE THREAD

**Issue by TheBird956** [vigoren/foundryvtt-simple-calendar#267]
**Describe the bug**
When accessing the current raw day from the API, the first day of the month is 0 instead of 1

**To Reproduce**
1. Call `SimpleCalendar.api.timestamp()` and pass it to `SimpleCalendar.api.timestampToDate()`
2. Read `data.day`
3. Day will be 0 if you are on the first day of the month

**Expected behavior**
The returned day should not have a value of 1 **below** what it should be

**Foundry Information**
 - Foundry Version: v9 build 238
 - Game System: DnD5e

**Browser (please complete the following information):**
 - OS: Pop_OS! 21.04
 - Browser: Brave
 - Browser Version: Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

**Comment by vigoren** [comment]
Hey sorry about the delay in responding to this I took the holidays off from developing.

As per the [documentation](https://github.com/vigoren/foundryvtt-simple-calendar/blob/main/docs/API.md#date-object) the day value returned for `data.day` is the day index of that day in the month. This is to somewhat future proof the day number if a feature is every added where the day number is not used or is something use internally (like intercalary months have negative numbers associated with them).

For the display number of the day I would use `data.display.day` as this will be whatever that day is configured to be displayed as (right now just its numeric representation)

**Comment by TheBird956** [comment]
Ok, however I am a bit worried that `data.display.day` could potentially not be a numeric value of the current day, which is why I went with `data.day` in the first place.

I would suggest that since `data.day` is in index, it should be renamed to `data.dayIndex` to avoid confusion (though renaming it will create confusion for everyone using the API)

**Comment by vigoren** [comment]
I have been thinking about this and have come up with this plan that should satisfy what you are after:

- Leave `date.day` as is so the update doesn't break any other modules relying on that being the index.
- Ensure that `data.display.day` is ALWAYS the numeric representation of the day (just like how `data.display.month` is always the numeric representation of the month). It will still be returned as a string but will be a number and can be parsed out if needed to be manipulated.
- If/when days get updated to have a named display (as opposed to numeric) I will add a new property `data.display.dayName` to the display object that will contain that days non numeric display. This will keep days inline with how I currently handle months.

I think I will also expose a new API function(or update the [existing one](https://github.com/vigoren/foundryvtt-simple-calendar/blob/main/docs/API.md#simplecalendarapiformatdatetimedate)) for formatting the date/time with a custom passed in format string so you could then just specify the format tokens you want to use to display the date and make SC actually put the final string together.

**Comment by TheBird956** [comment]
Having the API function sounds like a great idea and I would definitely use that!

Sounds good for the naming of the day/dayName
