### ISSUE TITLE
[QUESTION] new note over macro

### ISSUE THREAD

**Issue by Talaren** [vigoren/foundryvtt-simple-calendar#268]
It is possible to add a new note over a macro?
because for the Treat Wounds to remember how long the cd for the person is.

Greetings Talaren

**Comment by vigoren** [comment]
Hey! There is not a way to do this through a macro yet but there will be in the next update. I am currently working on a large update that includes changes to how notes are handled in the backend, with these changes in place adding the ability to create a note through a macro will be added.
