### ISSUE TITLE
Requesting V9 Update PLEASE

### ISSUE THREAD

**Issue by PhluXx1** [vigoren/foundryvtt-simple-calendar#269]
I would really love to see this get updated to v9 it's so important to my campaign. My players use it all of the time and it really helps keep track of everything. Please tell me you'll be updating this and when we can expect this fantastic module?

**Comment by vigoren** [comment]
Hey!
Simple Calendar works just fine on V9, so you can continue to use it without issue. Foundry is just warning users as I haven't made a release to say it is compatible with v9. I am am in the middle of a large update for Simple Calendar that when done will remove that warning from Foundry.

All that said it is perfectly fine to keep using the current release of Simple Calendar in V9.
