### ISSUE TITLE
[BUG] Players see GM-only events in search

### ISSUE THREAD

**Issue by iComputerfreak** [vigoren/foundryvtt-simple-calendar#272]
**Describe the bug**
When a player searches the calendar for the name of an event or month, they can see all events that match the search parameter, including events that are marked as not visible to players.

**To Reproduce**
1. As a gamemaster, create a new event in the calendar called "Test-Event". Do **not** set "Player Visible".
2. Log in as a player and search the calendar for the query "Test" or the name of the month in which the Test-Event was created.
3. The player sees the Test-Event in the search results, even though he should not be able to.

**Expected behavior**
The player should not find the GM-only events in his search results.

**Screenshots**

**Foundry Information**
 - Foundry Version: 9, Build 242
 - Game System: DnD5e 1.5.6
 - Simple Calendar Configuration: [simple-calendar-export.txt](https://github.com/vigoren/foundryvtt-simple-calendar/files/7926908/simple-calendar-export.txt) (I renamed the file from .json to .txt to be able to upload it on GitHub)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Browser Version 96.0.2

**Comment by vigoren** [comment]
That's not supposed to happen. I will look into it and fix it for the next release.

Sorry about that
