### ISSUE TITLE
[FEATURE] Old UI back?

### ISSUE THREAD

**Issue by yjeroen** [vigoren/foundryvtt-simple-calendar#275]
![image](https://user-images.githubusercontent.com/1303988/151875935-5b22ebc5-a599-4c00-81a5-11b8cab56c10.png)

Can there be an option to use this old UI?

**Comment by vigoren** [comment]
That was never the UI of simple calendar. That was/is the UI for the module [Weather Control](https://foundryvtt.com/packages/weather-control) (formerly Calendar/Weather). You can use that module to get that UI back of you would like!
