### ISSUE TITLE
[BUG]  Current year before calendar start year causes problems with hour/day advance.

### ISSUE THREAD

**Issue by tposney** [vigoren/foundryvtt-simple-calendar#276]
**Describe the bug**
If the current year is less than the year 0 value in the calendar with the clock running, time moving forwards causes strange behaviour.  
Around times of 22:58:55 advancing to 22:59:00 skips to 23:00,
And around 23:58:55 -> 23:59:00 skips to 00:00 and the current date gets confused.

**To Reproduce**
see above

**Expected behavior**

**Screenshots**

**Foundry Information**
 - Foundry Version: 9.245
 - Game System: any
 - Simple Calendar Configuration: Use SC gregorian but set the start year to 1970 and current year to 1400.

**Browser (please complete the following information):**
multiple at least chrome linux/windows, but I don't think it is relevant.

**Additional context**
Was flagged to me by @Kalos

**Comment by vigoren** [comment]
I will look into this. This shouldn't cause an issue as time of day is stored separately from the current year but something odd could be going on

**Comment by vigoren** [comment]
This was a tricky one but i figured out the issue and it will be fixed in the next release.
