### ISSUE TITLE
[BUG] Configuration changes not applied.

### ISSUE THREAD

**Issue by thes33** [vigoren/foundryvtt-simple-calendar#277]
**Describe the bug**
Cannot change Starting Week Day or Leap Year Settings.  Configurations are not changed.

**Foundry Information**
 - Foundry Version: [ v9 b249]
 - Game System: [PF2e]
 - Simple Calendar Configuration: None (no interaction)

**Comment by vigoren** [comment]
With Pathfinder 2 there is a setting called [PF2e Sync](https://github.com/vigoren/foundryvtt-simple-calendar/blob/main/docs/Configuration.md#pathfinder-2e-world-clock-sync) that is used to force the Pathfinder system clock and simple calendar to stay in sync. This forces a few settings to always be certain values (specified in the docs).

If you don't care about the Pathfinder system clock and simple calendar staying in sync together then you can disable that setting and change the other settings to what you need.

**Comment by thes33** [comment]
That did it, thanks!  I could have sworn I unchecked that.
