### ISSUE TITLE
Pathfinder 2E: World Clock Sync checkbox sets the year wrong

### ISSUE THREAD

**Issue by NikolasTzimoulis** [vigoren/foundryvtt-simple-calendar#279]
When the default [Pathfinder 2E: World Clock Sync](https://github.com/vigoren/foundryvtt-simple-calendar/blob/main/docs/Configuration.md#pathfinder-2e-world-clock-sync) setting is checked, the simple calendar and world clock are not correctly synced, they are off by 2700 years.

![4720vs7420](https://user-images.githubusercontent.com/380852/153115558-930a07ce-4dfa-4112-b333-30b82b5cbfca.png)

**Comment by vigoren** [comment]
Yeah this seems to have happened after one if the recent updates to the PF2e system. I will fix it for the next release

**Comment by Elmaro** [comment]
Seeing that in DnD5e there is also a problem
