### ISSUE TITLE
[FEATURE] Option for player notes

### ISSUE THREAD

**Issue by 9ryex5** [vigoren/foundryvtt-simple-calendar#28]
Please add the option for GMs to allow players to create notes

**Comment by vigoren** [comment]
I have figured out a way to do this, the only caveat is that a GM has to be connected for players to add notes. This shouldn't be too big of a hurdle though in my opinion.

Players will also be able to edit and delete their own notes.

All notes added by players are visible to all other players.

I have added the functionality and am just testing it out and catching edge cases.

This will be apart of the next release.

**Comment by vigoren** [comment]
This has been added in the 1.20 release
