### ISSUE TITLE
[FEATURE] Provide an api way of identifying what calender is installed

### ISSUE THREAD

**Issue by Moonpile** [vigoren/foundryvtt-simple-calendar#280]
"SimpleCalender.api.name" seems to always return "'O'".  It would be nice if name allowed us to set the name of the calendar, or at least the .json export would have a name and id to help systems and modules identify what calendar is installed.  I see you are looking at doing multi-calendar support, so I imagine that would have to include some way of identifying the calendars.

**Comment by vigoren** [comment]
Hey, yes I am adding multi calendar support and there will be ways through the API to get the current calendar as well as all configured calendars.

Just finishing up some other features then that will be released
