### ISSUE TITLE
[BUG] v2  Beta - Module error in console

### ISSUE THREAD

**Issue by vt-tom** [vigoren/foundryvtt-simple-calendar#291]
**Describe the bug**
When i activate the Module Beta i get an error in the console. If i try to open the calendar from the sidebar, i get another error.

**To Reproduce**
1. Start the world
2. activate the module
3. try to open the tool in the sidebar

**Screenshots**
errors:
![grafik](https://user-images.githubusercontent.com/80099175/160371653-3605195a-04e6-4ba9-8f96-e9c1cbac8988.png)

**Foundry Information**
 - Foundry Version: [9.255]
 - Game System: [DSA/TDE 5th Edition Version 3.2.3]
 - Simple Calendar Configuration: [no config]

**Browser (please complete the following information):**
 - OS: [WIN10]
 - Browser [chrome]
 - Browser Version [99]

**Comment by vigoren** [comment]
Hey, sorry about this. It is an issue when using languages other than English.

Switching to English will allow the module to load.

Or if you are comfortable in doing this you can extract the attached zip in the directory where Foundry stores its data, open the modules folder, then the simple calendar folder and finally the lang folder
( on windows it would be %LocalAppData%\FoundryVTT\Data\modules\foundryvtt-simple-calendar\lang )

[lang.zip](https://github.com/vigoren/foundryvtt-simple-calendar/files/8363992/lang.zip)

I have made the fix and it will be in the next version of the beta but this would allow you do not have to wait for that to be released.

**Comment by vt-tom** [comment]
Ah thank you. I used the zip file and it worked. Now i can start testing.
