### ISSUE TITLE
[BUG] In "Unofficial Old School Essentials" game.time.worldTime does not consistently update when rounds are advanced

### ISSUE THREAD

**Issue by MaineQat** [vigoren/foundryvtt-simple-calendar#295]
**Describe the bug**
Using only "Unofficial Old School Essentials" system and Simple Calendar, when advancing combat rounds, game.time.worldTime does not update (or at least sync to client) consistently.  Advancing time directly (e.g, +30 seconds) will then apply all accumulated time from the rounds in addition to the amount chosen to advance.

The Simple Calendar hud clock **does** correctly update and advance in increments as combat rounds are advanced, even while worldTime does not.

**To Reproduce**
1. Begin a combat
2. Check `game.time.worldTime` in console
3. Advance one or more game rounds
4. Check `game.time.worldTime` in console, value most likely won't reflect the actual changes
5. Directly advance by 

**Expected behavior**
game.time.worldTime updates consistently in sync with the displayed clock when rounds are advanced

**Foundry Information**
 - Foundry Version: 9.255
 - Game System: OSE
 - Simple Calendar Configuration: Default settings (fresh install with only OSE plus SC)

**Browser (please complete the following information):**
 - OS: mac
 - Browser: Chrome
 - Browser Version: 99.0.4844.74

**Additional context**
Tested with a fresh dnd5e+simplecalendar and it works as expected.

**Comment by vigoren** [comment]
Thanks for the report! This will be fixed in the next release.
