### ISSUE TITLE
[FEATURE] official integration of the DSA/TDE Calendar

### ISSUE THREAD

**Issue by vt-tom** [vigoren/foundryvtt-simple-calendar#296]
**Is your feature request related to a problem? Please describe.**
While im testing the BETA, i asked myself one question: why cant we implement the calendar of Das Schwarze Auge/The Dark Eye 5th Edition in Simple Calendar?
I asked the publisher an get the ok for it. So if you are interested contact me. 

I manually implemented the calendar in my foundry, maybe we can use it?

**Comment by vigoren** [comment]
I could absolutely add the calendar as a predefined one in Simple Calendar.
If you export your calendar and send it to me I can use that as the base for the DSA/TDE Calendar in Simple Calendar!

**Comment by vt-tom** [comment]
Here is an export of the file. But there are some vacations as notes. Can i export them somehow too?

**Comment by vt-tom** [comment]
I saw that in v2 i can also export the notes. So i tried it with my calendar. Maybe you can see the vacations in it.
[simple-calendar-export_dsa_calendar.zip](https://github.com/vigoren/foundryvtt-simple-calendar/files/8378354/simple-calendar-export_dsa_calendar.zip)
