### ISSUE TITLE
[QUESTION] Change name of notes folder

### ISSUE THREAD

**Issue by Barti-meaus** [vigoren/foundryvtt-simple-calendar#297]
Hello, 
can I change the name of the note's folder? Currently, the name of the folder is "_simple_calendar_notes_directory". If I change the folder name, the module ignores it and creates again the folder with the name "_simple_calendar_notes_directory". 

Did I miss a something in the configuration, or would it be an additional function?

Thanks!

PS: thank you very much in general for creating and updating this module!!!

**Comment by vigoren** [comment]
Oh this looks like a bug, or I forgot to allow for it. Either way in the final release you will be able to rename the folder!
