### ISSUE TITLE
[BUG] V2 Beta Calendar display is not syncing correctly with current date

### ISSUE THREAD

**Issue by Chronolegionnaire** [vigoren/foundryvtt-simple-calendar#298]
**Describe the bug**
Calendar display is not showing the correct date for these format tokens DO MMMM dddd. Using a custom calendar (just simple reskinned gregorian calendar)

**To Reproduce**
Use any of these tokens DO MMMM dddd in display setting
Calendar will show wrong day in bottom left clock and the time display when you click the bottom left clock.

**Expected behavior**
Correct date should be shown

**Screenshots**
![Capture](https://user-images.githubusercontent.com/69740347/162545328-6f9c1016-63ef-464b-815a-c895b3b1b6f8.PNG)

The correct display should be Junith (june) 20th Moondus (Monday) 1:00PM

**Foundry Information**
 - Foundry Version: [e.g. 0.8.4]
 Foundry v9 build 255
 - Game System: [e.g. DnD5e]
 Pathfinder 2e v3.8.3
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
 Windows
Chrome
 - Browser Version [e.g. 22]
Version 100.0.4896.75

**Additional context**

**Comment by Chronolegionnaire** [comment]
[simple-calendar-export.zip](https://github.com/vigoren/foundryvtt-simple-calendar/files/8455772/simple-calendar-export.zip)

Attached is my exported configuration

**Comment by vigoren** [comment]
Thanks for the report.

The bottom left clock is not part of simple calendar and I am not sure which module does that.

That said there is an issue with the clock (and a few other cases I found) so I have updated those cases so the correct date/time will be shown. That will be apart of the release! 

These changes may have fixed the bottom left clock too, if you can let me know what module that is I can test.

**Comment by Chronolegionnaire** [comment]
I believe that is the built in clock for the pf2e system. I will confirm soon as I get a chance tonight!

**Comment by Bryantbakeraz** [comment]
The clock from there is added by PF2e Tweaks by Ustin

https://gitlab.com/Ustin/pf2e-tweaks

**Comment by Chronolegionnaire** [comment]
That clock is from PF2e tweaks by Ustin

https://gitlab.com/Ustin/pf2e-tweaks

**Comment by vigoren** [comment]
Awesome thanks! With my changes the date is now displaying more correct. The end day and month name are always there, it seems that specific module is adding in the time, day and month separately.

So when you update the time display to include the day and month they will be duplicated in this instance. So that is something that specific module would have to address.

Hope that makes sense.

**Comment by Chronolegionnaire** [comment]
Makes perfect sense, thanks for your speedy responses and your awesome module!
