### ISSUE TITLE
[BUG] V2 Can't control the New Moon Day

### ISSUE THREAD

**Issue by SwordofSpirit** [vigoren/foundryvtt-simple-calendar#300]
The New Moon Day field is blank and non-functional.

I was unable to adjust this field in the Greyhawk calendar, as well as in a new custom calendar. On first creating a new calendar it can be accessed, but then it becomes stuck and cannot be adjusted.

EDIT: After playing around some more, I determined that even when the field is accessible (which seems to be intermittent), for some reason the calendar doesn't want to abide by what I put it in!

Example, I made a super simple calendar (364 days, 13 28-day months of 4 7-day weeks and a single moon with 28-day lunar cycles) and set the new moon as Day 1 of Month 1. I also changed the cycle adjustment to 0. I left the remaining lunar settings on default, so New Moon, First Quarter, Full Moon, and Last Quarter are a single day each, and the other phases are 6 each. But when I look at the calendar Day 1 of Month 1 gives me a waning crescent, while both days 2 and 3 give me a new moon. Flipping through the months, some of them double up their single day days, and others don't.

I wish I could better determine what's going wrong, but that was the best I could do, because soon after I tried adjusting the new moon date to the last day of the previous year to see if that would help, the calendar decided to freeze, and on restarting Foundry I get this error when trying to access the calendar:

foundry.js:319 TypeError: Cannot read properties of undefined (reading 'numericRepresentationOffset')
[Detected 1 package: foundryvtt-simple-calendar]
    at Yt.dateToDays (index.js:1)
    at Ye.getDateMoonPhase (index.js:1)
    at Ye.getMoonPhase (index.js:1)
    at Qe.getData (index.js:1)
    at Qe._render (foundry.js:3062)
    at Qe.render (foundry.js:3021)
    at Qe.showApp (index.js:1)
    at SceneControls._onClickTool (foundry.js:51799)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)

Thanks for all your hard work, this is going to be pretty awesome when we get the bugs ironed out.

**Comment by vigoren** [comment]
Thanks for the report! This is something I meant to change but had forgotten. I plan to have it be a selector similar to have you choose a seasons starting month and day rather than drop downs. I'll get this fixed up before release
