### ISSUE TITLE
[BUG v2] Stopping the Pause causes the time to go on in a fight. 

### ISSUE THREAD

**Issue by vt-tom** [vigoren/foundryvtt-simple-calendar#304]
**Describe the bug**
I have the problem, that in a fight, the time only stops if i have the pause activated. When i deactivate the pause, so my players can move, the time goes on. I think this is a not desired behaviour? 

Side note:
if i also use Smalltime and configure it to control the time, the time remains stopped if i deactivate the pause.

**To Reproduce**
1. Start a battle
2. Press Space to end the pause

**Foundry Information**
 - Foundry Version: 9.269
 - Game System: DSA/TDE 5th Edition 3.3.1
 - Simple Calendar Configuration: BETA v2.2

**Comment by vigoren** [comment]
I have not been able to replicate this particular issue. Here is what I have done, step by step, perhaps I am missing a step or another module is interfering in some way.

Foundry Version: 9.269
Game System: DSA/TDE 5th Edition 3.3.1
Simple Calendar Configuration: v2.0.0-beta.2
No other Modules installed.
Time Setting Unify Clock Start/Pause with Game Pause enabled.

* New Scene
* Add an actor
* Start Simple Calendars real time clock (game will unpause)
* Start a Combat with the actor (Simple Calendars clock will pause)
* Advance combat rounds (time will advance 6 seconds/round)
* Pause the game with the space bar (Simple Calendars clock will remain paused)
* Unpause the game with the space bar (Simple Calendars clock remains paused)
* End combat (Simple Calendars clock will start again)

If those steps are working for you then it could be something else at play here, but I am interested to see if your steps are similar or different.

**Comment by vt-tom** [comment]
Ah i see, its a problem which occurs if times-up is active. But without Timesuop, my effects don't dissappear after the adjusted time. But i have to send a bug report to the timesup developer, or?

**Comment by vt-tom** [comment]
So i did just another few tests:
Another Server with
Foundry Version: 9.269
Game System: DnD5E 1.5.7
Simple Calendar Configuration: v1.3.75
TimesUp: 0.8.32

No Problem, i can Start a Combar and deactivate the Pause without the clock running any further.

2nd Test
Foundry Version: 9.269
Game System: DnD5E 1.5.7
Simple Calendar Configuration: v2.0.0-beta.2
TimesUp: 0.8.32

Here i got the Same error. So ist only occurs with Simplecalendar v2.0.0-beta2 and TimesUp: 0.8.32 active. Not with the older Simplecalendar Version. Maybe this helps to identify the problem?

**Comment by vigoren** [comment]
Times up and simple calendar shouldn't really interact with eachother in that way. I'll check it out on my end first to see what the conflict might be.

**Comment by vigoren** [comment]
Is the scene you are testing in the active scene (will have a little target next to its name)?

I have only been able to replicate this if the combat is not in the active scene. This is how the real time clock is designed so that if there is an old scene with an old combat still running it doesn't prevent you from using the clock in newer active scenes.

**Comment by vt-tom** [comment]
Ah that might be, because it's my development Foundry installation.

I will test it as soon as I can and give you an answer.

**Comment by vt-tom** [comment]
Okay, in one foundry instance, the Scene was not active and it was an older scene.
In the second foundry instance it was the active, but an old scene. 

In both cases i could fix the problem in creating new scenes, where the error not occurs.

**Comment by vigoren** [comment]
Interesting. Simple Calendar doesn't set anything in Scenes at all.

All I do is check to see which scene is set as the active one and if there is a combat running in that scene. If yes, then pause the clock, if no then the clock can run.

Maybe the scenes had something strange happen to them in foundry, like combat data not being properly or completely set. Either way I don't think there is much I can adjust here as my way of checking is pretty simple and the only way that I know of to do so.

**Comment by vt-tom** [comment]
Okay, then i would say you close this one and i will keep an eye on this with new scenes in my ongoing campaign worlds?

**Comment by vigoren** [comment]
That sounds good to me! Please let me know if you keep encountering this issue
