### ISSUE TITLE
Calendar doesn't advance year on Abadius 1

### ISSUE THREAD

**Issue by ckdragons** [vigoren/foundryvtt-simple-calendar#305]
**Describe the bug**
Using PF1E Golarian calendar, advancing the day from Kuthona 31 to Abadius 1 does not advance the year. The year remains the same.

**To Reproduce**
1. Select Kuthona 31 and set Current Date
2. Click on Dawn to advance to next dawn, which should be Abadius 1
3. Date changes to Abadius 1 but the year stays the same

**Expected behavior**
Expect the year to increase by 1 (or decrease by 1) at the end of the calendar year.

**Foundry Information**
 - Foundry Version: 0.9.269
 - Game System: PF1E
 - Simple Calendar Configuration:
 
**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 99.0.1

**Comment by vigoren** [comment]
This should be resolved in the latest release
