### ISSUE TITLE
[BUG] After migration, settings panel won't open

### ISSUE THREAD

**Issue by GHScrapper** [vigoren/foundryvtt-simple-calendar#309]
**Describe the bug**
I updated to version 2 and got the panel saying it was auto-migrating. It never migrated the notes to the journal. All notes are gone. When I try to open the settings panel, nothing happens. When I try to run the clock, I get a yellow circle, but time does not advance.  Uninstalling and reinstalling did not help. The custom month names are still there, and phases of the moon. 

**To Reproduce**
I'm not sure this can be reproduced by others but:
1. Open the calendar.
2.  Click on settings gear.
3. Nothing happens
4. Same thing occurs in Foundry module settings panel, click on the box for SC settings, nothing.

**Expected behavior**
Settings panel should open when clicking on settings gear

**Screenshots**
Not a screenshot but here is a copy-paste of the error in console:
    
       Simple Calendar  | Error "Cannot read properties of undefined (reading 'player')"
TypeError: Cannot read properties of undefined (reading 'player')
    at Function.clonePermissions (https://assets.forge-vtt.com/bazaar/modules/foundryvtt-simple-calendar/v2.0.0/index.js:1:74628)
    at Oe.clone (https://assets.forge-vtt.com/bazaar/modules/foundryvtt-simple-calendar/v2.0.0/index.js:1:74883)
    at Ye.initializeAndShowDialog (https://assets.forge-vtt.com/bazaar/modules/foundryvtt-simple-calendar/v2.0.0/index.js:1:77054)
    at Pe.configurationClick (https://assets.forge-vtt.com/bazaar/modules/foundryvtt-simple-calendar/v2.0.0/index.js:1:128175)

**Foundry Information**
 - Foundry Version: [9]
 - Game System: [DnD5e]
 - Simple Calendar Configuration: Not sure what you want here. If it's info from the settings panel, I can't see it.
 - Running using The Forge if that matters, installed from the Bazaar there. Never had a problem with any module doing this before, nor with SC v. 1.

**Browser (please complete the following information):**
 - OS: [Win10]
 - Browser [Edge]
 - Browser Version [101.0.1210.39 (Official build) (64-bit)]

**Additional context**
The migration never seems to have finished. It just spun for a long time (30 min + ). I had a few notes but not that many -- so I can't imagine it would take longer than that to migrate notes. No notes seem to have been migrated, no new journal entries were made. Settings won't open from the gear on the calendar or from the module settings panel in the general foundry module section.

**Comment by vigoren** [comment]
Hey, sorry you ran into an issue. It seems like the migration may have run into an issue when moving over the permissions. If you open the console of the browser and run this command, do any errors happen? `SimpleCalendar.api.runMigration()`

**Comment by GHScrapper** [comment]
I get the following error after the step of "Migrating Calendar Notes", I've included stuff above the error so you can see where it is in the sequence in context (the actual red error message starts on the line "Uncaught..."): 

Simple Calendar  | Migrating Calendar Notes...
foundry.js:273 DEBUG | Calling preUpdateSetting hook with args:
foundry.js:274 (4) [Setting, {…}, {…}, 'Ee2asUJ7zc0WzSmS']
foundry.js:273 DEBUG | Calling preUpdateSetting hook with args:
foundry.js:274 (4) [Setting, {…}, {…}, 'Ee2asUJ7zc0WzSmS']
Promise {<rejected>: TypeError: Cannot read properties of undefined (reading 'year')
    at Function.runNoteMigration (h…}
index.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'year')
[Detected 1 package: foundryvtt-simple-calendar]
    at Function.runNoteMigration (index.js:1:185091)
    at Lt.runNoteMigration (index.js:1:189287)
    at Lt.run (index.js:1:187781)
    at Module.ht (index.js:1:142468)
    at <anonymous>:1:20

**Comment by vigoren** [comment]
Thank you, I think I have a fix figured out for this. Will do a release later tomorrow.

**Comment by vigoren** [comment]
I think the latest update will fix this issue, if you can please up and try running the migration again to see what happens. You can run the migration again by opening the console of the browser and running this command `SimpleCalendar.api.runMigration()`
And please let me know how it goes! Again sorry for the issues

**Comment by GHScrapper** [comment]
Worked! Thanks for the quick response and trouble-shooting.

Also, you have no need to apologize. I am super grateful that you have made this module and offered it to the community....  I do coding as part of my job so I know bugs happen. And when you think you squashed them, they turn into undead zombie bugs and return worse than ever....

**Comment by vigoren** [comment]
Glad it worked! I always get nervous about data loss for users when doing a migration so was disappointed I let a bug slip through the migration process lol
