### ISSUE TITLE
Messed up ui

### ISSUE THREAD

**Issue by ShahynRox** [vigoren/foundryvtt-simple-calendar#313]
Hello!
Right after the latest update the ui of Simple Calendar ist messed up, when I start my world via The Forge VTT. 
This happens in Chrome and Firefox.
The calendar-screen is far to big and the fonts seem to be too large. Looks like wrong css. Huge sunrise and sun
Buttons under calendar (new note, search, settings, etc.) don't work.
Changing style doesn't help.
Also the module setup in the game settings seems to be corrupt.

I attached some screenshots.

Best regards, Shahyn

**Foundry Information**
 - System Language: German
 - Foundry Server Version: 9
 - Game System: [e.g. TDE5, Das Schwarze Auge 5]
 - Simple Calendar Configuration: -

**Browser (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser; Mozilla Firefox, Chrome
 - 
![Simple Calendar Issue 01](https://user-images.githubusercontent.com/88293425/167643638-cba8992f-999c-4313-842b-19a99d510600.jpg)
![Simple Calendar Issue 02](https://user-images.githubusercontent.com/88293425/167643669-b7f7230e-2891-4f4a-bf0e-60083f73cdeb.jpg)

**Comment by vigoren** [comment]
This looks like the CSS isn't being loaded at all, which is causing issues for both the main view and setting view. If you open your browser's console (F12 on Windows) are there any errors being shown?

**Comment by vigoren** [comment]
Closing this issue as I have been unable to replicate it and have not heard back about the questions asked.
