### ISSUE TITLE
[BUG] Forgotten Realms: Harptos - duplicate notes

### ISSUE THREAD

**Issue by MalakanC** [vigoren/foundryvtt-simple-calendar#314]
**Describe the bug**

Use of the Quick Setup option for the `Forgotten Realms: Harptos` calendar yields duplicate notes for each built-in event.

**To Reproduce**
1. Go to the Quick setup settings option
2. Select `Forgotten Realms: Harptos`
3. Go to any pre-built calendar event (e.g. Spring equinox - Ches 19)

**Expected behavior**

Single note per event

**Screenshots**

![image](https://user-images.githubusercontent.com/39969354/167680316-cd01bfd3-396b-44f9-b928-ce8e43dce76b.png)

**Foundry Information**
 - Foundry Version: 9.269
 - Game System:  DnD5e 1.6.1 & DnD5e 1.5.7
 - Simple Calendar Configuration: Default, only did the quick setup.

**Browser (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Browser Version 101.0.4951.54 (Official Build) (64-bit)

**Comment by vigoren** [comment]
Hey, this is actually just a visual bug that happens right after applying a predefined calendar. The notes are not actually duplicated, if you refresh your browser the counts will show correctly that there is just 1 note on those days. The next update will have a fix for this!

**Comment by MalakanC** [comment]
Can confirm, refresh does remove the duplicate for me

**Comment by vigoren** [comment]
This issue has been fixed in the latest release
