### ISSUE TITLE
[FEATURE] Option to use greyscale/classic button in token controls

### ISSUE THREAD

**Issue by MrPotatoZed** [vigoren/foundryvtt-simple-calendar#316]
The new design for the calendar button in token controls is very slick, as are all the UI updates. Someone obviously put some time into making a button that pops and looks attractive. However, it being the only button in color makes it stand out in a way that's arguably too intrusive. If it's not too much trouble having an option to use the classic button style would be appreciated. Thanks for all the hard work you've put into this.

**Comment by vigoren** [comment]
I have toned down the icon so it stands out way less in the latest release!
