### ISSUE TITLE
[BUG] [Minor] When scrolling through the calendar, the year does not change

### ISSUE THREAD

**Issue by MasterZelgadis** [vigoren/foundryvtt-simple-calendar#318]
When scrolling through the calendar, the year does not change. Tested in Golarion (2e) and gregorian calendar.
If you click on a day to create a note, the date is correct, but above the calendar displayed is always the current year

Steps to reproduce:
Scroll through the calendar with the arrow buttons and cross the year border

Expected behaviour:
The year should increase by 1

Actual behaviour:
The year stays the same

Impact:
Minor, only UI, calculations are correct

Version:
Foundry V9 Build 269
Simple Calendar 1.3.75

**Comment by vigoren** [comment]
This issue is fixed in the most recent release (2.0.4) Due to an issue the best way to update is uninstall/reinstall Simple Calendar, explanation [here](https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v2.0.4).
