### ISSUE TITLE
[FEATURE] Have a way to display dawn/dusk without actually setting the time.

### ISSUE THREAD

**Issue by kiligir** [vigoren/foundryvtt-simple-calendar#319]
The ability to set when sunrise/sunset is and have SC do all the work is great! I just wish there were a way to actually know the time for dawn/dusk (which gets asked a lot) without having to actually press the button. Just having it show up in parentheses in the tooltip would be plenty, but somehow showing up in the notes for each day would also be wonderful. Thank you for the great mod!

**Comment by vigoren** [comment]
This has been added in version 2.1.18. You can now right click on a day to see a menu that will show the sunrise and sunset times for that day.
