### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by CasualTerror** [vigoren/foundryvtt-simple-calendar#320]
**Describe the bug**
Time does not pause while in combat

**To Reproduce**
1. start combat

**Expected behavior**
Time to pause and then increase by amount set on "second per Combat Round" when a new round starts

**Foundry Information**
 - Foundry Version: current [version 9]
 - Game System: current [1.6.1
 - Simple Calendar Configuration: [v2.0.4]

**Browser (please complete the following information):**
 - OS: Windows
 - Browser Opera GX 
 - Browser Version 85.0.4341.79

**Comment by vigoren** [comment]
Is the scene the combat is in set to be the active scene? That is required for Simple Calendar to pause the time automatically.

**Comment by vigoren** [comment]
If you run into this issue again when the combat is in the active scene please let me know!
