### ISSUE TITLE
[BUG] There is no GM present in the game

### ISSUE THREAD

**Issue by bugbeersandflagons** [vigoren/foundryvtt-simple-calendar#321]
**Describe the bug**
When logged in as a player, adding a new note to the calendar results in message "There is no GM present in the game"

**Expected behavior**
The update notes suggested that this should now work regardless of a GM being present.  I am on version 2 of simple calendar, and the latest version of foundry and 5e game system

**Screenshots**
![image](https://user-images.githubusercontent.com/85903357/168273251-22bd184d-d9ba-43a9-ad08-23d0eff51548.png)

**Foundry Information**
 - Foundry Version: 9 build 269
 - Game System: DnD5e v1.6.1

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Browser Version 100.0

**Comment by bugbeersandflagons** [comment]
Update - I use a journal replacement mod, Monk's Enhanced Journal - could be a clash between these 2 modules messing with the permissions?

**Comment by vigoren** [comment]
I am able to replicate this with out Monks Enhance Journal, so I will fix this soon. Not sure how that got in there

I haven't tested with Monks Enhanced Journal so there could be other issues
