### ISSUE TITLE
[BUG] Unable to use with localization mod

### ISSUE THREAD

**Issue by bnp800** [vigoren/foundryvtt-simple-calendar#322]
**Describe the bug**
When using this mod with another mod which provides localization for many mods, this mod will stop working

**To Reproduce**
1. Install mod `mega_chn` [https://github.com/fvtt-cn/mega_chn](url)
2. Enable this mod and `mega_chn`
3. On load click the `SC` button in left control panel
4. See error in console

**Expected behavior**
Open the Simple Calendar app

**Screenshots**
![image](https://user-images.githubusercontent.com/69395973/169191379-a0db179d-77e7-4e99-a275-fac69ae11e6a.png)

**Foundry Information**
 - Foundry Version: v9
 - Game System: tested in pf1, swade, dnd3r, dnd5e
 - Simple Calendar Configuration: default

**Browser (please complete the following information):**
 - OS: Windows, linux
 - Browser: edge
 - Browser Version: 101.0.1210.47

**Additional context**

**Comment by bnp800** [comment]
It seems a bug of `mega_chn`, not `simple calendar`

**Comment by vigoren** [comment]
Yeah it would seem to be a bug from that module, closing this issue.
