### ISSUE TITLE
[BUG]  time unit dropdown is illegible in "classic ui"

### ISSUE THREAD

**Issue by MarkPearce** [vigoren/foundryvtt-simple-calendar#325]
**Describe the bug**
time unit dropdown is illegible in "classic ui"

Black text on dark blue background lacks usable contrast. 

**To Reproduce**
1. Go to 'simple calender'
2. Click on 'day'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6976378/169550386-02940494-fffd-4e9a-a5d8-a3b15e5a6401.png)

**Foundry Information**
 - Foundry Version:9
 - Game System: pf2e
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
 - OS: mac/windows
 - Browser chrome

**Additional context**

**Comment by vigoren** [comment]
This will be fixed in the next release.
