### ISSUE TITLE
[BUG] Migration stuck, replays every launch of the world

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#329]
This modal dialog shows that the world is loaded every time, and the Clean Up Data button is not clickable. There are no notable errors in the console. 

![image](https://user-images.githubusercontent.com/4083812/169686766-3f0822c6-b081-445b-a3dc-c572ac521181.png)

Also I noticed that the notes now contain duplicates for each day, generated each time the migration attempted to create them. Now I need a way to wipe my V1 configuration and recreate my calendar as it keeps growing with each world start. 

There's also no way to remove the Default calendar, and that way I cannot even remove the old V1 calendar. I am stuck at a point where I should remove the mod altogether to avoid data swelling. 

![image](https://user-images.githubusercontent.com/4083812/169687839-ab192eb8-c789-4333-9087-924514ca9408.png)

**Comment by vigoren** [comment]
Sorry about this bug. I think I see what may have been happening and will have a fix released shortly for it. If you read this before I do the release and you are willing to send me your settings.db for this world I can do a more thorough test to make sure I catch what is happening. You can attach it to this issue or send it to me over discord (vigorator#8691), or over [email](mailto:vig@vig.vg).

The default calendar can't be removed as the module needs at least 1 calendar to function (it can be renamed).
The clean up data button is disabled unless the migration is considered finished (to prevent the removal of data if there was an issue) but in this case there was an issue preventing it from being considered finished.

Once the update is released I will also post the steps I would do to fix all the duplicate notes.

**Comment by vigoren** [comment]
I have released the update that should address this issue.

After installing the update following these steps should remove the duplicate notes.
- Make a backup of the world, just incase something happens.
- Load the world, this will trigger the migration dialog to appear again (this is expected). All steps should be green. Do NOT click the clean up data button.
- Open Simple Calendars configuration, go to global configuration settings and ensure the setting "Show Notes Folder" is checked.
- Refresh the page, the migration should NOT run again.
- Go to the Journal Entries section of the right side bar, you should see a folder there called `_simple_calendars_note_directory`, this is where all of the notes are now stored and there should be lots of them in there.
- Delete the directory, which will delete all of the notes.
- Run this command in the browsers console `SimpleCalendar.api.runMigration()`
- A dialog will appear asking you to confirm to run the migration again, click "Confirm".
- The migration will run again and you will see the migration dialog. All steps of the migration should be green.
- Check the Journal Entries section and the `_simple_calendars_note_directory` folder should be back with all of your notes in it.
- You can, this is 100% optional, click the "Clean Up Data" button. Which will go in and remove all of the old notes and configuration options of the settings.db file.
- If you want that folder hidden then open Simple Calendars configuration, go to global configuration settings and ensure the setting "Show Notes Folder" is unchecked.
- Reload the page, there should be no migration dialog, the notes folder should be hidden and there should only be one instance of your notes on the calendar.

I know that is a bit of mucking around but that should help resolve the issues.
Again sorry that you ran into them.

**Comment by vigoren** [comment]
Going to close this as I have not heard back if the issue is still persisting or not. If it is please re-open with more details, thanks!
