### ISSUE TITLE
[BUG] Note text is black on dark screen

### ISSUE THREAD

**Issue by ckdragons** [vigoren/foundryvtt-simple-calendar#334]
![image](https://user-images.githubusercontent.com/84493092/170811616-0a7062a7-cdf8-4e4c-bbb9-0b823c1da8b2.png)

**Describe the bug**
Using Firebox with a dark theme. The text when creating notes is black on a dark background. Hard to see.

**Comment by vigoren** [comment]
Which version of Simple Calendar are you using? When I test this with the latest version (2.0.13) with Windows and FireFox in dark mode the text is white.

**Comment by ckdragons** [comment]
SC 2.0.13
Foundry 9.269 on Forge
Firefox 100.0.2 (64-bit)
Using Dark theme in Firefox
Change theme in Firefox doesn't help, including Light and System Auto (refreshing window with F5 each time)
Even tried a new theme
![image](https://user-images.githubusercontent.com/84493092/170815125-9506009c-56a8-4fdb-b72b-dbf29661729c.png)

**Comment by vigoren** [comment]
It sounds like the style sheet for the editor isn't loading correctly. Are there any errors in the console or network tab showing an issue loading this file `/modules/foundryvtt-simple-calendar/styles/themes/tinymce-dark.css` ?

**Comment by ckdragons** [comment]
Yes
![image](https://user-images.githubusercontent.com/84493092/170848963-f3bdc049-284c-4ac2-874a-b95691655246.png)

**Comment by vigoren** [comment]
Ah ok I think I see what the bug is and it is specific to the forge. I will have a fix in the next release.

**Comment by vigoren** [comment]
The latest version should fix this, please let me know if it doesn't!
