### ISSUE TITLE
[BUG] Error Message for my players after activating/deactivating the pause

### ISSUE THREAD

**Issue by vt-tom** [vigoren/foundryvtt-simple-calendar#337]
**Describe the bug**
If i use simplecalendar and deactivate and then activate the pause (maybe and so on) then the players get an error message. 

**To Reproduce**
1. Log in as a player
2. activate/deactivate the pause as a gm
3. error message shows up as a player

**Error Message**
```
Simple Calendar  | Error "User Jan lacks permission to update Setting [zjj88tvoN2i8zuBw]"
Error: User Jan lacks permission to update Setting [zjj88tvoN2i8zuBw]
    at ServerDatabaseBackend._updateDocuments (file:///data/application/resources/app/dist/database/backend/server-backend.mjs:1:3039)
    at async Semaphore._try (file:///data/application/resources/app/common/utils/semaphore.mjs:99:17)
error @ index.js:1
Promise.catch (async)
changeDateTime @ index.js:1
interval @ index.js:1
setInterval (async)
start @ index.js:1
gamePaused @ index.js:1
_call @ foundry.js:294
callAll @ foundry.js:253
togglePause @ foundry.js:6170
(anonymous) @ foundry.js:6243
T.emit @ index.js:143
value @ socket.js:276
value @ socket.js:263
value @ socket.js:231
T.emit @ index.js:143
value @ manager.js:200
T.emit @ index.js:143
value @ index.js:105
value @ manager.js:192
T.emit @ index.js:143
value @ socket.js:323
T.emit @ index.js:143
value @ transport.js:99
value @ transport.js:92
ws.onmessage @ websocket.js:76
```

**Foundry Information**
 - Foundry Version: [9.269]
 - Game System: [DSA/TDE 3.4.2]
 - Simple Calendar Version: [eg 2.0.20]
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Comment by vigoren** [comment]
Are you also using the module Weather Control? I know there was an issue at one point with that module throwing that error for players when time changed.

I haven't been able to replicate it with just Simple Calendar installed.

**Comment by vt-tom** [comment]
No, I don't use weather control and I don't have it installed.
I will try to narrow it down a little bit better.

We had a RP Session Friday and I could get rid of the error in deactivating simple calendar. Then I wrote the ticket a little bit fast to remember there was a problem.

Next week I will dig further into this. Maybe it is an other module which is the problem.

**Comment by vigoren** [comment]
Ah ok it could be another module or something else going on.

What foundry permission level do the users have? (Player, trusted player etc)

Have you customized those permissions at all?

Is there any specific permissions set within simple calendar? (She to change time or as notes etc

I'll keep trying to see if I can replicate the issue on my end.

**Comment by vt-tom** [comment]
I analyzed it a bit further:
- only simple calendar active, without any other modules
- the player which occurs the errors is Trusted Player with the following permissions:
![grafik](https://user-images.githubusercontent.com/80099175/172215354-d73b9282-bc74-46ed-9c14-2a3b6e9063d5.png)

So it is not a problem with other modules, but with some permissions.

**Comment by vigoren** [comment]
Thanks I have been able to replicate the error now. I will have a fix for it in the next release!

**Comment by vigoren** [comment]
This has been fixed in the latest version!
