### ISSUE TITLE
[BUG] No Migration/Not working

### ISSUE THREAD

**Issue by 9ryex5** [vigoren/foundryvtt-simple-calendar#338]
I've been able to update this module by uninstalling the old one and installing the new one on my computer. But I haven't been able to do the same in the server. There was no migration screen for me and I don't have any settings.
![image](https://user-images.githubusercontent.com/43207603/171937667-ad24642f-f2bc-4479-b069-be2725573607.png)

I'm getting these errors when I click on "Simple Calendar Configuration" or the calendar icon.
![image](https://user-images.githubusercontent.com/43207603/171937866-d05c1d8f-3617-4afa-8865-e7dd925aa30b.png)

I tried to copy the "foundryvtt-simple-calendar" from my computer to the server with no difference.

**Comment by vigoren** [comment]
This looks like the new module did not install correctly. There should be more settings and it shouldn't fail to load that file (the error in the console).

If you copied it over you may need to restart your sever for the update the take effect.

Things to try, go to the Foundry setup screen (where you can install new modules/systems), go to the modules tab and find Simple Calendar and uninstall it. Then click the install button, find Simple Calendar and install it, then relaunch your world and try again.

Or if you want to copy the files over manually, copy the files over into the directory where all the other modules are (sounds like you tried this). Restart the foundry server. Launch your world and it should show up and work.

**Comment by 9ryex5** [comment]
I did reinstall the module before copying the files manually with no avail, but I'll probably need to restart the server to fix it.
