### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by rmasoni** [vigoren/foundryvtt-simple-calendar#340]
Since the last major update I can't open Simple Calendar's settings window anymore. Nothing happens when I click the button with the gear icon. Tested with all modules disabled and nothing changed.

**Comment by vigoren** [comment]
Are there other settings for the Module or just the Configuration button?
Which system? (Shouldn't matter but maybe)
Which version of foundry?

Are there any errors in the browsers console when you click the button?

I just did a quick test in the latest version and it opened correctly for me so wondering what the differences are.

**Comment by rmasoni** [comment]
I don't understand what you meant with the first question.

Just checked and there are these two errors:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/62244/172135256-fe9d2360-b697-4b66-9aa2-77270e00ead7.png">

Foundry Virtual Tabletop Version 9 Build 269
DnD5e Fifth Edition System 1.6.2

**Comment by rmasoni** [comment]
Good news: the module fixed itself after I uninstalled and installed it again.
