### ISSUE TITLE
[FEATURE] Add a quick "Show to players" and "Make visible to players" buttons

### ISSUE THREAD

**Issue by XpPlayer845** [vigoren/foundryvtt-simple-calendar#341]
**Is your feature request related to a problem? Please describe.**
In order to make a note visible to players the GM currently has to:
- Select the day the note was created for
- Open the Notes-of-the-day list (if not already opened)
1) Open the note (from the Notes-of-the-day list)
2) Click on the edit button
3) Select every single player it should be visible to
4) Click the save button
5) Close the note

**Describe the solution you'd like**
Directly inside the Notes of the Notes-of-the-day list:
- Add a button (for the GM) that toggles the visibility for all players (globally, so you don't have to go back and re-do every note if you add a new player later in the game)
- Add a button that opens a player-selection dialog (that also includes the global-visibility option)
- Change the Tool-tip of the "Player Visible" tag to show which players it is visible for
- (Maybe) Add a button that lets the GM display a note for the players (open the note on player-screen, same as the [Show Notes](https://github.com/shawndibble/foundryvtt-show-notes) module)
- [EDIT] Add a quick delete button (still asking for confirmation)

This would greatly reduce the work needed to show a note to the players.
[EDIT] Alternatively a right-click context menu instead of the buttons would also do the trick

**Describe alternatives you've considered**
When enabling the "Show Notes Folder" option the GM can edit the viewing rights of all the notes, but it doesn't change the visibility in the calendar itself. It would enable bulk-editing of view-rights but I think a quickly accessible global setting would be best.
Maybe in the future you can add a window that contains a list where the GM can see/access/edit all notes of a calendar nicely, but I think the solution I proposed would help lowering the in-game work for the GM more.

**Comment by vigoren** [comment]
Version 2.1.27 should cover most of these items.

- There is a new option when selecting which players can see a note called All Players that will make the note visible to all current and future players.
- The player visible icon is different depending on if all players, some players or just the GM can see the note. The tool tip will also list the players that can see it.
- Added a right click menu with several options
  - Remind Me / Don't Remind Me to toggle if you want to be reminded (everyone can see)
  - Show Players, will allow you to show the note to the selected players (GM only)
  - Edit to open the note up in edit mode (GM or note author)
  - Delete brings up the confirmation dialog to delete the note (GM or note author)


The first option in combination with the edit link should cover your first two points better than they currently are.

Let me know what you think!
