### ISSUE TITLE
[BUG] Clicking on Show Notes Folder (anywhere except the checkbox) toggles Sync Date

### ISSUE THREAD

**Issue by SalieriC** [vigoren/foundryvtt-simple-calendar#342]
**Describe the bug**
Clicking on the highlighted area for "Show Notes Folder" in the config does not toggle its checkbox but the checkbox for "Sync Date..." instead.

**Comment by vigoren** [comment]
Oh oops that is an easy fix too. Thanks for reporting it! I will have this fixed in the next release.

**Comment by vigoren** [comment]
This has been fixed in the latest version!
