### ISSUE TITLE
[BUG] JS error prevents calendar Nav Arrows from working

### ISSUE THREAD

**Issue by Terrox** [vigoren/foundryvtt-simple-calendar#345]
**Describe the bug**
clicking left/right does nothing.
spinning loader dots
unknown why at this stage.

I get this error on click settings.
| Error "a.months[e.month].days[e.day] is undefined"

**To Reproduce**
Import Forgotten Realms calendar
???

**Expected behavior**

**Screenshots**

**Foundry Information**
TBA

**Browser (please complete the following information):**
 Firefox

**Additional context**
`Simple Calendar  | Error "a.months[e.month].days[e.day] is undefined"
DD@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:13014
q/t<@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:14506
q@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:14488
U@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:15230
build@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:68830
DateSelector@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:150262
c@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:19853
anonymous@http://foundry.anisms.com:30000/scripts/handlebars.min.js line 29 > Function:71:165
h@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:17870
c@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:6899
b.default/<@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:7289
c@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:19853
anonymous@http://foundry.anisms.com:30000/scripts/handlebars.min.js line 29 > Function:679:49
h@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:17870
b.default/<@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:10117
c@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:19853
anonymous@http://foundry.anisms.com:30000/scripts/handlebars.min.js line 29 > Function:63:47
c@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:15429
d@http://foundry.anisms.com:30000/scripts/handlebars.min.js:27:15744
e@http://foundry.anisms.com:30000/scripts/handlebars.min.js:28:22748
renderTemplate@http://foundry.anisms.com:30000/scripts/foundry.js:4696:10
async*_renderInner@http://foundry.anisms.com:30000/scripts/foundry.js:3235:22
_renderInner@http://foundry.anisms.com:30000/scripts/foundry.js:3775:30
_render@http://foundry.anisms.com:30000/scripts/foundry.js:3068:30
async*_render@http://foundry.anisms.com:30000/scripts/foundry.js:3764:17
render@http://foundry.anisms.com:30000/scripts/foundry.js:3021:10
render@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:77982
showApp@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:79236
initializeAndShowDialog@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:78855
async*configurationClick@http://foundry.anisms.com:30000/modules/foundryvtt-simple-calendar/index.js:1:129382`
![image](https://user-images.githubusercontent.com/16533005/174225710-5652af22-85ec-4bbb-92af-09a3dab0b17c.png)

**Comment by vigoren** [comment]
Hey I am unable to replicate this by loading the included Forgotten Realms calendar. I can see from the screen shot that other aspects of the configuration were changed (The words "Deepwinter" in brackets after the month name are not included in the  predefined calendar for the Forgotten Realms and the names of the weekdays are not shown by default).

I would check the months to see if any have weird values for the months to make sure nothing odd is going on there. 

Additionally if you want to open the configuration dialog, go to import/export and export this calendar and attach the generated file to this issue I can take a look and see what is going on specifically.

**Comment by Terrox** [comment]
thanks, could be that I edited some names assuming that would work. I'll redo the import and see what happens.

**Comment by Terrox** [comment]
I reimported Forgotten Realms and it still happened. Then disabled About Time since there was a JS error related to it but that didn't fix it.
These are the only two errors I get on load.
`TypeError: token.actor is null
[Detected 2 packages: ATL, lib-wrapper]
    ready activeLighting.js:137
    _call foundry.js:294
    callAll foundry.js:253
    setupGame foundry.js:5567
    _initializeGameView foundry.js:6514
    _initializeView foundry.js:6490
    initialize foundry.js:5431
    call_wrapped libWrapper-wrapper.js:511
    libWrapperInit libWrapper-api.js:791
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:62701
    async* foundry.js:62683
[foundry.js:319:30](http://foundry.anisms.com:30000/scripts/foundry.js)
Uncaught (in promise) TypeError: s is undefined
[Detected 2 packages: foundryvtt-simple-calendar, lib-wrapper]
    loadNotes index.js:1
    initialize index.js:1
    async* index.js:1
    _call foundry.js:294
    callAll foundry.js:253
    setupGame foundry.js:5567
    _initializeGameView foundry.js:6514
    _initializeView foundry.js:6490
    initialize foundry.js:5431
    call_wrapped libWrapper-wrapper.js:511
    libWrapperInit libWrapper-api.js:791
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:62701
    async* foundry.js:62683`

**Comment by Terrox** [comment]
I also disabled all modules except Find the Culprit and Simple Calendar and it still happens, unless I just don't know how to advance days?

**Comment by vigoren** [comment]
you shouldn't see any errors from simple calendar,
the first error doesn't have anything to do with simple calendar.

The second error though is puzzling me. So I will need some more details. There is something going on when the notes are trying to be loaded that isn't working as expected.

- What version of foundry are you running?
- Which system is this in?
- Did you add notes to the calendar?
- If you enable the setting [Show Notes Folder](https://simplecalendar.info/pages/docs/global-configuration/settings.html#global-configuration), reload the page and look in the journal tab there should be a folder called "_simple_calendar_notes_directory". 
  - Did you add a journal entry to this folder through Foundry and note as a note through Simple Calendar?
  - If you delete that folder (and all the notes in it) does the error still appear? (If the folder is full of custom notes making a backup first would be a good idea)

**Comment by Terrox** [comment]
thanks, it was the notes folder which had duplicate folders(?) of most of the months and holidays and one(maybe more?) custom user note. I'm not sure how the folders got in there. But when I did Remove All and reloaded it was all working again.

It was all latest versions as of yesterday, 5e system.

**Comment by vigoren** [comment]
hmm that is strange, Simple Calendar doesn't add folders under that folder. but this does tell me the bug has to do with nested folders so I will have do do a fix for that. Thanks for the details!
