### ISSUE TITLE
Combat on Non-Active Scene desynced

### ISSUE THREAD

**Issue by poisoneddm** [vigoren/foundryvtt-simple-calendar#346]
Hi,

When I run combat that is not on the active scene (because a player is off adventuring in a seperate area or because I've linked two maps via Multilevel) regardless of whether the combat is linked or unlinked to a scene the calendar continues to run and does not pause combat like it does on active scenes. 

I.E Pauses time (but not the game) and goes up in 6s increments at the end of a round. 

I've replicated this on two PF2e worlds and both with only Simple Calendar running

**Comment by vigoren** [comment]
I have added a new setting that should help with what you have described above.

The "Pause Real Time Clock on Combat Rule" whos details can be found in the [release notes](https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v2.0.30) or in the [documentation](https://simplecalendar.info/pages/docs/global-configuration/settings.html).
