### ISSUE TITLE
[BUG]  Simple Calendar Not Starting or Working

### ISSUE THREAD

**Issue by senicluxus** [vigoren/foundryvtt-simple-calendar#348]
**Describe the bug**
Simple Calendar will show up in the menu and have all the options and menu's available, but it is stuck at the current day I have it set to when it stopped working. I cannot move time forward in any way whatsoever. It has a buffering icon in the bottom left and in the console I see this error:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'calendarId')
[Detected 1 package: foundryvtt-simple-calendar]
    at Et.loadNotes (modules/foundryvtt-simple-calendar/index.js:1)
    at Et.initialize (modules/foundryvtt-simple-calendar/index.js:1)
    at async modules/foundryvtt-simple-calendar/index.js:1`

**To Reproduce**
1. Launch World
2. Press F12
3. Error appears and module is non-functional

**Expected behavior**
I should be able to move time forward and backward and set the date.

**Foundry Information**
 - Foundry Version: 9.269
 - Game System: DnD5e
 - Simple Calendar Version: 2.0.25

**Browser (please complete the following information):**
 - Firefox

**Comment by vigoren** [comment]
Are you still able to open the configuration for Simple Calendar?

If so I would look at following the 4th bullet in this [post](https://github.com/vigoren/foundryvtt-simple-calendar/issues/345#issuecomment-1158697068) as i think these 2 issues are related and I have been working on a fix for it.

**Comment by senicluxus** [comment]
Oh my goodness that fixed it! I didn't even think to check the notes folder.

Yes that was the issue. I had a single note in there by mistake I must of dragged it in, deleting it and refreshing fixed the issue. Thank you so so much!
