### ISSUE TITLE
[FEATURE] Don't close window when hitting Esc

### ISSUE THREAD

**Issue by GambetTV** [vigoren/foundryvtt-simple-calendar#352]
Because of the dumb way Foundry is configured, if I have a bunch of character sheets, item sheets, journal entries, and scene settings windows open, I can hit Esc once and it closes all of these windows. Unfortunately, it also closes the Simple Calendar window, which I'd prefer to have permanently up unless I deliberately close it. It'd be nice if you could make it resist closing when hitting escape, unless maybe it's the dominant window.

**Comment by vigoren** [comment]
I looked into this and it's not something I can easily detect. Hitting escape is the same as clicking the close button and programmatically I can't tell tell if it was clicked on our if escape was hit. So I can't really implement this functionality.
