### ISSUE TITLE
Changing the date on imported notes [FEATURE] 

### ISSUE THREAD

**Issue by Morters** [vigoren/foundryvtt-simple-calendar#353]
I have exported some of the calendar data from an old campaign and I need to change the date to about 1000 years in the past. 
It is impossible to change the date with this prompt:
![image](https://user-images.githubusercontent.com/11695935/183134144-936aa955-a2fb-4cb2-a7e8-555eb341e7d6.png)

as I need to scroll thousands of pages for each note.. I was wondering if there is or will be an option to change the date of a not without the need to scroll the date all the way. 

Thank you

**Comment by vigoren** [comment]
I have updated the date/time selector for notes so that the year on the calendar is a text box where you can change the year by typing it in rather than filtering through all the months to change the year. This was added in version 2.1.0 of Simple Calendar.
