### ISSUE TITLE
[BUG] Similar to #313 UI is messed up settings also don't open

### ISSUE THREAD

**Issue by DieDae** [vigoren/foundryvtt-simple-calendar#354]
**Describe the bug**
Updated to the latest version and the UI is broken and settings won't open.

Odd thing is the old UI is still showing up and everything is functioning fine serverside it's clientside that is broken.

Things I've done:

Uninstall/reinstall simple calendar.
Delete the simple calendar folder from the server and unpack the .zip manually
stop/restart the server between attempts

**Expected behavior**
Everything to be hunky dory.

**Screenshots**
![chrome_2022-08-14_01-59-26](https://user-images.githubusercontent.com/1352860/184526141-05790d5c-a4d3-472d-8abe-c1ee53379e7b.png)
![2022-08-14_01-57-45](https://user-images.githubusercontent.com/1352860/184526142-22e765cc-2c0d-43c0-890d-b2869a534420.png)
![mstsc_2022-08-14_02-03-30](https://user-images.githubusercontent.com/1352860/184526258-14171831-600a-4d3a-8f87-1b342a0a1238.png)

**Foundry Information**
 - Foundry Version: 9.296
 - Game System: DnD5e
 - Simple Calendar Version: 2.0.30
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
 - Browser: chrome 104.0.5112.81 
 - Just tried in edge 104.0.1293.54 and old UI shows up and functions fine 
 - Firefox is affected as well

**Additional context**
The only errors that come up are in the screenshot when I try to open settings from the foundry configure settings menu

**Comment by vigoren** [comment]
This is an odd issue, I can't think of any reason why it would fail to load properly.

It almost seems like a caching issue but you did restart the foundry server and tried different browsers so that should have taken care of any lingering caches.

Have you tried with just Simple Calendar enabled? Just to quickly rule out other modules.

Also have you tried a different world? Maybe the issue is localized to a specific world for some reason?

**Comment by DieDae** [comment]
Figured it out after having slept on it. All of my website traffic is routed through cloudflare so it was trying to use the cached stuff which is why it worked serverside and why visits from a new browser worked but re-visiting was affected.
