### ISSUE TITLE
[FEATURE] Close button for mini-SC

### ISSUE THREAD

**Issue by weepingminotaur** [vigoren/foundryvtt-simple-calendar#356]
Currently, when SC is in its mini-mode, you can't close it from that window. You have to double-click the title bar to bring up the full window, then click Close. This is inconvenient for those of us who use the mini window most of the time. Adding a quick button (red x?) to the mini-window would save a ton of clicks.

**Comment by vigoren** [comment]
This has been added to the compact view in version 2.1.0 of Simple Calendar. Thanks for requesting it!
