### ISSUE TITLE
[FEATURE] Move scene control button to the 'Journal Notes' tab

### ISSUE THREAD

**Issue by Avera9eJoe** [vigoren/foundryvtt-simple-calendar#357]
**Is your feature request related to a problem? Please describe.**
The Simple Calendar button currently sits in the "Token Controls" tab in the Scene control bar which seems rather strange to me as it does not change things with tokens, and is the only button in that menu which does not. Lowering the number of buttons on that menu would be beneficial for both myself and my players.

**Describe the solution you'd like**
Either a menu picker in settings to let the DM choose which menu the scene button rests in, or change it's default location to the Journal Notes tab.

**Describe alternatives you've considered**
Sadly there aren't any solutions to this issue I can think of, as there doesn't appear to be any options for this in settings.

**Comment by vigoren** [comment]
This has been updated in version 2.1.0 of Simple Calendar.

**Comment by Avera9eJoe** [comment]
Awesome!! Thank you so much!
