### ISSUE TITLE
[BUG] Holidays/events show up in Configure Scene Journal Entry box

### ISSUE THREAD

**Issue by Avera9eJoe** [vigoren/foundryvtt-simple-calendar#358]
**Describe the bug**
The generated calendar events from Simple Calendar appear inside of Configure Scene, when trying to link journal entries to scenes for DM notes. These events do not appear inside of Journal Entries, so they are inaccessible, and do nothing if linked to a scene; they are a problem to sort through when trying to link notes

**To Reproduce**
1. Use Eberron calendar configuration
2. Create a new scene
3. Open Scene Configuration --> Ambience --> Journal Entry
4. Observe the presence of all generated events, which can be selected, but do nothing

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5304201/186093150-430fb6fa-00d6-465c-90a3-f6f2f517ca7f.png)

**Foundry Information**
 - Foundry Version: v9
 - Game System: DnD5e
 - Simple Calendar Version: 2.0.30
 - Simple Calendar Configuration: Eberron

**Browser:**
 - Desktop Application

**Comment by vigoren** [comment]
The notes in Simple Calendar are journal entries. If you go to the configuration for Simple Calendar and check the setting "Show Notes Folder" under the global configuration section.

Then refresh the page and a folder under the journal entries tab will show that contains all of the notes in Simple Calendar.

If I set one of the calendar notes to the journal entries setting for a scene, then right click on the scene and select view journal entry the note does open.

So it appears to work from my testing as it is intended, though I can appreciate not wanting to see those notes as a selectable option.

I can look into hiding them from that drop down of the show notes folder is unchecked.

**Comment by Avera9eJoe** [comment]
> I can look into hiding them from that drop down of the show notes folder is unchecked.

That sounds like a perfect solution! That way it can be used in both ways

**Comment by vigoren** [comment]
This has been fixed in version 2.1.0 of Simple Calendar. Thanks for reporting it!
