### ISSUE TITLE
[BUG] Note Title is not changeable

### ISSUE THREAD

**Issue by Muwak77** [vigoren/foundryvtt-simple-calendar#362]
**Describe the bug**
The title of Calandar-Notes cannot be changed

**To Reproduce**

- add a new note
- rename the note
- when exiting the title-field, its value reverts to the previous state

**Expected behavior**
The title should change

**Foundry Information**
 - Foundry Version: 10.284
 - Game System: probably any, testet with DTE, Cthulhu 7 and investigator
 - Simple Calendar Version: 2.1.0
 - Simple Calendar Configuration: as it comes out of the box

**Browser (please complete the following information):**
Chrome

**Comment by vigoren** [comment]
Ah man this wasn't broken when I released looks like something may have changed in one of the last couple updates. I will fix it later today and do a release.

**Comment by Muwak77** [comment]
> Ah man this wasn't broken when I released looks like something may have changed in one of the last couple updates to Foundry. I will fix it later today and do a release.

Great, I really appreciate your work, SC is one of the very few modules I didn't want to do without :)

**Comment by vigoren** [comment]
This is fixed in version 2.1.4
