### ISSUE TITLE
[FEATURE] Function to open up the calendar

### ISSUE THREAD

**Issue by winterwulf** [vigoren/foundryvtt-simple-calendar#37]
Would it be possible to give a fuction to open the calendar window?
So we could create a macro button to open it, and use as a button in a secene or in a journal.

**Comment by vigoren** [comment]
This can be done for sure, good idea.

**Comment by vigoren** [comment]
This has been added in version 1.1.6.

For instructions on how to set these up see the release notes or the [Macro section of the readme](https://github.com/vigoren/foundryvtt-simple-calendar#macros).

**Comment by winterwulf** [comment]
you're awesome!!
