### ISSUE TITLE
[BUG] Migration from v1 to v2 stuck.

### ISSUE THREAD

**Issue by asdmaster104** [vigoren/foundryvtt-simple-calendar#372]
**Describe the bug**
Recently updated to v10 build 284 of foundry, and to v2.1.4 of Simple Calendar. When I opened the game the migration window popped up, but it is indefinitely stuck on the spinning yellow circle. Console shows an error:

 "Uncaught (in promise) Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[Detected 1 package: foundryvtt-simple-calendar]"

**To Reproduce**
Unsure? I assume this works as intended for other users as I have not seen anyone else mention this particular issue.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/113069421/188994518-4cab3a3d-a28e-42cc-826f-3258f8332639.png)

**Foundry Information**
 - Foundry Version: 10
 - Game System: DnD5e 2.0.2
 - Simple Calendar Version: 2.1.4
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
 - Browser: Chrome

**Additional context**

**Comment by vigoren** [comment]
Sorry you ran into this issue. I think I know what the problem is and will try to get an update out to fix it tomorrow.

Once the update is out you should just have to open the game and the migration should start again.

**Comment by asdmaster104** [comment]
Awesome, thanks for the quick reply!

**Comment by vigoren** [comment]
Version 2.1.10 should fix this issue. If it doesn't please let me know!

**Comment by asdmaster104** [comment]
It is indeed fixed and working as intended. Thanks!
