### ISSUE TITLE
[BUG] Calendar showing all months instead of one

### ISSUE THREAD

**Issue by Ikabodo** [vigoren/foundryvtt-simple-calendar#378]
**Describe the bug**
The non-compact view shows all year in one view. Making it impossible to reach some part of the months.

**To Reproduce**
Open Calendar in non-compact view.

**Expected behavior**
![image](https://user-images.githubusercontent.com/7766890/190595236-094c9276-ed3b-4128-9b0a-a55778823e2e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/7766890/190595314-10d3acc9-1252-49ed-9d52-8cafa862586c.png)

**Foundry Information**
 - Foundry Version: 10.286
 - Game System: DnD5e 2.0.2
 - Simple Calendar Version: 2.1.18
 - Simple Calendar Configuration: Default, I think?

**Browser (please complete the following information):**
 - Browser Chrome

**Comment by vigoren** [comment]
this is fixed in 2.1.19.. I had accidentally left an experimental year view on.

my bad and sorry about that.

**Comment by Ikabodo** [comment]
No worries mate.
Thanks for the quick fix!

Also, the new view look great, might need some tweaking though. But that is what experimental means!
