### ISSUE TITLE
[BUG] When using the warhammer theme, short notes are too small for the text

### ISSUE THREAD

**Issue by TheFirst05** [vigoren/foundryvtt-simple-calendar#385]
**Describe the bug**
The text of short notes is hard to read when using the warhammer fantasy theme.

![image](https://user-images.githubusercontent.com/96636889/193353738-ea880aaf-8fc6-43b4-9c80-a951447b563f.png)

**To Reproduce**
1. Use the Warhammer theme.
3. Create a new note and write a short phrase.
4. Save and close the editor.
5. Open the note to read it (via the calendar).
6. See error

**Foundry Information**
 - Foundry Version: [v10]
 - Game System: [Warhammer fantasy 4e]
 - Simple Calendar Version: [eg 2.1.27]
 - Simple Calendar Configuration: Warhammer fantasy theme

**Browser (please complete the following information):**
 - Foundry.

Thanks for this mod. We use it a lot :)

**Comment by vigoren** [comment]
This issue should be fixed in version 2.1.40 of Simple Calendar
