### ISSUE TITLE
Version 10 Support

### ISSUE THREAD

**Issue by bluefroguk1** [vigoren/foundryvtt-simple-calendar#386]
When running FVTT V10 with Simple Calendar Installed, i get the following compatibility errors:

- setup.js:145 [foundryvtt-simple-calendar] The module "foundryvtt-simple-calendar" contains "dependencies" which is deprecated in favor of "relationships.requires"
- setup.js:145 [foundryvtt-simple-calendar] module "foundryvtt-simple-calendar" contains "system" which is deprecated in favor of "relationships.systems"
- setup.js:145 [foundryvtt-simple-calendar] The module "foundryvtt-simple-calendar" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by vigoren** [comment]
I feel like you are not on the latest version of simple calendar.

The version should be 2.1.27

If you are on 1.3.75 you will have to uninstall and reinstall the module. Uninstalling a module doesn't delete any data so it's safe to do that.

**Comment by bluefroguk1** [comment]
That sorted it  - thanks :)
