### ISSUE TITLE
Question : addNote capability

### ISSUE THREAD

**Issue by Kekilla0** [vigoren/foundryvtt-simple-calendar#388]
Can you force addNote to set to auto "Remind me"

**Comment by vigoren** [comment]
There currently isn't an option to do this through that function. I will add one for the next release.

**Comment by vigoren** [comment]
The addNote function has been updated so that the remind me can be set for a passed in list of user IDs. Check out the update documentation for more! https://simplecalendar.info/functions/SimpleCalendar.api.addNote.html
