### ISSUE TITLE
[FEATURE] Option to show the calendar date in the chat messages

### ISSUE THREAD

**Issue by Kaitiou** [vigoren/foundryvtt-simple-calendar#390]
It would be nice a option that lets chat to show a timestamp in messages, showing the calendar date of when they were written.

(Similar to what the "Chat Message Timestamp" module does, but, in this case, showing the in-game date instead the actual date in the real world).

This would be useful to check and remember when something was said, how long ago it happened, etc.

Thanks!

**Comment by vigoren** [comment]
There is another module that does this already of you have simple calendar installed. I would check it out to see if that works for you!
https://foundryvtt.com/packages/df-chat-enhance

**Comment by Kaitiou** [comment]
It works perfectly, thank you so much! Sadly, it seems that I have to choose between showing the real time or in-game time, but it can be solved with the other module I quoted before (Chat Message Timestamp). Having both, I've got to show the both times. Thank you again!
