### ISSUE TITLE
[BUG] Simple Calendar no longer will allow settings to be saved or calendar modified in latest v10 update

### ISSUE THREAD

**Issue by DaringMarble** [vigoren/foundryvtt-simple-calendar#392]
Modifications to calendar settings no longer can be saved. Clicking the 'save' button does nothing. The import function is also broken; it gives an error message that a properly exported json file is not a Simple Calendar json. 

I tried this in a new world with no mods using the PF2e system and the issue continued. I'm on the most recent v10 build of Foundry as of posting, v10 build 288.

**Comment by vigoren** [comment]
Which version of simple calendar are you running?

I don't think you are on the latest version of simple calendar.

The version should be 2.1.27

If you are on 1.3.75 you will have to uninstall and reinstall the module. Uninstalling a module doesn't delete any data so it's safe to do that.
