### ISSUE TITLE
[FEATURE] Make it possible to globally disable the calendar opening on login

### ISSUE THREAD

**Issue by nschoenwald** [vigoren/foundryvtt-simple-calendar#394]
**Is your feature request related to a problem? Please describe.**
I don't want the calendar to open for any of my players on login. I want to be able to disable this globally as a gm.

**Comment by vigoren** [comment]
That setting is a client setting and is designed to let each player determine if they want the calendar to open on login or not.

If you don't want players to do that you can ask them to update their settings. Or use a module like [Monks Player Settings] (https://foundryvtt.com/packages/monks-player-settings) that allows you to set each players client settings.

Hope that helps!
