### ISSUE TITLE
[BUG] DSA/TDE Sheet - Background transparent 

### ISSUE THREAD

**Issue by vt-tom** [vigoren/foundryvtt-simple-calendar#398]
**Describe the bug**
First: thank you for the new DSA/TDE5 Simple calendar Sheet. 

I really like it, but i have one little Problem with it. The Background ist transparent, as you can see in the Screenshot.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/197453162-3d754a21-c6e2-4a2c-ab36-17248bf868f4.png)
![grafik](https://user-images.githubusercontent.com/80099175/197453274-f9f77cdd-3500-4d75-98ec-440a97c3165e.png)

**Foundry Information**
 - Foundry Version: [e.g. 0.8.4] 10.288
 - Game System: [e.g. DnD5e] DSA/TDE5 4.1.10
 - Simple Calendar Version: [eg 2.0.4] 2.1.40

**Comment by vigoren** [comment]
That's strange. It looks like it is failing to load the background image properly.

If you refresh the page and open simple calendar are there any errors in the browser console (f12 on Windows)?

A couple of other questions:

- Are you hosting foundry yourself or using a service like the forge?
- do you use S3 buckets to store assets and things?

That should help me narrow down what's going on here.

Sorry it's not working as expected.

**Comment by vt-tom** [comment]
I have tested it on moltenhosting and in a local installation. So no difference between themn.
But i found an error in the console: 
![grafik](https://user-images.githubusercontent.com/80099175/197455931-6f5e6b5e-5d78-4a19-bb4d-fa7da64c7dd4.png)

**Comment by vigoren** [comment]
Thanks for the information.

The issue is not finding the journal background image. I will check which version of DSA5 I built this with versus the version you are using. The image might have been moved or renamed.

**Comment by vt-tom** [comment]
That might be the case. Maybe for all DSA 4.X Versions because the Journals changed?

**Comment by vt-tom** [comment]
Hmm, i dont know what the problem is, but the image is still unter systems/dsa5/icons/backgrounds in v4.X.

![grafik](https://user-images.githubusercontent.com/80099175/197460911-587b8106-2737-4fda-bea5-633ef4dcd501.png)

**Comment by vigoren** [comment]
I found the issue on my side and will have a fix for it out in a day or two hopefully.

Again sorry about this.

**Comment by vigoren** [comment]
version 2.1.50 of SC should fix this issue!
