### ISSUE TITLE
[FEATURE] Chat timestamp

### ISSUE THREAD

**Issue by asherett** [vigoren/foundryvtt-simple-calendar#404]
**Describe the solution you'd like**
I'd love to have the option to get timestamps on chat messages with "ingame time" fetched from SC. I'm thinking here about the (e.g.) "13h ago" timestamp in default.
![image](https://user-images.githubusercontent.com/76103282/199187195-1347bc50-3c0f-4950-8d67-da6143ae954c.png)

**Describe alternatives you've considered**
I'd want the default "x hours/days ago" timestamp to (optionally) reference SC time instead of user time.
Ideally there would also be an option to change between "x time ago" type timestamp and "<time> <date>" timestamp (i.e. a string of clock, date).
Another "ideal" option would be to display both ingame time and RL time in the timestamp.

**Additional context**
This feature was originally inspired by the module ["chat-timestamp" by jsavko](https://github.com/jsavko/chat-timestamp). But when playing, it would be extremely handy to see when a certain spell was cast in "_ingame time_" instead of "_real life time_", for spells and abilities that have duration measured in hours, days etc. Therefore I'd love to see a chat timestamp option getting info from SC.

**Comment by gsterling** [comment]
I would like this, too.

**Comment by vigoren** [comment]
This has been added in version 2.3.0 of Simple Calendar. It can be turned on using the [Use Game Time For Chat Messages](https://simplecalendar.info/docs/global-configuration/settings#use-game-time-for-chat-message-timestamps) setting under the global configuration.

How the date is displayed can be customized with the new [Chat Message Timestamp Format](https://simplecalendar.info/docs/calendar-configuration/display-options#datetime-formatting) setting under the Display Options.

Important to note that these changes will only apply to messages sent after this update has been installed.
