### ISSUE TITLE
[BUG] Error when changing calendar preset

### ISSUE THREAD

**Issue by mortiferus93** [vigoren/foundryvtt-simple-calendar#409]
![image](https://user-images.githubusercontent.com/62659858/201406478-6992c1b2-3908-4059-b577-3c0fd457fc21.png)

**Comment by vigoren** [comment]
This error happens on Foundry version 10 and when on a very old version of Simple Calendar.

Which version of simple calendar are you running?

The version should be 2.1.58

If you are on 1.3.75 you will have to uninstall and reinstall the module. Uninstalling a module doesn't delete any data so it's safe to do that.

**Comment by mortiferus93** [comment]
Thanks! Manually removing and reinstalling solved it!
