### ISSUE TITLE
[QUESTION] Check if Calendar is already open before `showCalendar();`

### ISSUE THREAD

**Issue by mouse0270** [vigoren/foundryvtt-simple-calendar#410]
What is the best way to check and see if the calendar window is already open before calling `SimpleCalendar.api.showCalendar();` It appears that this currently causes the calendar to register all its render hooks with some modules don't play nicely with. I'd like to check and see if the calendar is already open before calling this function and just curious the best way to handle that.

**Comment by vigoren** [comment]
I don't have anything in the API to check if the Simple Calendar application is open or not.

For a quick check you could do something like this
```function isSCOpen(){return !!Array.from(document.querySelectorAll('div[id^="fsc-"].simple-calendar')).filter(e => {return !e.querySelector('.window-resizable-handle')}).length;}```

Then it is a simple function call to ```isScOpen()``` and that will return a Boolean of if the dialog is open or not.

**Comment by vigoren** [comment]
In version 2.1.73 I have added the API function `SimpleCalendar.api.isOpen()` that will return if the calendar is open or not.
