### ISSUE TITLE
[FEATURE] please have an option to turn off the small timer

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [vigoren/foundryvtt-simple-calendar#415]
**Is your feature request related to a problem? Please describe.**
im always frustrated by the smaller calendar because i play pf2 and we dont need the timer. but do like the calendar organisation. i cant turn off the timer in the menu settings or if i can i cant see the setting.

**Describe the solution you'd like**
a clear button in the settings to turn off the timer 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/62528192/203359674-9567493e-e6fb-47b8-ae7a-0b7cc3933630.png)
by timer i mean this.

**Comment by vigoren** [comment]
That isn't part of simple calendar. That clock display comes from a module called weather control.
