### ISSUE TITLE
Compatibility Issue after Update [BUG] 

### ISSUE THREAD

**Issue by YorinLuz** [vigoren/foundryvtt-simple-calendar#416]
Hello,

I get the following compatibility warning when opening Foundry:

![image](https://user-images.githubusercontent.com/95984260/203409306-987e1660-f7b1-45c8-ac0d-607c177b74fe.png)

Was this already changed and it's only a me-problem or does this still have to be changed?

Thank you!

**Comment by vigoren** [comment]
Which version of Simple Calendar do you have installed?

I feel like this is an older version (1.3.75 is my guess). The latest version is 2.1.58, if you have an old version installed please uninstall and reinstall the module (no data is lost when a module is uninstalled). That should resolve the issue

**Comment by YorinLuz** [comment]
Yes, that worked. Thank you!
