### ISSUE TITLE
[BUG] Compatibility Warnings

### ISSUE THREAD

**Issue by KoodGarma** [vigoren/foundryvtt-simple-calendar#417]
**Describe the bug**

I recently updated FVVT from v9 to v10 b290 | 5e v2.0.3 and am getting three compatibility warnings, see below screenshots, in the F12 console log.

**To Reproduce**
1. Launch FVVT
2. Update all Modules
3. F12 console log

**Expected behavior**
No compatibility warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/65504428/204682697-e48425b3-57c2-4b35-b739-c835d356a9c8.png)
![image](https://user-images.githubusercontent.com/65504428/204682463-6eeadcf9-e3cb-461e-b1a4-41c36b50e383.png)

**Foundry Information**
 - Foundry Version: v10 b290
 - Game System: 5e v2.0.3
 - Simple Calendar Version: v1.3.75
 - Simple Calendar Configuration: N/A

**Browser (please complete the following information):**
 - Browser: The warning and log are in the FVVT app.

**Additional context**
N/A

**Comment by vigoren** [comment]
You are on an older version of simple calendar. The latest version is 2.1.58. please uninstall and reinstall the module (no data is lost when a module is uninstalled). That should resolve the issue

**Comment by KoodGarma** [comment]
That worked thanks!
