### ISSUE TITLE
[BUG] Can't edit Note/Details

### ISSUE THREAD

**Issue by Zeokhanash** [vigoren/foundryvtt-simple-calendar#423]
**Describe the bug**
No edit available to change the text in the Details part of Note into simple calendar

**To Reproduce**
1. Go to 'Simple Calendar'
2. Click on 'Add new note'
3. See error in Details section

**Expected behavior**
Used to have a button to edit text.

**Screenshots**

**Foundry Information**
 - Foundry Version: 10.291
 - Game System: DnD5e 2.0.3
 - Simple Calendar Version: 1.3.75

**Browser (please complete the following information):**
 - Browser chrome

**Additional context**

**Comment by vigoren** [comment]
You are on an older version of simple calendar. The latest version is 2.1.60. please uninstall and reinstall the module (no data is lost when a module is uninstalled). That should resolve the issue

**Comment by Zeokhanash** [comment]
Thank you for your fast respond. Now all is working well.

Good job for your awesome module 😉

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :7 décembre 2022 13:51
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [vigoren/foundryvtt-simple-calendar] [BUG] Can't edit Note/Details (Issue #423)


You are on an older version of simple calendar. The latest version is 2.1.60. please uninstall and reinstall the module (no data is lost when a module is uninstalled). That should resolve the issue
