### ISSUE TITLE
[BUG] Note text not editable

### ISSUE THREAD

**Issue by ralke1** [vigoren/foundryvtt-simple-calendar#425]
On foundry version 10, opening a new note or edit note does not let edit "Details"s text.

![image](https://user-images.githubusercontent.com/34632329/207456150-4e6dac56-7105-4b58-9d99-ad7b3436eaf4.png)

Terminal errors:

![image](https://user-images.githubusercontent.com/34632329/207456208-99ec7a46-76c7-4f73-99aa-431b69ffc431.png)

![image](https://user-images.githubusercontent.com/34632329/207456239-691fd0e9-7f02-499c-830d-b8b8192c2091.png)

![image](https://user-images.githubusercontent.com/34632329/207456264-f6388c89-c190-48a9-b768-2f730e6399af.png)

![image](https://user-images.githubusercontent.com/34632329/207456312-76871987-8fea-4a4f-9967-5e9721313f6c.png)

![image](https://user-images.githubusercontent.com/34632329/207456327-1d935e69-bcca-4927-a3b2-8b6dda0ec9dc.png)

**Comment by vigoren** [comment]
You are on an older version of simple calendar. The latest version is 2.1.60. please uninstall and reinstall the module (no data is lost when a module is uninstalled). That should resolve the issue

**Comment by ralke1** [comment]
i did this and solved! thanks!
