### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wardrumsjr** [vigoren/foundryvtt-simple-calendar#426]
**Cannot Save configuration on new world**

**To Reproduce**
1. Create New World
2. Open Simple Calendar Configuration
3. Change settings & hit 'Save Configuration'
4. No Change

**Expected behavior**
Should save all calendar settings

**Foundry Information**
 - Foundry Version: [v10.288]
 - Game System: [DnD5e]
 - Simple Calendar Version: [1.3.75]

**Browser (please complete the following information):**
 - FoundryVTT Client

**Comment by vigoren** [comment]
You are on an older version of simple calendar. The latest version is 2.1.60. please uninstall and reinstall the module (no data is lost when a module is uninstalled). That should resolve the issue
