### ISSUE TITLE
Sunset/Sunrise management

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#427]
Currently both sunset and sunrise are hardcoded as 6:00:00 and 18:00:00 in the calendar I am using.

I want to switch to summer earlier nautical sunrise but there's no way to edit it per day so SmallTime could manage the light on the maps. But this seems not to be possible unless I edit SmallTime settings by hand and they lack precise timestamps.

Is there a way this could be added to Small Calendar, in a way that would calculate the shift of sunrise and sunset in a realistic manner?

**Comment by vigoren** [comment]
Sunrise and Sunset times are tied to Seasons. If you go to the season settings you can set the sunrise/sunset time for the first day of that season. Simple Calendar will then adjust the sunrise/sunset of each day until it meets the time of the next season, I think that should cover what you are looking for.

**Comment by apoapostolov** [comment]
Thank you, I haven't checked there!
