### ISSUE TITLE
[BUG] Real Time Clock Doesn't Pause When Reloading The Page With Active Combat

### ISSUE THREAD

**Issue by vigoren** [vigoren/foundryvtt-simple-calendar#430]
Steps to reproduce (copied from discord and edited)

1. Enable the setting "Unify Clock Start/Pause With Game Pause".
2. Combat is started - clock pauses as per normal but no "Paused" UI wheel. 
3. Reload the canvas.
4. You should now have the normal "UI paused" wheel due to reload.
5. Unpause the game, which also unpauses the clock. Despite being in an active combat.

**Comment by kazini** [comment]
As I've seen, the bug seems to happen not necessarily with active combat, but just whenever the time on the clock is running and the game isn't paused.

**Comment by Dairid** [comment]
So this bug happens for me just as is, like I can't get the combat to auto-pause the time clock regardless of whether it's unified or not.

I've had a similar bug before where if I started combat with the game 'paused' (to give me time to set up the encounter etc), and then 'unpause' after I started combat the combat pause would not happen and i'd have spell effects just running out mid turn.  My current solution is to just no unify the pause/unpause and just do it manually as combat starts, not ideal.

I can occasionally get combat to auto-pause, but it's super inconsistent.

**Comment by vigoren** [comment]
@Dairid I think your issue is different from this.

By default the clock only pauses when there is a combat on the active scene. The active scene will have a little target next to its name in the scene list.  This is so that combats that have been set up on other scenes or old combats that weren't deleted don't cause the clock to pause.

There is a setting in Simple Calendar called "Pause Real Time Clock on Combat Rule" that can change that behavior from the active scene to "the Scene the GM is Currently Viewing". That tends to work better if as a GM you don't update the active scene or have a play style that is better suited to do that check based on the scene you are currently looking at rather than the active one. More details about that setting can be found in this page https://simplecalendar.info/pages/global-configuration/index/settings.html

If neither of those are working for you then can you let me know the version of Simple Calendar you are running, the version of FoundryVTT and the system you are playing in?

**Comment by Dairid** [comment]
So fun thing happened, I saw I did no have that option AT ALL.  Somehow my module was showing up to date etc, but was stuck way back in 1.0 so it was an old bug, once I forced the update all is well.

Thank  you

**Comment by vigoren** [comment]
This issues was fixed in version 2.1.73!
