### ISSUE TITLE
[BUG] Repeating Holiday Reminder on Reload

### ISSUE THREAD

**Issue by ZeroXNoxus** [vigoren/foundryvtt-simple-calendar#435]
**Describe the bug**
Whenever the client reloads the website he receives the note/holiday reminder for the current date while it should only be sent to chat once when the date is set.

**To Reproduce**
1. Set a holiday/note for a specific date
2. Activate the 'Remind Me' setting
3. Set the date to the holiday/note date
4. Reload the page multiple times

**Expected behavior**
Only a single message should be displayed, even when reloading the website.

**Screenshots**
![image](https://user-images.githubusercontent.com/29397572/210504341-345660bf-7b50-44d2-b9c7-676324aad149.png)

**Foundry Information**
 - Foundry Version: [0.10.291]
 - Game System: [DnD5e 2.0.3]
 - Simple Calendar Version: [current]

**Browser**
 - Browser [Google Chrome (current release)]

**Comment by vigoren** [comment]
Hey!
This is actually working as intended. Since simple calendar can't tell the difference between a page refresh and coming back to a session after a while it will re-alert users to events that are currently happening. The idea is that after a break this week refresh a players memory on what is going on in the game.

If you do not want this to happen can disable the feature. Under the Note Settings there is an option called "Send Reminders On Login", turning that off will stop reminders being sent when a page is refreshed.

Hope that helps!

**Comment by ZeroXNoxus** [comment]
Hey, sorry for the late answer, had some long days lately. I've looked for the "Send Reminders On Login" option you described but I can't find it anywhere:
![image](https://user-images.githubusercontent.com/29397572/211102200-a6c6281f-eb63-4b1e-912a-698cc6ba685d.png)

**Comment by vigoren** [comment]
Ah you are on a old version of Simple Calendar. That setting was added in version 2.0.0

What version of foundry are you using? If you are on version 10 uninstalling and reinstalling the module will get you the latest version

If you are on Version 9 you can uninstall and manually install version 2.0.30 (that's the last version that supports version 9 of foundry).
That version can be found here https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v2.0.30

Manual installation information can be found here, it might work if you try installing through foundry again, I just can't remember for sure.
https://github.com/vigoren/foundryvtt-simple-calendar#installing-the-module

In either case uninstalling does not remove any data so everything will still be there!

**Comment by ZeroXNoxus** [comment]
Oh I see, I've always updated via FoundryVTT module manager, so I thought I'm on the current version! That should fix the issue, thanks!
