### ISSUE TITLE
[FEATURE] Starting year for leap years calculation

### ISSUE THREAD

**Issue by mcavallo** [vigoren/foundryvtt-simple-calendar#438]
Hi,

I'm currently trying to implement the calendar of the hyborian age (Conan) using a combination of year names and leap years. I nearly got it working as intended but I couldn't get the leap years to align. When you use custom leap years it seems to be assumed that the first leap year in the cycle is not the first year in the calendar, so I'm wondering if there's a way go around this or if this is an option you might consider to include.

Thank you in advance for taking the time to read this.

## Example
**This is how it works today:**
Leap years are configured every 3 years
The first leap year is year 3 and the next is year 6

**This is what I'm trying to achieve:**
Leap years are configured every 3 years, starting on year 1
The first leap year is year 1 and the next is year 4

## Reference
For reference here's the calendar I'm trying to implement:

![image](https://user-images.githubusercontent.com/697518/211209315-8c8322b2-8325-4350-b108-20a2aa162dd3.png)

## Export
Here's an export of what I have so far:
https://pastebin.com/9XWPHDBA

**Comment by vigoren** [comment]
Hey sorry about taking so long to get back to you about this.

right now Leap years always start on year 0, I can look at adding an option where you can specify which year leap years start from or use the Year Zero setting for that as well.

**Comment by mcavallo** [comment]
No worries, thank you for the reply. Right, if you would consider to add a field/setting to offset the index from 0 to 1 (default being 0) it would account for cases like this.

I'd be more than happy to open a PR with the fully fledged calendar preset for others to use if you decide to implement the feature. As a way of giving back :)

**Comment by vigoren** [comment]
Been a long time but this feature has been added to version 2.4.0.

You can set the [Starting Year](https://simplecalendar.info/docs/calendar-configuration/leap-year-settings#starting-year) option under the leap year settings to specify the first year that a leap year happens and all other leap years will flow from that.

**Comment by mcavallo** [comment]
I'll open the PR with the Hyborian calendar as soon as I'm done with it. Thanks a lot for the update! 🎉
