### ISSUE TITLE
[FEATURE] Show more moons in compact view

### ISSUE THREAD

**Issue by gsterling** [vigoren/foundryvtt-simple-calendar#448]
**Is your feature request related to a problem? Please describe.**
My systems has 3 moons. I'd like to see each of them at the same time.

**Describe the solution you'd like**
I'd like to see at least 3 Moons at the same time. There should be enough room to display them.
![image](https://user-images.githubusercontent.com/58980630/215264102-234876de-b733-440c-9829-a6941b69d1fc.png)

**Describe alternatives you've considered**
Have a setting in the compact view options to define how many moons should be visible?
![image](https://user-images.githubusercontent.com/58980630/215264223-f7f236d1-ae28-4b98-8376-8b076fc627a5.png)

**Additional context**
\-

**Comment by vigoren** [comment]
I could probably just increase the number shown there. 2 is from the code for showing moons on the full calendar display where more than 2 can start overlapping with other dates. I just reused that code to keep things simple but can see just showing more.

**Comment by vigoren** [comment]
In version 2.1.80 I updated the compact view to show up to 5 moons before collapsing them into the dropdown.
