### ISSUE TITLE
[FEATURE] Scale the compact view window

### ISSUE THREAD

**Issue by gsterling** [vigoren/foundryvtt-simple-calendar#449]
**Is your feature request related to a problem? Please describe.**
I like the compact view, but not for it's small size, but it's cleanliness and usefulness. But it's a bit small on my screen. Can you add an option to scale it? The font is very small and I have problems seeing everything in it. It's even smaller then everything else, which doesn't have such a lot of info put in such a small place.

**Describe the solution you'd like**
I'd like to have the option to scale the simple calendar window by let's say 50%, 75%, 100%, 150%, 200%.

**Describe alternatives you've considered**
Rescaling the whole application. But I am happy with the size of everything else.

**Additional context**
I think here you can see, that it's just a bit smaller then everything else. Enough to make it hard to read especially the moon phasees and buttons. I mean I know, which button does what, but it just doesn't look good with the low contrast.
![image](https://user-images.githubusercontent.com/58980630/215264401-85f3bf77-877d-4b56-993c-d78791362edc.png)
It might look ok on a Full HD monitor, but on a 4k screen it's tiny.

**Comment by vigoren** [comment]
Yeah I don't have a 4k monitor so it could be quite small. I can look at adding a scaling option or improving it on high resolution monitors.

**Comment by vigoren** [comment]
In version 2.1.80 I have added scaling options to the client settings, you can scale the UI Larger or smaller in increments of 10 from 70% to 200%. That should hopefully allow you to get the compact view scaled larger for your screen!
