### ISSUE TITLE
[FEATURE] Autmoatically save note text when clicking save note

### ISSUE THREAD

**Issue by jonepatr** [vigoren/foundryvtt-simple-calendar#45]
**Is your feature request related to a problem? Please describe.**
It's confusing when you get a warning that you have to save the rich text editor. It's not completely obvious how to do that at first and is easily interpreted as a bug

**Describe the solution you'd like**
When I click save note it should save the rich text editor for me. I don't see the point in doing this step manually. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by vigoren** [comment]
I think this should be doable, I will look into it.

**Comment by vigoren** [comment]
This has been implemented in version 1.2.5. Thanks for the feedback!
