### ISSUE TITLE
[FEATURE] Have the game clock update more than once per second

### ISSUE THREAD

**Issue by gsterling** [vigoren/foundryvtt-simple-calendar#450]
**Is your feature request related to a problem? Please describe.**
I want a faster game time, but don't want it to jump in increments of 2. Right now the clock can only be updated at a minimum of 1 time per second. So the only solution for having an accelerated timeflow would be to not display every tick on the clock, but to skip some.

**Describe the solution you'd like**
I'd like to have the time updated every half second, so I can increase the game time by a factor of 2 compared to the real world, but still have a "normal" looking passage of time.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by vigoren** [comment]
This is something that should be doable!

**Comment by vigoren** [comment]
The Update Frequency has been updated to support decimals in version 2.1.80, you can set "Update Frequency" to 0.5 and "Game Seconds Per Real Life Seconds" to 2 and get the game to move at twice the speed but have the clock still update for every game second.
