### ISSUE TITLE
[BUG] Update deleted entire content

### ISSUE THREAD

**Issue by Failtier** [vigoren/foundryvtt-simple-calendar#451]
Congratulations,

I just updated the calendar to the new and much worse version, and in the process, it deleted my entire custom configurations and dumped them as journal entries. This is so bad, I decided that I don't need that calendar at all for the hours I have wasted now.

Of course, no backup of my old data, but I am not planning to use that new calendar anyways.

**Comment by vigoren** [comment]
It seems foundry is installing a really old version of my module right now for some reason. I'm working with them to figure out why 

None of your data would have been deleted, it should still all be there. 

Until foundry fixes the issue you can manually install the latest version using this link https://github.com/vigoren/foundryvtt-simple-calendar/releases/download/v2.1.73/module.json

**Comment by vigoren** [comment]
The issue of installing an old version seems to have been fixed.

Uninstalling the module and reinstalling it should then get it back working the way it was before.

Sorry about the issue.

**Comment by Failtier** [comment]
Thank you so much, it also brought back my old calendar and all notes I've been working on for hours, awesome!
