### ISSUE TITLE
[BUG] simple-calendar-date-time-change fires multiple times per date/time change

### ISSUE THREAD

**Issue by PlasticMohawk** [vigoren/foundryvtt-simple-calendar#452]
**Describe the bug**
* Given a dnd5e world with only the Simple Calendar module enabled (repeat: no other modules enabled):
* When the clock hits the turn of an hour (example: 11:59:59 -> 12:00:00),
* The hook, simple-calendar-date-time-change is fired twice instead of only once

**To Reproduce**
1. Create a console.log world script based on the hook: simple-calendar-date-time-change
2. In the game world, set Simple Calendar's time clock to something like: 11:59:55
3. Let the clock run for a few seconds, watching the browser console.
4. When the click hits 12:00:00, the hook fires twice instead of only once.
4a. This seems to happen intermittently at various time changes

**Expected behavior**
I expect the hook "simple-calendar-date-time-change" to fire only once per second (or once per manual change of the clock)
Observed: Occasionally, and always when there's a new hour, such as 11:59:59 -> 12:00:00, this hook will fire twice.

**Screenshots**
![image](https://user-images.githubusercontent.com/5216225/215516732-cd1be5f6-7a72-42fa-854e-1d831bd05b3e.png)

**Foundry Information**
 - Foundry Version: 10 build 291
 - Game System: DnD5e
 - Simple Calendar Version: 2.1.73
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
 - Browser: Chrome Version 109.0.5414.120 (Official Build) (64-bit)

My use case/goal is, I'm trying to set up a World Script which runs a macro on certain in-game times of day. The use of this macro demonstrates the information shown in the screenshot as well as this issue.
[date-time-change.txt](https://github.com/vigoren/foundryvtt-simple-calendar/files/10537090/date-time-change.txt)

**Comment by vigoren** [comment]
This should be fixed in version 2.1.80!
