### ISSUE TITLE
[BUG] Time increment dropdown menu vanishes above the screen in Compact Window

### ISSUE THREAD

**Issue by GambetTV** [vigoren/foundryvtt-simple-calendar#455]
For my purposes, the cleanest looking spot to have Simple Calendar open in is in compact mode at the top of the screen. Unfortunately, placing the calendar here means that if I open the time increment dropdown menu, because it only opens upward, I can only see Day/Month/Year increments, and have to pull the window down significantly to see Second/Round/Minute/Hour. Unfortunately, it's not super feasible to just leave the window down here.

If possible, it'd be great if the dropdown would drop, y'know, *down*, below the window, if it's at a high enough position to get obscured.

I attached a screenshot of what I'm talking about.

![image](https://user-images.githubusercontent.com/72000497/215959121-3bcd0876-805a-461e-bea9-98e85c7ec5be.png)

**Comment by vigoren** [comment]
That should be going down not up. I will look into fixing this.

**Comment by vigoren** [comment]
This should be fixed in version 2.1.80!
