### ISSUE TITLE
[BUG] Quick Increment not showing

### ISSUE THREAD

**Issue by KLSteinwand** [vigoren/foundryvtt-simple-calendar#458]
**Describe the bug**
When in compact mode, Quick Increment does not show any buttons, but Full Control still does.

**To Reproduce**
Unsure as I've talked with other users, but they are not experiencing this behavior.

**Foundry Information**
 - Foundry Version: 10.291
 - Game System: PF2e 4.6.8
 - Simple Calendar Version: 2.1.80
 - Simple Calendar Configuration: Sync to PF2e calendar

**Browser (please complete the following information):**
 - Foundry App
 
**Additional context**
Even with no other modules active, this occurs.

**Comment by vigoren** [comment]
That is strange, the only time I have seen similar issues is when something isn't loading correctly. Though it should be kissing fine in the app.

- does it happen when Simple Calendar is the only active module?
- When in the Foundry app are there any errors in the console? (hitting F12 will show the console, errors will be listed in red)

**Comment by KLSteinwand** [comment]
So doing some more digging, the Show Clock option does still need to be checked on, but that is still giving players the clock in the calendar, where as previously I was able to get it to not show the clock on the player's view. I guess part of it was just me forgetting that Show Clock had to be enabled for Round/Minute increments, but now I can't have that without players seeing what the time is. Did I just have some random bug load previously thinking that it was a feature?

**Comment by vigoren** [comment]
Sorry about the delay in getting back to you.

That does sound like a bug that you thought was a feature. The show clock option should disable the clock for everyone (GM and players). With the clock disabled it doesn't really make sense to have controls for advancing the time by units less than a day.  

That said I feel like the quick increment option should either be disabled if the clock is set to not show or it should show options for days, months and years instead

**Comment by vigoren** [comment]
Sorry about the long delay in getting back to you about this (had a couple months of medical issues).

This issue should be fixed in version 2.2.0!
