### ISSUE TITLE
[BUG] Can't save text when using Meme - Moerills Expandable Markdown Editor

### ISSUE THREAD

**Issue by jonepatr** [vigoren/foundryvtt-simple-calendar#46]
**Describe the bug**
When writing a note I can't save it when the markdown editor addon is enabled.

**To Reproduce**
1. Enable "Meme - Moerills Expandable Markdown Editor"
2. Open the simple calendar and click "add new note"
3. Enter a title 
4. Enter some note text
5. Click save (for the rich text editor)
6. Click save note
7. Show the note

**Expected behavior**
The text to be in the notes field

**Browser (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Browser Version 89.0.4389.90 (Official Build) (arm64)

**Additional context**
I'm using the twodsix system (v 0.7.26) and foundry vtt (v 0.7.0)

**Comment by vigoren** [comment]
I personally haven't tried this editor so it will require some investigation to try and make it work.
