### ISSUE TITLE
[BUG] Current world time does not accurately persist between refreshes

### ISSUE THREAD

**Issue by PlasticMohawk** [vigoren/foundryvtt-simple-calendar#462]
**Describe the bug**

If the Simple Calendar clock is running, and I reload the page or reload the game world, the currently displayed time is behind by a few in-game seconds.

**To Reproduce**

1. Let the clock run for an arbitrary amount of time.
2. Reload the page, making a note of what the time was in-game when you reloaded.
3. After the page reload, check the Simple Calendar clock. It most likely is behind by a few seconds.
4. See screenshots below

Before reloading
![image](https://user-images.githubusercontent.com/5216225/217558970-0d29415c-f487-42c9-ba68-b88a0c387a0d.png)

After reloading
![image](https://user-images.githubusercontent.com/5216225/217559171-db2619dc-57f2-4510-af58-e406dc103bb2.png)

**Expected behavior**

For example, if the clock says 12:00:00 when I reload the page or reload the world, after reloading, I expect the clock to still be at 12:00:00. Instead, I observe that after reloading, the clock is behind, e.g. 11:59:58 in this example.

**Screenshots**
See above

**Foundry Information**
 - Foundry Version: 10.291
 - Game System: DnD5e
 - Simple Calendar Version: 2.1.80

**Browser (please complete the following information):**
 - Chrome v 109.0.5414.120

**Additional context**

**Comment by vigoren** [comment]
Hey, this is actually working as intended. Saving the current date to foundry's data base can be a little intensive so I avoid doing that every second while the clock is running and instead will save the current date/time every 10 seconds. So when running the clock and you refresh the browser it will depend on where in that 10 second save internal you are as to how much time is seemed to be lost.
