### ISSUE TITLE
Missing Calendar.html

### ISSUE THREAD

**Issue by Aavar6802** [vigoren/foundryvtt-simple-calendar#465]
After updating to 2.1.80 the calendar can no longer be opened. The error is:

"no such file or directory, open '/localpath/FoundryVTT/Data/modules/foundryvtt-simple-calendar/templates/calendar.html'"

**Comment by vigoren** [comment]
This is usually a caching issue where foundry is still trying to load an old file. You can try: 

- restarting foundry
- clearing your browsers cache
- try in a different browser

**Comment by Aavar6802** [comment]
Thanks - Clearing cache worked.
