### ISSUE TITLE
[BUG] Cannot open calendar entry occasionally.

### ISSUE THREAD

**Issue by jonathanmclaus** [vigoren/foundryvtt-simple-calendar#468]
**Describe the bug**
Sometimes I can't open certain entries on my calendar. Other entries function normally. This seems to typically happen when I open an entry, close its window, and then can't reopen that same entry.

**To Reproduce**
1. Open calendar.
3. Double click on entry.

**Error**
This is the error in the console log when the entry fails to open.

```
foundry.js:5485 Uncaught TypeError: undefined. Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
[Detected 1 package: foundryvtt-simple-calendar]
    at NoteSheet.bringToTop (foundry.js:5485:36)
    at ts.showNote (index.js:1:262471)
    at MainApp.viewNote (index.js:1:151715)
```

![image](https://user-images.githubusercontent.com/5731591/221315453-680ecbdc-58b8-44c5-a088-ef750de8660b.png)

**Foundry Information**
 - Foundry Version: [e.g. v10.291]
 - Game System: [e.g. PF2]
 - Simple Calendar Version: [eg 2.1.80]
 - Simple Calendar Configuration: [standard Pathfinder 2E]

**Browser (please complete the following information):**
 - Chrome

**Comment by vigoren** [comment]
I was unable to replicate this issue but I think I see where it was happening and implemented a fix in version 2.3.6 to help with that. If the issue persists please let me know.
