### ISSUE TITLE
[FEATURE] When having multiple days that start with the same letter, use multiple letters to distinguish between them

### ISSUE THREAD

**Issue by jonepatr** [vigoren/foundryvtt-simple-calendar#47]
**Is your feature request related to a problem? Please describe.**
Would be a nice addition to make it a bit clear which day it is. Not super important though.

**Describe the solution you'd like**
When multiple days share initial letters, use as many letters to make each short form unique (in month view), e.g.
M Tu W Th F Sa Su for the regular calendar. 

**Describe alternatives you've considered**
Let it be an option to show the full name (but in smaller font)? 

**Additional context**
-

**Comment by vigoren** [comment]
Yeah good points. I think with the full name, even with smaller text it will be too much.

If you hover over the weekday name it will show the full name but having 2 letters might be better.

**Comment by vigoren** [comment]
In version 1.2.5 weekdays will now have 2 letters representing them. Thanks for the feedback!
