### ISSUE TITLE
Notes don't collapse

### ISSUE THREAD

**Issue by Monation** [vigoren/foundryvtt-simple-calendar#472]
There is no functionality to make the notes go away. 

Open SimpleCalendar
Click on Notes button
Click on Notes button again

**Expected behavior**
Once they appear, Clicking on the notes button should make them go away, but they don't, they just stay there.

**Foundry Information**
 - Foundry Version: 10
 - Game System: PF2E
 - Simple Calendar Version: 2.1.80
 - Simple Calendar Configuration: nothing fancy

**Browser (please complete the following information):**
Firefox (latest version)

**Comment by vigoren** [comment]
This has been fixed in version 2.3.16!
