### ISSUE TITLE
[BUG] Themes don't work if Foundry uses routePrefix

### ISSUE THREAD

**Issue by grz0** [vigoren/foundryvtt-simple-calendar#473]
**Describe the bug**
Themes don't work when Foundry uses routePrefix. 
Simple calendar uses URL without routeprefix, for example:
https://hostname.domain/systems/wfrp4e/ui/sidebar_button-background_grey.webp
but is should use:
https://hostname.domain/routeprefixhere/systems/wfrp4e/ui/sidebar_button-background_grey.webp

**To Reproduce**
1. set routePrefix in Foundry config
2. set a theme in SC config, for example Warhammer theme.

**Expected behavior**
Simple calendar should work when routePrefix is set.

**Foundry Information**
 - Foundry Version: 6.3.1
 - Game System: warhammer
 - Simple Calendar Version: 2.1.80

**Comment by vigoren** [comment]
Hey sorry about the long delay in getting back to you about this (had a couple months of medical issues).

This issue should be fixed in version 2.2.0!
