### ISSUE TITLE
Mistranslation in French, moon phases icons names

### ISSUE THREAD

**Issue by Dame-du-Lac** [vigoren/foundryvtt-simple-calendar#474]
Hi

First, thank you very much for this tool, it's great!

I have a bug to report about the moon phases icons names in French. I suppose the strings were translated without context, and it created some mistakes.
Here are the correct translations :
• New Moon => Nouvelle lune (actual translation OK)
• Waxing Crescent => **Premier croissant** (actual transation "Lune croissante", mistranslation)
• First Quarter => **Premier quartier**  (actual transation "Premier trimestre", mistranslation)
• Waxing Gibbous => Lune gibbeuse croissante (actual translation OK)
• Full Moon => Pleine lune (actual translation OK)
• Waning Gibbous => Lune gibbeuse décroissante (actual translation OK)
• Last Quarter => **Dernier quartier**  (actual transation "Dernier trimestre", mistranslation)
• Waning Crescent => **Dernier croissant**  (actual transation "Lune décroissante", mistranslation)

**Comment by vigoren** [comment]
It seems like these translations were update in version 2.1.40 of Simple Calendar.
An existing moon might have the old names still though if it was created before that version was released.
