### ISSUE TITLE
[FEATURE] Reminded

### ISSUE THREAD

**Issue by GregorHak** [vigoren/foundryvtt-simple-calendar#484]
Now you must create note, then open it, and click Reminded button.
Can you add option to Reminded already when creating calendar note? 

![Bez nazwy-1](https://user-images.githubusercontent.com/99994770/228773037-73093a72-b898-4ba4-8257-0d988bf00616.png)

**Comment by vigoren** [comment]
This option has been added in version 2.3.0!

**Comment by GregorHak** [comment]
Thanks
