### ISSUE TITLE
[BUG] Documentation website links are broken

### ISSUE THREAD

**Issue by logoff** [vigoren/foundryvtt-simple-calendar#485]
**Describe the bug**
All website links https://simplecalendar.info/ produce 404 errors

**To Reproduce**
1. Go to https://simplecalendar.info/
2. Click on any link
3. Get 404

**Expected behavior**
I would expect navigating to working pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/1023895/231580808-d9e7ae80-9302-474f-96b2-08a112c353ac.png)

**Foundry Information**
 - N/A

**Browser (please complete the following information):**
 - Google Chrome up-to-date. But I guess this is not relevant at all.

**Additional context**
N/A

**Comment by vigoren** [comment]
This was fixed a while ago but the paths have changed with the new website. Redirects should take care of the rest.
