### ISSUE TITLE
[FEATURE] Have chat timestamp reflect in-game time rather than IRL time

### ISSUE THREAD

**Issue by GambetTV** [vigoren/foundryvtt-simple-calendar#490]
Right now when you send a message in chat, it lets you know how long ago you sent the message, such as "2 minutes ago" or whatever. Interestingly when you save the chat log, it outputs as a date/time, using I assume your computer's IRL clock. There are also modules, such as "Chat Message Timestamp" that output this timestamp into Foundry's chat instead of the "2 minutes ago" message, which is more useful. But I think it would be neat if your module could override the normal timestamp, and instead output Simple Calendar's timestamp instead. In that way it would better allow us to keep track of time, and would actually make the logs more useful as it would tell us when something occurred in game, from the character's perspective.

**Comment by vigoren** [comment]
This has been added in version 2.3.0 of Simple Calendar. It can be turned on using the [Use Game Time For Chat Messages](https://simplecalendar.info/docs/global-configuration/settings#use-game-time-for-chat-message-timestamps) setting under the global configuration.

How the date is displayed can be customized with the new [Chat Message Timestamp Format](https://simplecalendar.info/docs/calendar-configuration/display-options#datetime-formatting) setting under the Display Options.

Important to note that these changes will only apply to messages sent after this update has been installed.
