### ISSUE TITLE
[BUG] Can not select macro to execute

### ISSUE THREAD

**Issue by sanguaire** [vigoren/foundryvtt-simple-calendar#491]
**Describe the bug**
When I want to select a macro for an event, I can open the list of macros. When I select one, the selection is not saved.

**To Reproduce**
1. Go to 'an event'
2. Open the configuration dialog for the event
3. Try to select an macro

**Expected behavior**
The selected macro is saved in the event

**Screenshots**

**Foundry Information**
 - Foundry Version: 10.291
 - Simple Calendar Version: 2.1.80

**Browser (please complete the following information):**
 - Browser chrome

**Comment by vigoren** [comment]
Hey sorry about the long delay in getting back to you about this (had a couple months of medical issues).

This issue should be fixed in version 2.2.0!

**Comment by sanguaire** [comment]
Thank you
