### ISSUE TITLE
[BUG] Pathfinder 2e: Despite linking Simple Calender and the World Clock in the setting, World Clock one Day ahead

### ISSUE THREAD

**Issue by Westtantemala** [vigoren/foundryvtt-simple-calendar#496]
Hello,
I've been using Foundry and Simple Calendar together for a while now, but recently I've found that the World TimeClock always seems to be a day/24 hours ahead of the SC when the Game World Time integration is set to Mixed, and the World Time Sync is is enabled.

All other aspects of the calendar seem to be working as intended.

![Calendar](https://github.com/vigoren/foundryvtt-simple-calendar/assets/134189422/f2023918-2b7c-481b-bba5-af6ca22f42ac)

**Foundry Information**
 - Foundry Version: [10 Patch 6/291]
 - Game System: [Pathfinder 2e]
 - Simple Calendar Version: [2.1.80]
 

**Browser (please complete the following information):**
 - Browser [Firefox]

**Comment by vigoren** [comment]
There are a few edge cases where time in Simple Calendar will be off by a day from the PF2E World Clock. This has to do with how each addresses leap years and is not easily fixed from the side of PF2E.

I [brought this up with the PF2E devs](https://github.com/foundryvtt/pf2e/issues/1772) a while ago but it isn't something they are going to change. Unfortunately that means there will be this discrepancy for certain years in the Calendar.
