### ISSUE TITLE
[BUG] Compact view window changes size while typing anywhere

### ISSUE THREAD

**Issue by gsterling** [vigoren/foundryvtt-simple-calendar#499]
**Describe the bug**
Since the introduction of the dynamic time skip interval buttons (thanks again!) the compact view window changes it's size when pressing ctrl or shift anywhere, even why typing in an input field.

**To Reproduce**
1. Open the compact view with the quick time control buttons
2. Click in the chat
3. Type stuff while pressing shift or paste something with ctrl+v
4. See the window changing it's width

**Expected behavior**
The buttons should always remain the same size, regardless of which buttons are pressed. The problem isn't the buttons changing it's label or functionality while inside another input field. It's just irritating, that the size of the window changes while typing or even selecting additional targets or tokens.

**Screenshots**
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/58980630/9b943a41-79e2-40f6-934b-8bfbc0f6cb8c)
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/58980630/d9d68b23-8cc8-4d3f-9121-503822273f6c)
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/58980630/43d61b3f-664a-4ded-ae48-5b9f6a3a71ac)

**Foundry Information**
 - Foundry Version: 10.291
 - Game System: Splittermond 0.9.8
 - Simple Calendar Version: 2.2.0

**Browser (please complete the following information):**
 - Browser: Chromium and the standalone FoundryVTT node.js client

**Additional context**
I deactivated all modules besides Simple Calendar and the problem still exists.

**Comment by vigoren** [comment]
This has been fixed in version 2.3.0!
