### ISSUE TITLE
[BUG] Leap Year tab is unnecessary on two rows

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#50]
Please remove the word "Settings" for English-language tabs to appear as a single line text.

![image](https://user-images.githubusercontent.com/4083812/113559986-f2aa0480-960a-11eb-873a-17decb7a4b93.png)

**Comment by vigoren** [comment]
This should be fixed in version 1.2.5. Thanks for the feedback!
