### ISSUE TITLE
[BUG]  White border

### ISSUE THREAD

**Issue by FatGiwafe** [vigoren/foundryvtt-simple-calendar#503]
**Describe the bug**

The Calendar has a white border around it

**To Reproduce**

Set Theme to Warhammer Fantasy Roleplay 4th Edition

**Expected behavior**

I expected not to see a white border, which is absent on other Themes

**Screenshots**
See attached file

**Foundry Information**
 - Foundry Version: 10
 - Game System: Warhammer Fantasy Roleplay 4th Edition
 - Simple Calendar Version: [eg 2.2.0]
 - Simple Calendar Configuration: Quick Setup to Warhammer Calendar, other paramaters are default

**Browser (please complete the following information):**
 - Browser: Firefox

![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/116798137/59eb12c3-648e-47d1-b251-01be490d9050)

**Comment by vigoren** [comment]
For some reason it isn't loading the correct image file from the Warhammer system. I have made changes in version 2.3.0 that should make it less glaring when an image can't be loaded!
