### ISSUE TITLE
[BUG] In V11 D&D 2.2.1 Foundry when SImple Calendar is live, journal won't open. 

### ISSUE THREAD

**Issue by YenBenGrey** [vigoren/foundryvtt-simple-calendar#505]
**Describe the bug**
As the title explains 

**Expected behavior**
Journal to open as normal

**Screenshots**

**Foundry Information**
 - Foundry Version: 11.302
 - Game System: DND5e 2.2.1
 - Simple Calendar Version: 2.2.0
 - Simple Calendar Configuration: Faerun Calendar of Haptos

**Browser (please complete the following information):**
 - Browser Chrome and Foundry App
**Additional context**
<img width="768" alt="Screenshot 2023-06-28 at 17 24 32" src="https://github.com/vigoren/foundryvtt-simple-calendar/assets/98095856/2ec61c22-cf05-4333-87ef-c2ae2bdd901c">

**Comment by vigoren** [comment]
Talked in Discord about it. Issue was the default sheet for journal entries got set to use the Simple Calendar Note sheet. Changing it back to the default sheet fixed the issue.
