### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by lektu** [vigoren/foundryvtt-simple-calendar#507]
**Is your feature request related to a problem? Please describe.**

The new feature to change chat message timestamps to use the SC time is great. However, it does show the HH:mm even if I'm not really using it (I don't synch SC with the clock, or use time, as opposed to date, in any way).

Also, as I haven't set or used time in any way, I don't know why all chat messages appear with 00:05. That's surely not a bug but piloting error, but again, I don't use time with SC, just dates, and I have time disabled everywhere AFAIK.

**Describe the solution you'd like**
Just an option to specify I don't want time in my timestamps (paradoxical, but true).

**Describe alternatives you've considered**
I tried to use CSS to just make the HH:mm part invisible, but the whole timestamp is a single span entity.

![timestamp](https://github.com/vigoren/foundryvtt-simple-calendar/assets/833999/963acfc9-dc3b-4402-b199-da65949fb2d2)

**Comment by vigoren** [comment]
You can customize this using [Chat Message Timestamp Format](https://simplecalendar.info/docs/calendar-configuration/display-options#datetime-formatting) option in the configuration under Display Options. Just remove the `HH:mm` from the format and the time will no longer show.

**Comment by lektu** [comment]
Yes. I'm in idiot. Sorry for the noise.

**Comment by vigoren** [comment]
No worries!
