### ISSUE TITLE
[FEATURE] Extend the dialog height by enough to show the top two events per day

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#51]
The current UI is sized to show the calendar and settings but any day that has events recorded to it will need scrolling of the dialog UI to show them. Please extend the height and make UI placeholders for events below the calendar so that at least 2-3 events per day can be viewed without scrolling.

**Comment by vigoren** [comment]
The calendar window should be tall enough to see 2 events in version 1.2.5. Thanks for the feedback!

**Comment by apoapostolov** [comment]
Not happening on my 0.7.9 calendar 1.2.5. Tested with Culprit for some mod that could misbehave

![image](https://user-images.githubusercontent.com/4083812/113734878-65e37180-9704-11eb-8435-e1651473e8b4.png)

**Comment by vigoren** [comment]
Hmm ok I think I might know the culprit, will reopen this until it is actually fixed.

**Comment by vigoren** [comment]
This should actually be fixed now in the most recent release.
