### ISSUE TITLE
[BUG]  First roll is always done twice on startup

### ISSUE THREAD

**Issue by WaterpoloBlock** [vigoren/foundryvtt-simple-calendar#515]
**Describe the bug**
After starting up the server and joining the game. If I do any action which would require a roll in chat: Attack, damage, macro or dice roll it will always do it twice.

**To Reproduce**

Make sure Simple Calendar is installed and enabled.

1. Go into game
2. Type in /Roll 1d20
3. See Double message

**Expected behavior**
For it to not double roll/ or bring up the output twice.
This didn't occur last week.

**Screenshots**
![First_Roll](https://github.com/vigoren/foundryvtt-simple-calendar/assets/73310678/29698de0-ea72-4c8c-b329-2105112803ca)

**Foundry Information**
 - Foundry Version: V11 (Build 304)
 - Game System: PF2e (5.1.0)
 - Simple Calendar Version: [2.3]
 - Simple Calendar Configuration: [Stock settings]

**Browser (please complete the following information):**
 - Browser [Brave, aka Chrome]

**Additional context**
Only have two modules enabled:
Simple Calendar and The Forge.

Afterwards, the rolls will be normal. But I did have a similar issue in WorkBench. [Where it did the Recovery Checks twice.](https://github.com/xdy/xdy-pf2e-workbench/issues/868#issuecomment-1623261565)

**Comment by vigoren** [comment]
Confirmed this is a bug, I have a fix that will be in the next release (hopefully in a few days).

**Comment by vigoren** [comment]
This has been fixed in version 2.3.6!
