### ISSUE TITLE
[BUG] Incorrect Path Referencing for Warhammer Fantasy Theme on The Forge

### ISSUE THREAD

**Issue by jtsmirror** [vigoren/foundryvtt-simple-calendar#517]
**Describe the bug**
The issue involves the Warhammer Fantasy Roleplay 4th Edition theme on The Forge not referencing the correct paths, which results in certain UI elements not being used.

**To Reproduce**
1. Use The Forge to host your game
2. Select the 'Warhammer Fantasy Roleplay 4th Edition' theme
3. Navigate to Simple Calendar
4. Observe that certain UI elements are not being used due to incorrect path referencing

**Expected behavior**
The expected outcome is that all the UI elements are properly utilized in Warhammer Theme

**Screenshots**
The Forge
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/136428641/1b6b98fe-71da-4196-a4fc-8f50bf7a37aa)
Foundry VTT App
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/136428641/e7e40024-e297-4821-b305-8b9e86be1d2d)

**Foundry Information**
 - Foundry Version: [11]
 - Game System: [Warhammer Fantasy Roleplay 4ed]
 - Simple Calendar Version: [2.3.6]
 - Simple Calendar Configuration: [Warhammer Fantasy Theme]

**Browser (please complete the following information):**
 - Browser [Chrome]

**Additional context**
This bug only manifests when hosting on The Forge. Upon checking the Foundry application itself, everything works as expected. Additionally, for The Forge, the Warhammer Fantasy Theme functions properly only when the module is installed through the Summon Import Wizard. I think that the issue lies in how The Forge handles path referencing compared to Foundry VTT's standalone application.

**Comment by vigoren** [comment]
This has been fixed in version 2.3.13!
