### ISSUE TITLE
[BUG] Long Date Format Display Issue in Warhammer Fantasy Theme

### ISSUE THREAD

**Issue by jtsmirror** [vigoren/foundryvtt-simple-calendar#518]
**Describe the bug**
The bug pertains to "text stretchability." (im not quite is this what to call it) Specifically, when the Date Format used in Compact view while utilizing the Warhammer Theme is too long, the text does not stretch appropriately.

**To Reproduce**
1. Select Warhammer Fantasy Theme
2. Set 'Date Format' in display settings to something long
3. Observe that the text does not stretch as expected

**Expected behavior**
The expected behavior is that regardless of the length of the Date Format, the text should stretch adequately to accommodate it within the Compact View. 

**Screenshots**
How it look (Warhammer Theme)
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/136428641/7810e52a-02dd-4be8-b4fd-6fe8a33a5345)
How i want it to look (Dark Theme)
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/136428641/7267e0e3-945f-4c12-b676-197690b90e2f)

**Foundry Information**
 - Foundry Version: [11]
 - Game System: [Warhammer Fantasy Roleplay 4ed]
 - Simple Calendar Version: [2.3.6]
 - Simple Calendar Configuration: [Warhammer Fantasy Theme]

**Browser (please complete the following information):**
 - Browser [Chrome]

**Additional context**
-

**Comment by vigoren** [comment]
This has been fixed in version 2.3.13!
