### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by galaara98** [vigoren/foundryvtt-simple-calendar#523]
**Describe the bug**
Month's in year zero are not showing the right amount of days
Month with 1 day is showing up as 30 days is some interfaces, Months with 28 days are showing up as 30 days in some interfaces

**To Reproduce**
Custom Calendar
Year: All defaults except
Current Year: 0
Year Postfix: CE
Year Zero 0

Month:
14 Months
Named Alphabetically from AXXXX to MXXXX, then "Void Day"
Month 1-13 have 28 days [totaling 364]
Month 14 has 1 [total day count = 365]

Weekdays
renamed, but left count at 7, no special settings.

Seasons:
4 Renamed and Split Every 91 days (3.25 * 28 totaling 364)
1 New, 1 day long (making 365 days)

Moon, 2
1 - Cycle Length 28.07692307692 [*13 = 365], Cycle Adjust = 0, Year 0, New Moon = Void Day (365th day of year)
2 - Cycle Length 365, Cycle Adjust = 0, Year 0, New Moon = Void Day (365th day of year)

No other changes

**Expected behavior**
Year 0 having proper days in a month (all months have 30 days in the calendar in year 0)
Interfaces like "Now Moon Month and Day" are showing 30 days no matter what year we are in and no matter how many actual days are in the month (for instance My 14th month should have 1, this interface is showing 30, I set my 14th month to have 100 days, and this Dialog only showed 30)
Note I believe it has something to do with year 0 also, because if I scroll through the months, it eventually starts looking ok (as if I had moved into year 1 or -1 and it looks better)

**Screenshots**

**Foundry Information**
 - Foundry Version: [e.g. 11.305]
 - Game System: [e.g. pf2e]
 - Simple Calendar Version: [2.3.13]
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
[simple-calendar-export_bug.json.txt](https://github.com/vigoren/foundryvtt-simple-calendar/files/12045983/simple-calendar-export_bug.json.txt)
![Simple Calendar issues](https://github.com/vigoren/foundryvtt-simple-calendar/assets/178406/8c0e390c-86f8-43e3-94a9-9225e602942d)

**Additional context**

**Comment by vigoren** [comment]
Hey I think the issue is that there is a leap year rule enabled. That's the usual culprit in situations like this.

If you check the leap year settings make sure they are set to none of you don't want any leap years.

**Comment by galaara98** [comment]
Ahhh... tis true... Leap Year set to none... all better

**Comment by vigoren** [comment]
Glad that fixed it up for you!
