### ISSUE TITLE
[BUG] Calendar has a nasty habit of popping over other windows

### ISSUE THREAD

**Issue by GambetTV** [vigoren/foundryvtt-simple-calendar#525]
I'm on v11.305 of Foundry, and v2.3.13 of Simple Calendar.

When Simple Calendar is open in Compact View, it has a bad habit of popping up over the top of other windows. It seems to do this when I hit any key on the keyboard, regardless of the scenario. If I hit F12 to open the console, if I type in the chat room, if I use WASD to move a token, it'll pop out in front of whatever window it's beneath. When not in compact view, it does not do this.

**Comment by vigoren** [comment]
This has been fixed in version 2.3.16!
