### ISSUE TITLE
[BUG] PF1 Weather panel repeatedly showing a glitchy closing animation

### ISSUE THREAD

**Issue by ProfBashington** [vigoren/foundryvtt-simple-calendar#526]
**Describe the bug**
If you have opened the panel and leave it open, then select any other day on the calendar to view notes, change the active day etc, that the panel will continually show the closing animation on each new day you select until you open and close it.

**To Reproduce**
1. Open the PF1 Weather sliding panel.
2. Leave the panel open and click around to any different days.

**Expected behavior**
As the panel closes automatically if you select a different day or every time you press on button on the panel, you would expect for the panel to stay closed once closed.

**Screenshots**

**Foundry Information**
 - Foundry Version: 11 Stable.  306 
 - Game System: pf1 9.1
 - Simple Calendar Version: 2.3.13
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
 - Browser- Core Server App for Windows.

**Additional context**

**Comment by vigoren** [comment]
This has been fixed in version 2.3.16!
