### ISSUE TITLE
[BUG] Turns advances rounds for buffs while SC is active

### ISSUE THREAD

**Issue by Hevkalol** [vigoren/foundryvtt-simple-calendar#528]
**Describe the bug**
Simple calendar working weirdly with new Pf1e version (v9.2) it is skipping rounds for buffs every time i hit next in combat.

**To Reproduce**
1. Make combat with few NPc/PCS ,while any of them posses buff with duration.
2. Start battle and skips few turns
3. Check the buff

https://github.com/vigoren/foundryvtt-simple-calendar/assets/131466739/b01b0512-87fd-4b33-b56a-0c0d28fd05e8

**Expected behavior**
Rounds for buffs should advance only then that person turn is started

**Foundry Information**
 - Foundry Version: [10.291]
 - Game System: [Pf1e v9.2]
 - Simple Calendar Version: [2.3.16]
 - Simple Calendar Configuration: [default with golarion calendar ]

**Comment by vigoren** [comment]
This should be fixed in version 2.3.20!
