### ISSUE TITLE
[BUG] Outputting Calendar timestamp to chat only works for GM messages

### ISSUE THREAD

**Issue by GambetTV** [vigoren/foundryvtt-simple-calendar#531]
When "Use Game Time for Chat Message Timestamps" is turned on, it seems to only work when the GM posts a message. When a player does, it goes back to the default timestamp of "1m ago" or whatever. I'm not sure when this bug was introduced, but I do know at a certain point my players were typing a message to chat to see what time it was, lol, so it must be somewhat recent.

I'm on v11.306 of Foundry if that helps, and the most recent version of Simple Calendar (2.3.20), although this issue goes back at least a week, and I want to say maybe even two weeks or longer, though I'm not 100% sure about that.

**Comment by vigoren** [comment]
This has been fixed in version 2.4.0
