### ISSUE TITLE
Adding a second date line that doesn't line up with calender or time (pf2e system; don't know what the other line is from)[BUG] 

### ISSUE THREAD

**Issue by fishrobe** [vigoren/foundryvtt-simple-calendar#534]
**Describe the bug**
In chat timestamps, a second date line is added that doesn't match the PF2e system or the in-game clock.

**To Reproduce**
Make any roll with world time timestamps on (pf2e; haven't checked in other systems). This also happens when it is set to only post real-time--it uses the mystery time instead. I used Find the Culprit to confirm this is coming from Simple Calendar and not another module. Time for odd date is real-time. I don't know where the month/year are coming from.

**Expected behavior**
Expect to only have in-game time, or real-time. 

**Screenshots**

**Foundry Information**
 - Foundry Version: v11 b307 
 - Game System: [e.g. pf2e]
 - Simple Calendar Version: 2.3.20
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]
![weird date](https://github.com/vigoren/foundryvtt-simple-calendar/assets/50474856/87e75d21-7f4b-4c83-bd50-2342e9e03381)

**Browser (please complete the following information):**
 - Browser Vivaldi

**Additional context**
I'm using the Forge, though I don't think that would be an issue, thought I'd add it.

**Comment by vigoren** [comment]
Do you have the module DF Chat Enhancements?

If so it has an option to add chat message timestamps as well. I would check to see if that is enabled.

**Comment by fishrobe** [comment]
I do, but when I turn it off, I only get the "2967 Kut" time, and Golarion time is gone entirely.

**Comment by fishrobe** [comment]
If I disable Simple Calendar timestamps, it works ok, if the DF Enhancements box to use Simple Calendar is checked. I still don't know where the dates are coming from if they're both selected, but at least that fixed it. Thanks!

**Comment by fishrobe** [comment]
Just dubble checked and even with DF completely disabled, I am only getting the weird date/time from SC.

**Comment by fishrobe** [comment]
Thanks. I don't even have that button shown to switch calendars, so I assume I only have one, since that's how I set it up.

I'm not too worried about it. Just thought it was a neat feature, but I just turned it off for now, and turned off DF, too, since it's outdated and stopped playing nice with the most recent version of v11. (308)
![calendar](https://github.com/vigoren/foundryvtt-simple-calendar/assets/50474856/7f313d70-c2f8-4818-9dcd-8ec56d2f877e)

**Comment by fishrobe** [comment]
I can share my configuration with you anyway, so yoiiu can check it out. Not sure how to get it to you, though.

**Comment by fishrobe** [comment]
I tried in GitHub but it didn't like the JSON file. I'll try something
again in a bit. Thanks!

**Comment by vigoren** [comment]
There was an issue with how timestamps were generated in PF2E. Version 2.4.0 of SC will fix this issue.
