### ISSUE TITLE
[BUG] Can't advance game time. Get message saying there is an active combat running. Please resolve them before starting the real time clock. But there isn't any combat running on any scene

### ISSUE THREAD

**Issue by Vornmegil** [vigoren/foundryvtt-simple-calendar#537]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Foundry Information**
 - Foundry Version: [e.g. 0.8.4]
 - Game System: [e.g. DnD5e]
 - Simple Calendar Version: [eg 2.0.4]
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**

**Additional context**

**Comment by vigoren** [comment]
The reason this message will appear depends on what you have set for the setting "Pause Real Time Clock on Combat Rule".

This setting can be found in Simple Calendars configuration window under Global Configuration -> Settings. It has 2 settings

**Pause Only on the Active Scene** 
The real time clock will only pause for combats that are running on the active scene (indicated with a target icon in the scene list).
If this setting is set then check which scene is active and if there is a combat running on that scene.

**Pause on the Scene the GM is Currently Viewing**
The real time clock will pause only if the current scene the primary Gamemaster is viewing has a combat running.
If this setting is set then there would be a combat running on the scene you are currently viewing.

<hr/>

If there are no combats running on the active scene or the scene you are viewing then there could be a stuck combat. I have seen that occasionally combats can not be properly removed so SC thinks they are still running.

You can check this by opening up the developer console (F12) and putting this command in `game.combats.size`. That will show how many combats foundry thinks is running.
If there are combats that shouldn't be there you can run this command `game.combats.forEach(c => {c.delete()})`. Warning is that will delete all combats on all scenes so it is better to wait until you are done with any combats in progress before running that command.

**Comment by Vornmegil** [comment]
Thank you so much for that elegant solution. Working fine now, consider this closed
