### ISSUE TITLE
[BUG] Simple Calendar interrupting Mod: "Speaking As" capabilities

### ISSUE THREAD

**Issue by galaara98** [vigoren/foundryvtt-simple-calendar#542]
**Describe the bug**
When Simple Calendar Mod is enabled, it suppresses the Mod "Speaking As"

**To Reproduce**
Disable all Mods,
Enable Mod "Speaking As" https://github.com/MrVauxs/speaking-as
View Chat, you can see an option that allows you to speak as your player or if you own a token then the token
Enable Simple Calendar Mod (in addition to Speaking As)
View Chat, Speaking As capabilities are gone (if you switch to chat quickly you can watch the functionality start and then be hidden).

**Expected behavior**
Both Mods should be able to coexists.

**Screenshots**

![Expected](https://github.com/vigoren/foundryvtt-simple-calendar/assets/178406/dfefa21a-9322-4dfa-8cad-0ee22b4d60fe)
![SimpleCalendarIssue](https://github.com/vigoren/foundryvtt-simple-calendar/assets/178406/5dbf8b09-3e95-4d12-ba93-fc8405ec0d44)

**Foundry Information**
 - Foundry Version: Stable 11.308
 - Game System: PF2e 5.5.1
 - Simple Calendar Version: 2.4.0
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
 - Opera - Foundry Server is self hosted node.js

**Additional context**

**Comment by galaara98** [comment]
Started in the last 0-3 days

**Comment by vigoren** [comment]
My guess is that is happening because of the Use Game Time For Chat Message Timestamps setting in SC. Turning that off should allow you too use the other module until I can get a fix out.

**Comment by vigoren** [comment]
I will have a look into it. Thanks for the report!

**Comment by vigoren** [comment]
This should be fixed in version 2.4.3! Sorry about the wait.
