### ISSUE TITLE
[BUG] Impossible 

### ISSUE THREAD

**Issue by McGregor777** [vigoren/foundryvtt-simple-calendar#547]
**Describe the bug**
I am not able to select a range of date for my Note starting from a date of a month and finishing on a date of another month.

**To Reproduce**
1. Create a note.
2. Click on the Note's Date/Hour.
3. Select the starting date of the note.
4. Click on the next month button or the previous month button (the calendar disappear).
5. Click on the Note's Date/Hour again.
6. Select another day.
7. The date range is not correctly taken into account.

**Expected behavior**
Defining a note to be starting from a day of a month to a day of a following month.

**Screenshots**
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/28816687/3787e693-7f45-4895-832f-b6a561a3fb4d)

**Foundry Information**
 - Foundry Version: 11.309
 - Game System: WFRP4e 7.0.2
 - Simple Calendar Version: 2.4.0
 - Simple Calendar Configuration: Using Warhammer Fantasy preset.

**Browser (please complete the following information):**
 - Browser: Foundry 

**Additional context**
I am using Warhammer Fantasy Calendar.

**Comment by vigoren** [comment]
Sorry about the bug, this should be fixed in version 2.4.3
