### ISSUE TITLE
[QUESTION] How to change hotkey

### ISSUE THREAD

**Issue by BrianM56** [vigoren/foundryvtt-simple-calendar#559]
After recently updating, pressing shift+S makes the calendar appear and disappear. Is there a way to change it so it doesn't do this? It makes it rather annoying to change a characters facing/position as calendar overrides it.

**Comment by vigoren** [comment]
There is a configurable key binding that can be set to open up simple calendar. https://simplecalendar.info/docs/using-sc/opening-sc#keybinding

If changing that doesn't solve the issue it could be another module doing it. Could try disabling other modules to see what one might be causing that.

SC doesn't listen for that key combo unless configured to.

**Comment by BrianM56** [comment]
Thank you, somehow it got rebound. Problem solved :)
