### ISSUE TITLE
[BUG] Cannot delete notes

### ISSUE THREAD

**Issue by Nedrapter** [vigoren/foundryvtt-simple-calendar#568]
**Describe the bug**
Cannot delete notes from calendar.

**To Reproduce**
Make a note.
Try to delete it.

**Screenshots**
This error shows up
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/74311190/d14aa715-a449-4088-84af-21e6f1b46223)

**Foundry Information**
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/74311190/a6218300-545b-40db-9435-b71da2be20a0)
module version 2.43

**Browser (please complete the following information):**
Opera

**Comment by vigoren** [comment]
When you open the note does it look like a regular journal entry or is it styled to look like the calendar?

I think the issue might be the journal entry is not using the simple calendar journal sheets. You can check this by clicking the `Sheet` button with a gear icon in the top right of the journal entry when it's open. The dialog that opens will have a drop down for the journal entries sheet (not the default sheet one) where you can select the "Simple Calendar Note" option. If it is set to that then the delete functionality should work.

If you are using the Ferncombe module there is an issue with it that breaks the setting of the right journal entry sheet. Details about that can be seen here https://github.com/foundryvtt/Ferncombe/issues/2

If none of those help a screen shot of the note would help.

**Comment by Nedrapter** [comment]
Ferncombe is the issue indeed. After changing the style the deleting works. It does seem annoying to have the style pre-assigned to Ferncombe's style.

**Comment by vigoren** [comment]
I agree, unfortunately Ferncombe is very aggressive in setting its sheet as the default for all journal entries (which calendar notes are) so it requires an update from that module's developers to fix.

 I did propose a solution but haven't heard anything about it since doing so

**Comment by vigoren** [comment]
Closing this as Ferncomb needs to make a change to fix the issue.
