### ISSUE TITLE
[BUG] Changing Year of existing note does not work

### ISSUE THREAD

**Issue by J0nnyI** [vigoren/foundryvtt-simple-calendar#569]
**Describe the bug**
Changing the year of the date editor for an existing note does not apply the changes.

**To Reproduce**
1. Create a new Calendar note
2. Edit the Note
3. Click on the Date of the Note
4. Change the Date using the Textbox depicting the year
5. Click anywhere else

**Expected behavior**
Either the year should be applied when the Dropdown closes or the month should update on change, so that you can select the desired day of said month

![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/32224734/49a9440c-b3f7-49c8-9474-16911ed9b3a6)

**Foundry Information**
 - Foundry Version: 11 Build 315
 - Game System: dnd53 2.4.0
 - Simple Calendar Version: 2.4.3
 - Simple Calendar Configuration: [simple-calendar-export.json](https://github.com/vigoren/foundryvtt-simple-calendar/files/13707783/simple-calendar-export.json)

**Browser:**
 - Chrome

**Comment by vigoren** [comment]
This has been fixed in version 2.4.8!
