### ISSUE TITLE
[FEATURE] GM Reminders

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#57]
This is related to #22 but maybe more practical, so a bit of an alternative to it.

The ability to set GM Reminders, for marking events as something that must be reminded to the GM when the calendar is marked to that day. For example to remind of caravans coming back to the village, the date the BBEG will kidnap the daughter of one of the players, when a player will show symptoms of a disease, etc.

This is the function and how I imagine it
- when creating a note, there's a GM Reminder checkbox, off by default.
- GM Reminder rows in the event table are slightly GM-colored to identify them as reminders, or even get a tag before or after the text. 
- when a day has one or several GM reminders, in the calendar there's a dark blue circle (to contrast with the ordinary red) with a counter next to the typical event counter. Reminders are counted separately from the normal events and are excluded from the normal events counter.
- when the world's session starts, if the current day has GM reminders, make private posts to the GM to remind him of of the note and its contents, if any. The same posts are posted privately when the calendar is moved to a date with one or several GM reminders.
- GM Reminders may have time. If the user uses Calendar/Wealther widget (I do hope at some time Simple Calendar can produce its own or clone this widget from Calendar/Weather) and Simple Calendar syncs with the time, then post privately in the chat each time the time of the reminder is crossed.

**Comment by vigoren** [comment]
GM reminders are a good idea will look into adding this for sure. Like you said will be in conjunction with #22 as they are somewhat related.
