### ISSUE TITLE
[BUG] Compact View opens in center - position not remembered

### ISSUE THREAD

**Issue by bcmcms** [vigoren/foundryvtt-simple-calendar#570]
**Describe the bug**
When I have 'Open in Compact View' selected, reloading foundry causes the compact view to be placed in the center of the screen, rather than its last placed location. Double-clicking to exit compact view causes the full sized calendar to be placed in the correct location (that is, the last placed location of the full-sized calendar), and returning to compact view causes the compact calendar to be placed where the full-sized calendar just was.

My primary use case for Simple Calendar is sitting on the bottom of the screen in compact view, so being able to start in compact mode helps (as the full sized calendar can't fit at the bottom of the screen and I want it compact anyway), but fixing the position every time is extra work and seems like a bug.

**To Reproduce**
1. Enter the Configure menu for Simple Calendar
2. Ensure 'Open in Compact View' is selected, along with 'Remember Position'.
3. Reload foundry (Using F5 or by restarting the application)
4. The Compact View will appear in the center of the screen on load

**Expected behavior**
Ideally the compact calendar's location should be remembered, in accordance with the enabled "Remember Position" option, just like the full-sized calendar's is at the moment. It would be even better if it was possible for the compact and full sized calendars to have separate stored locations but that may be beyond the scope of the current features. It'd be sufficient for whichever one it is defaulted to open as to be remembered.

**Screenshots**
I can get a screenshot if you need it but it'd just be the compact calendar in the center of the screen

**Foundry Information**
 - Foundry Version: Release 11.315
 - Game System: DnD5e v2.4.1
 - Simple Calendar Version: 2.4.3

 - Simple Calendar Configuration: [simple-calendar-export.json](https://github.com/vigoren/foundryvtt-simple-calendar/files/13755218/simple-calendar-export.json)

**Browser (please complete the following information):**
 - Foundry's custom hosting client for 11.315

**Comment by vigoren** [comment]
Sorry for the late reply.

Do you have the "Remember Compact Position" option selected?

The main application and the compact view version can have separate positions remembered. Some users like to tuck the compact view in a corner for easy checking time then have the main app appear somewhere else for easy working with the calendar then when they are done have the compact view go back to where it was.

**Comment by bcmcms** [comment]
That fixes it. Somehow I missed that option when I was initially scouring the menu. Sorry about that!
