### ISSUE TITLE
[BUG] Console Error PF2e v5.12.1 - Hero Point Re-Roll

### ISSUE THREAD

**Issue by ottyn** [vigoren/foundryvtt-simple-calendar#572]
**Describe the bug**
Error in console when re-rolling with a Hero Point from the chat card on PF2e v5.12.1

**To Reproduce**
1. Make an attack roll that misses
2. Right click on chat card and select "Re-roll with Hero Point"

**Expected behavior**
Error doesn't appear to effect anything in game, but does produce a fairly lengthy error message in console.  Chat card does update with the new roll and you can then roll damage as normal.

**Screenshots**
Log file of error attached as it would not fit into a screenshot.

[error.log](https://github.com/vigoren/foundryvtt-simple-calendar/files/13854837/error.log)

**Foundry Information**
 - Foundry Version: 11.315
 - Game System: PF2e v5.12.1
 - Simple Calendar Version: 2.4.3

**Browser (please complete the following information):**
 - Browser: Chrome

**Additional context**

**Comment by vigoren** [comment]
Hey this seems it may have been an issue with the PF2E system itself. I tried it in the most recent version 5.13.1 and I can reproduce the error.

I did notice that in the update for 5.12.3 there was a fix related to chat cards that may have been related to the issue you are seeing.
- (stwlam) Fix rendering of notes in rerolled check messages

If you are able to I would try updating and see if that resolves this issue. If not please let me know!

**Comment by vigoren** [comment]
Closing as this appears to be fixed by the above change to the PF2E system
