### ISSUE TITLE
[BUG] Issue with notes

### ISSUE THREAD

**Issue by MartinaSide** [vigoren/foundryvtt-simple-calendar#578]
**Describe the bug**
Changing the "Note Repeats" options resets the fields for "Note categories" and "Who can view" to default.

**To Reproduce**
1. Go to New Note
3. Set Who Can View to something that is different from default
4. Set Note Categories to something that is different from default
6. Set Note Repeats to another option
7. Bug encountered

**Expected behavior**
Note Categories and Who Can View unchanged

**Foundry Information**
 - Foundry Version: Version 11 Stable 315
 - Game System: DnD5e
 - Simple Calendar Version: 2.4.3
 - Simple Calendar Configuration: Forgotten Realms

**Browser (please complete the following information):**
 - Browser edge, chrome

**Additional context**
NA

**Comment by vigoren** [comment]
This has been fixed in version 2.4.8!
