### ISSUE TITLE
[BUG] Custom Months with days of 20 and less show up as days of 31

### ISSUE THREAD

**Issue by TheSteadyEddy** [vigoren/foundryvtt-simple-calendar#581]
**Describe the bug**
When creating a month that has 20 days or less in it, the month is shown as 31 days in the Calendar.

**To Reproduce**
Create a custom month with a number of days of 20 or less.

**Expected behavior**
I feel that the Simple calendar should display a month with 20 days properly?

**Screenshots**
![Screenshot_1](https://github.com/vigoren/foundryvtt-simple-calendar/assets/161659716/a38dae7b-111a-4da4-85f9-2146300d6497)

**Foundry Information**
 - Foundry Version: 11 patch 13
 - Game System: PF2E
 - Simple Calendar Version: eg 2.4.3
 - Simple Calendar Configuration: 5 day weeks, months with mostly 20 days, 22 months in a year.

**Browser (please complete the following information):**
 - Browser CHrome

**Additional context**

**Comment by vigoren** [comment]
My guess is that the leap year rules are enabled and that it is a leap year. Under the leap year rules you can set the number of days a month has in a leap year or disable leap years all together.

**Comment by TheSteadyEddy** [comment]
Thank you! That was the issue, seems to be fixed after disabling leap years :)
