### ISSUE TITLE
[BUG] infinite loops in d35e system

### ISSUE THREAD

**Issue by psedonatural** [vigoren/foundryvtt-simple-calendar#582]
**Describe the bug**
Infinite loop with attack rolls in system D35E and causes stackoverflow.
WIth default d35e system, it throws an error  reaches maximum 3 stacks:
        RangeError: Error thrown in hooked function 'createChatMessage' for hook 'preCreateChatMessage'. Maximum call stack size exceeded

 If libWrapper is enabled, there is no maximum stacks restriction and the infinite loop may lead to a crash.

**To Reproduce**
1. With D35E system, only simple calendar enabled.
2. open an actor card and give him a weapon
3. open(edit) the weapon item card and click on the "create attack" on the title bar.
4. back to the actor card, summary tab, use the attack action that you just created.
5. check the error

**Expected behavior**
native D35E attack rolls.

**Screenshots**
with no other mods
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/86414628/a216cef9-dd15-430e-9659-ac7be63937bc)
with libWrapper enabled
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/86414628/460e3a94-c4c5-4109-bebb-537cf23fd4a3)

**Foundry Information**
 - Foundry Version: [v11.315] up2date
 - Game System: [3.5E SRD v2.4.3] up2date
 - Simple Calendar Version: [2.4.3] up2date
 - Simple Calendar Configuration: [default]

**Browser (please complete the following information):**
 - Browser [chrome]

**Additional context**

**Comment by vigoren** [comment]
This has been fixed in version 2.4.8!
