### ISSUE TITLE
[BUG] Simple Calendar Causes Chat Permission Errors

### ISSUE THREAD

**Issue by claycle** [vigoren/foundryvtt-simple-calendar#586]
**Describe the bug**
When the calendar mod is enabled, some players see the following error message when other players type in chat:

![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/419840/fc139413-580c-4924-95ce-8b9a55ac7376)

Additionally, the chat cards do not scroll fully up off the bottom of the chat frame.

**To Reproduce**
1. Enable the mod
2. Have a player type a message
3. Other player gets the error.

**Expected behavior**
No error should occur.

**Foundry Information**
Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: rqg, 3.4.2
Active Modules: 25
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
GPU: ANGLE (ATI Technologies Inc., AMD Radeon Pro Vega 64 OpenGL Engine, OpenGL 4.1)
Max Texture Size: 16384

Scene: 4512 x 2632 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 9 | Tokens: 5

Actors: 35 | Items: 16 | Journal Entries: 183 | Rollable Tables: 0 |
Playlists: 7 | Compendium Packs: 83 | Chat Messages: 379

SYSTEM: RuneQuest Glorantha 3.4.2

CALENDER VERSION: 2.4.8

BROWSER: Edge, Firefox

**Comment by vigoren** [comment]
Please update to version 2.4.9 that should address the issue.
