### ISSUE TITLE
[BUG] Logically, the current day save button should be part of the current day control frame. 

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#59]
This is very minor, but it bugs me that a button to save current day is located outside of the frame containing its settings. 

![image](https://user-images.githubusercontent.com/4083812/113762814-a998a400-9721-11eb-96cf-ab18a15d5703.png)

**Comment by vigoren** [comment]
Makes sense, I have merged the button with the date control box so it is more cohesive looking.
