### ISSUE TITLE
[BUG] Persistent Open setting makes it impossible to deselect objects on the canvas or open the ESC menu

### ISSUE THREAD

**Issue by mclemente** [vigoren/foundryvtt-simple-calendar#592]
**Describe the bug**
Persistent Open setting makes it so pressing ESC won't deselect tokens or open the ESC menu.

Is there any way to make it so that this doesn't happen?

I think the "simplest" fix is to copy Cases 4 and 5 of `ClientKeybindings._onDismiss` into the `close` method with an `if (Object.keys(ui.windows).length === 1)` to guarantee it is the only other application open so it doesn't conflict with anything else.

The alternative would be to call `delete ui.windows[this.appId]` when rendering itself, but I have no idea what underlying issues would come with this.

**To Reproduce**
1. Set Persistent Open on.
2. Press ESC with no other windows open while selecting a token.

**Expected behavior**
Placeable objects (tokens, tiles, drawings) to be deselect or the menu to open.

**Comment by vigoren** [comment]
This doesn't appear to be an issue in foundry  version 12, but I have put out a fix that will address this issue in foundry version 10 and 11.
