### ISSUE TITLE
[BUG] Issue with multiple day events

### ISSUE THREAD

**Issue by Issacar13** [vigoren/foundryvtt-simple-calendar#603]
**Describe the bug**
Trying to add a 2 weeks festival to the calendar that overlap 2 months (ie.: 25 april to 05 february). It won't allow it to establish itself, the ending day will show 00, NaN

**To Reproduce**
1. add an event
2. Try to make the note date/time overlap 2 months

**Expected behavior**
being able to establish an event with a starting date in one month and the ending date in a different month.

**Screenshots**
![image](https://github.com/vigoren/foundryvtt-simple-calendar/assets/168503811/7db45bc0-b146-4b4a-b2ed-5a991f165f5e)

**Foundry Information**
 - Foundry Version: [e.g. 11.315]
 - Game System: [e.g. FP2e]
 - Simple Calendar Version: [eg 2.4.13]
 - Simple Calendar Configuration: [optional, can help in debugging custom calendars]

**Browser (please complete the following information):**
 - Edge
 -
**Additional context**

**Comment by vigoren** [comment]
This has been fixed in  version 2.4.17!
