### ISSUE TITLE
The ability to change the time from 24 hour time to AM and PM.

### ISSUE THREAD

**Issue by sevrick** [vigoren/foundryvtt-simple-calendar#605]
From what I have seen there isn't a way to change the time to a standard am and pm instead of the 24 hour time.

It would be great to have that, since I don't really think of time in that way.

I could be wrong and just not seeing the settings for it.

**Comment by vigoren** [comment]
Simple Calendar offers a very customizable way to change how the time and date are displayed, all details on how you can customize the display can be found here.

For a quick setting to a 12-hour clock though you can follow these steps:

- Open up the Simple Calendar configuration window.
- Navigate to the calendar's "Display Options" settings.
- In the field called "Time Format" replace with this `hh:mm:ss A`.
- Save the configuration, now the clock will be displayed in a 12-hour format!

**Comment by sevrick** [comment]
thx
