### ISSUE TITLE
Change Weekday position [FEATURE] 

### ISSUE THREAD

**Issue by fabiocmg** [vigoren/foundryvtt-simple-calendar#61]
The calendar lacks a way to change a weekday position in the week. In Fantasy Calendar, for example, this is solved by informing the first weekday of the first year (usually year 0). That works fine, but any adjustment made to the weekday position would do fine.

I suggesting this because I'm having problems to set the current weekday in my calendar. I'm work around this, but or with wrong weekdays compared to the official calendar (the days of the week don't match that of the official calendar), or I have  the calendar widget to show up the weekday in a different position in the week (for example, sunday appearing as the fourth day, not as the first).

**Comment by vigoren** [comment]
Good suggestion. I have added this as a configuration option and updated some of the predefined calendars to set this offset so everything falls on the correct day of the week.

I am just finishing up a few other things but a release with this feature should be out later this week.

**Comment by vigoren** [comment]
This feature has been added in the latest release.
