### ISSUE TITLE
Reported error in Foundryvtt

### ISSUE THREAD

**Issue by Thanatos0042** [vigoren/foundryvtt-simple-calendar#616]
The "Simple Calendar" module's manifest contained the following unknown keys: "manifestPlusVersion"

I don't know if it's an issue or not, as I don't know programming, but I thought it best to at least report it.

Foundtryvtt version 12 build 327

**Comment by Thanatos0042** [comment]
never-mind, it went away after I said something.

**Comment by SirBedwyr** [comment]
On current version of Foundry (12.331) and simple calendar (2.4.18) I am now getting this error: The "Simple Calendar" module's manifest contained the following unknown keys: "manifestPlusVersion"
