### ISSUE TITLE
[BUG] Always thinks that combat is enabled

### ISSUE THREAD

**Issue by scooper4711** [vigoren/foundryvtt-simple-calendar#65]
**Describe the bug**
Unable to start time controls. Error message "There is an active combat" appears although there is no active combat.

**To Reproduce**
I have disabled all modules except for Tidy UI and Simple Calendar. The time settings/calendar was originally imported from Calendar/Weather
1. Go to the calendar
2. Click on the play button to start time
3. See error

**Expected behavior**
Time starts passing.

**Browser (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Browser Version: 90

**Additional context**
Note that I created a new world (I use the HarnMaster 3 system) and there it works as expected, however I'm using the default calendar in this case.

**Comment by vigoren** [comment]
This message can appear if any scene has an active combat running. So the first thing I would check is to see if there is any scene in the world has an active combat.

This behaviour happens because advancing combat rounds actually changes the foundry game time and running a real world clock in to of that would advance the time too much.

**Comment by scooper4711** [comment]
I wasn't aware that combat was per scene. Thanks for pointing that out. I finally found the scene which had an active combat.

Suggestion: Either limit your check to the currently active scene, or perhaps in the error message mention which scene has an active combat so the GM doesn't have to hunt.

**Comment by vigoren** [comment]
Yeah those are good points I will look into limiting it to the currently active scene or at the very least mention which scene it is.
