### ISSUE TITLE
[BUG] Lost calendar notes between sessions

### ISSUE THREAD

**Issue by benbarbour** [vigoren/foundryvtt-simple-calendar#66]
**Describe the bug**
Lost all notes / entries.

**To Reproduce**
I did an "update all" on my modules this morning. Not sure if it's related. I added the notes almost a week ago, ran one session where I don't think I opened the Calendar, and then tried opening it just now.

**Expected behavior**
My notes persisted and retrievable.

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: 87

**Additional context**
I'm getting an error when playing around with the calendar right now:

```
Simple Calendar  | Day is missing data attribute! index.js:1:311
    error https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    dayClick https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    jQuery 8
    activateListeners https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    _render https://foundry.bbarbour.com/scripts/foundry.js:4537
    render https://foundry.bbarbour.com/scripts/foundry.js:4479
    updateApp https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    dayClick https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    jQuery 8
    activateListeners https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    _render https://foundry.bbarbour.com/scripts/foundry.js:4537
    render https://foundry.bbarbour.com/scripts/foundry.js:4479
    updateApp https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    loadNotes https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    _update https://foundry.bbarbour.com/scripts/foundry.js:3499
    set https://foundry.bbarbour.com/scripts/foundry.js:3481
    SaveNotes https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    saveButtonClick https://foundry.bbarbour.com/modules/foundryvtt-simple-calendar/index.js:1
    jQuery 4

​
```

**Comment by vigoren** [comment]
I'm sorry that this happened.

This is the first time I have heard of this happening. There isn't anything in the module itself that would cause this to happen so maybe something in the update all that caused it.

Did other modules lose any settings or have there settings reset?

**Comment by benbarbour** [comment]
Not to my knowledge. I'll keep experimenting. I think I have a backup copy of the world I can pull them out of. If you could point me towards where they are stored in foundry maybe I can write a little macro or console lines to export / import them.

**Comment by vigoren** [comment]
For sure, glad you had a backup. They are in the world's settings database under the key foundryvtt-simple-calendar.notes


From my experience updating didn't change theses settings at all.

There was no errors in the console?

**Comment by benbarbour** [comment]
None but the one mentioned in the bug description

**Comment by vigoren** [comment]
That one isn't a big big. It happens if you click on a non icon or note count for a day, errors when trying to select the day. I have a fix for that coming.

So it's unrelated to this issue specifically.

**Comment by benbarbour** [comment]
Oh weird; they are all still there! However "today" is ~40 years later than I filed them! No idea how that happened! I guess I'll file another issue if it happens again. Thanks for your help and a great module!

Maybe a player did it. -.-

**Comment by vigoren** [comment]
Oh strange but glad you found them! And glad you are enjoying the module 😁
