### ISSUE TITLE
[FEATURE] Limit check for active combat to the currently active scene

### ISSUE THREAD

**Issue by scooper4711** [vigoren/foundryvtt-simple-calendar#67]
**Is your feature request related to a problem? Please describe.**
When trying to activate the clock, it's frustrating and unclear to the user when a non-active scene has combat active and this prevents the user from starting the clock.

**Describe the solution you'd like**
When checking if there is active combat before allowing the user to start the clock, only check the currently active scene has active combat. 

**Additional context**
Failing that, at least tell the user which scene still has active combat so that it's easier to find and close.

**Comment by vigoren** [comment]
I have limited the combat check to the active scene. This is apart of the 1.2.30 release
