### ISSUE TITLE
[FEATURE] Compact view

### ISSUE THREAD

**Issue by scooper4711** [vigoren/foundryvtt-simple-calendar#68]
**Is your feature request related to a problem? Please describe.**
The full calendar UI is fantastic, but it does take up a lot of screen real-estate.

**Describe the solution you'd like**
Create a minimal UI that the user can switch to which perhaps only displays one week at a time and has a more compact UI for displaying/controling time. The compact UI of Calendar/Weather is a nice example of a very compact UI which isn't intrusive if it's always open.
Perhaps you can hook into the control for double-clicking on the title bar and display the minimal UI then. That would be cool.

**Describe alternatives you've considered**
I was using Calendar/Weather but your support for notes/repeating events is far superior and has sold me. However, I need to minimize the UI.

**Additional context**

**Comment by vigoren** [comment]
I have added a compact view for the calendar.
By double clicking on the header instead of minimizing it will shrink to the compact view. Double clicking again will restore it to the full version.
This was release in v1.2.30

**Comment by scooper4711** [comment]
Wow! That was fast! Thanks for turning this (and my other feature requests) around so quickly!
