### ISSUE TITLE
[BUG] The green "set current date" button doesn't

### ISSUE THREAD

**Issue by scooper4711** [vigoren/foundryvtt-simple-calendar#69]
**Describe the bug**
The "set current date" button doesn't set the current date.

**To Reproduce**
1. Select a date other than the current date
2. Click on 'set current date'
3. Notice that nothing happens, no error in the log

**Expected behavior**
It would change the current date to the currently highlighted date. Or perhaps pop up a dialog asking if you want to set the current date.

**Browser (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Browser 90

**Additional context**

**Comment by vigoren** [comment]
This wasn't a bug per say. In stead it was confirming your changes to the current date. Moving the current date forward would not save it until this button was selected.

I realize that is not very intuitive at all so I have changed the behaviour. Now advancing the day/month/year does not require the save current date button to be click to be saved properly.

When day is selected the save current date button will appear, clicking it will set the currently selected day as the current day. A notification will appear if the selected day is not currently visible (such as selecting a day then changing the month being viewed) to try a limit accidentally setting the dat to something unintentional. 

Overall I think this is a great improvement over the current setup.
This was release as part of the v1.2.30 release
