### ISSUE TITLE
[FEATURE] Quick Access Calendar Notes

### ISSUE THREAD

**Issue by SabreRunner** [vigoren/foundryvtt-simple-calendar#73]
I wish there would be a way to find notes quickly instead of looking back in the calendar for something specific. Hopefully, in a way that Quick Insert can access.

**Comment by vigoren** [comment]
I think this will kind of tie into the option I am looking at for saving notes as journal entries (which should then be searchable by Quick Insert as well as issue #79 to add searching to the calendar interface
