### ISSUE TITLE
[FEATURE] Random Day Generation

### ISSUE THREAD

**Issue by Greysion** [vigoren/foundryvtt-simple-calendar#74]
Hello!

I was hoping it might be a possible consideration to expand the macro to generate a random date within a created calendar.

It would definitely make picking random dates a little easier, given a start and end query, especially for creating events on a random chain.

Thank you once again for your awesome mod. :)

**Comment by vigoren** [comment]
Something like this should be doable as a macro

**Comment by vigoren** [comment]
This has been added in version 1.2.73, be sure to check out the [documentation ](https://github.com/vigoren/foundryvtt-simple-calendar/blob/main/docs/API.md#simplecalendarapichooserandomdatestartdate-enddate) on how it works!
