### ISSUE TITLE
[BUG] Sync between about time and simple calendar

### ISSUE THREAD

**Issue by winterwulf** [vigoren/foundryvtt-simple-calendar#75]
Hi :)

Whenever I move time forward from Simple Calendar, the time syncs as expected in the About Time/Weather Calendar clock.

When I try the opposte though (to move time forward from the weather calendar window) the time advances 21 years plus some days and months in the Simple Calendar.

I've experienced this using Game World Time Integration options: Mixed; and also with: Third Party.

**Comment by vigoren** [comment]
Hey I found an issue that I think was the cause of your issue and have released a fix in the most recent update (v1.2.34). Please update to that and let me know if the issue keeps occurring.

Thanks
