### ISSUE TITLE
[FEATURE] Search date / Notes

### ISSUE THREAD

**Issue by zcClarkE** [vigoren/foundryvtt-simple-calendar#79]
Simple Calendar is a great way to keep track of important dates in a world, but it lacks a search tool for player and GM to go forward or backward in time in an instant, which is a notable issue when a campaign has events taking place over hundreds of years.

It might be useful as a step further to also be able to search dates through typing in titles of notes a date has, but this feature is likely more complex.

**Comment by vigoren** [comment]
I agree that a search function is needed. Will look at adding one in the next version.

**Comment by vigoren** [comment]
A simple search feature has been added in version 1.3.66!
