### ISSUE TITLE
[BUG] Custom Leap Years Not Working

### ISSUE THREAD

**Issue by Bolt7** [vigoren/foundryvtt-simple-calendar#80]
**Describe the bug**
Custom leap years don't work because it's impossible to enter a number for When Leap Years Happen.

**To Reproduce**
1. Go to Leap Year Settings
2. Select Custom for Leap Year Rule
3. Click on When Leap Years Happen
4. Enter a number other than 0
5. Click away or press enter
6. See that it reverts to 0

**Expected behavior**
It should keep the number that you put in and use the modified day/month settings for years that are a multiple of that number.

**Screenshots**
![image](https://user-images.githubusercontent.com/75871317/116731017-32b89900-a9b7-11eb-9cd8-4329e3b7f9b7.png)

**Comment by vigoren** [comment]
Opps how embarrassing.

Will have a fix for this rolled out shortly.

**Comment by vigoren** [comment]
v1.2.35 has a fix for this.

Sorry about the issue.
