### ISSUE TITLE
[FEATURE] Start Month on 1st weekday

### ISSUE THREAD

**Issue by Bolt7** [vigoren/foundryvtt-simple-calendar#82]
A feature that makes months start on the first weekday would be great. This would be useful to stop the weekdays from drifiting in custom calendars with year lengths that aren't multiples of the week length.

For future proofing being able to choose the weekday that a month starts on might be better, but starting on the 1st weekday is all I need.

**Comment by vigoren** [comment]
This is something I can add under each months advanced settings. A dropdown where you can specify which day of the week a month starts on (or the default, which is calculated out)

**Comment by Bolt7** [comment]
That would be perfect.

**Comment by vigoren** [comment]
This has been added in v1.2.47!
