### ISSUE TITLE
[BUG] Can't select intercalary month as Season Starting Month or New Moon Month

### ISSUE THREAD

**Issue by tototonis** [vigoren/foundryvtt-simple-calendar#83]
**Describe the bug**
Can't select a different intercalary month as the start of a season or new moon. Always defaults to the last intercalary month of the year.

**To Reproduce**
1. Create a calendar with multiple intercalary months
2. Add new season or moon
3. Try to set Season Starting Month or New Moon Month as different intercalary months

**Expected behavior**
I'd like to set intercalary days (months with number of days = 1) for the start of each season in my custom calendar.

**Comment by vigoren** [comment]
Sorry you ran into this bug.

I will get this fixed.

**Comment by vigoren** [comment]
This issue has been fixed in v1.2.38. Please let me know if you run into any more!
