### ISSUE TITLE
[FEATURE] Event tooltip on calendar

### ISSUE THREAD

**Issue by fabiocmg** [vigoren/foundryvtt-simple-calendar#84]
I suggest a feature that allows you to see a tooltip with the names of the events when you hover the mouse on the day on the calendar that have an event. Now we have to click on the day to see it.

**Comment by vigoren** [comment]
I can do more advanced tool tips, though I think I will have to limit it to the first 2-3 event names rather than all. Just incase someone has loads of events on one date and not spawning a giant tool tip as a result.

**Comment by fabiocmg** [comment]
Good!

**Comment by vigoren** [comment]
This has been added in v1.2.38!
