### ISSUE TITLE
[FEATURE] setting to allow trusted player(s) to change the calendar date.

### ISSUE THREAD

**Issue by vigoren** [vigoren/foundryvtt-simple-calendar#86]
Look into allowing the DM to set the permission level (example a player set to trusted), or a specific player, who can set the date on the calendar.

This way the DM can allocate time tracking duties to someone else they trust.

**Comment by jasonckramer** [comment]
I would like to see Trusted players able to change the Time as well, as part of their time tracking duties.

**Comment by vigoren** [comment]
The allowing users in different roles to change the date has been added in v1.2.55
