### ISSUE TITLE
[FEATURE] Support for modified sunrise/sunset

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#87]
Mainly used for fantasy worlds or specific locations (i.e. tundra in Icewind Dale, where sunrise is 10am and sunset is 2pm)

The ability to apply to seasons a custom sunrise and sunset time, with smooth changes each day depending on whether the day is positioned between two seasons each with different peak sunrise/sunset.

**Comment by MapperD** [comment]
Latitude adjustments to the sunrise and sunset would be cool to go along with changing sunrise/sunset based on the day of the year.

**Comment by vigoren** [comment]
You can now specify a sunrise/sunset time for the first day of each season. Sunrise and sunset times slowly change as days progress to meet the sunrise/sunset time of the next season. This is to add a smooth transition between seasons sunrise and sunset times.

I did not add the latitude adjustments to this as that is a more complicated task (not all calendars are on worlds of similar size to that of earth) so I have left those times to be adjusted as needed.
