### ISSUE TITLE
[FEATURE] Force Mode to import full calendar in AboutTime instead only changes

### ISSUE THREAD

**Issue by apoapostolov** [vigoren/foundryvtt-simple-calendar#88]
Users who have desync between SimpleCalendar and AboutTime may not know that they have to push Import to AboutTime button buried in the bottom of the Settings dialog. A force mode that detects such desyncs and does a full import anytime there is a desync would help avoid issues, esp with other mods that use Calendar (such as SmallTime).

**Comment by Maghawk** [comment]
I am using this button and the calendars are still out of sync 🤷

**Comment by vigoren** [comment]
@Maghawk did you try updating to the most recent version 1.2.38 and follow the steps in the release notes?

There was an out of sync issue that was fixed in that release.

**Comment by Maghawk** [comment]
I think we probably just talked about and maybe identified the problem on discord. If so, hi!

**Comment by apoapostolov** [comment]
The last version and the three-step fix fixes the data in AboutTime until the next restart of the world. The issue continues to happen.

**Comment by apoapostolov** [comment]
One way this can be avoided if SimpleCalendar pushes to AboutTime every time the world is loaded.

**Comment by vigoren** [comment]
I have been playing around with the about time integration a lot trying to iron out bugs.

I haven't noticed it being reset at all during world restarts. 

Could another module be changing about times settings on world restarts?

My testing was done with Simple Calendar, about time and small time modules enabled.

As I'm writing this, wondering if it could be calendar/weather making the change. Is that a module you have enabled?

**Comment by Eonfuzz** [comment]
Hey so we're currently exporting SimpleCalendar to AboutTime and AboutTime is getting sync'd to one month earlier than the time we've set.

Any ideas?

**Comment by apoapostolov** [comment]
My only suggestion would be to force the proper date/tme upon world load (optional, in case someone doesn't want this).

**Comment by vigoren** [comment]
@Eonfuzz 

There currently is an issue between the newest version of about time and Simple Calendar that is causing this.

I'll be putting an update or tomorrow that will fix this issue.

**Comment by Eonfuzz** [comment]
@vigoren you're a legend. Thanks mate

**Comment by venom986** [comment]
This does not seem to be resolved for me in the version that was released yesterday. I'm on about-time 0.8.4 and simplecalendar  release from yesterday.

I'm wondering if the fact that about-time uses a zero index for months is the actual issue? I'm trying to set my current date to 1 Kythorn 1491 DR. If I set that in SimpleCalendar I get 1 Greengrass in about-time which represents this as 06/01/1491. To get 1 Kythorn in about-time I have to set about-time directly to 08/01/1491 (but then SimpleCalendar's date shows something like 24 Kythorn...).

**Comment by venom986** [comment]
I have another world though where the date is 30 Hammer 1493 DR and things seem perfectly in synch there.

**Comment by vigoren** [comment]
@venom986 for the world that isn't synced did you export the simple calendar settings into about time after the update? The difference in time you are seeing sounds consistent with needing to re export.

**Comment by venom986** [comment]
@vigoren I did. Would it make a difference that the game was paused when I did the export? Would that have prevented an update to game time?

**Comment by vigoren** [comment]
@venom986 game being paused shouldn't affect the export at all.

Is there a difference in active modules between the two worlds and could one be maybe interfering?

Otherwise there could be a bug. In all my testing about time and Simple calendar stay synced together so to help track the bug down it would help to have your calendars configuration settings. The current quickest way to give me that is to send me the affected worlds settings.db file (nothing sensitive is stored in there) or if you don't wish to do that (totally understandable) can tell me the settings you are using.

**Comment by venom986** [comment]
The one difference off the bat is that Simple Calendar, About Time, and SmallTime were all enabled on first launching the world that still doesn't work (post update), whereas About Time was disabled on first launching the world that does work. 

The other thing is 1491 DR is before a leap year and 1493 is after. This is the Harptos calendar. 

I'm about to go log in and can do some testing and send config.

**Comment by venom986** [comment]
grumble. grumble. grumble.

Have you tried turning it off and on again?

/facepalm

So, although I had confirmed i had the functionality from the new release of Simple Calendar, I had NOT restarted my world after exporting Simple Calendar to About Time. Now that I have cycled the world it seems everything is synched nicely.

**Comment by vigoren** [comment]
@venom986 glad it's working for you! 

Though you shouldn't have needed to restart the world but at least that is an easy way to get them synced up again.

**Comment by venom986** [comment]
@vigoren yeah not sure why.

As an FYI if you don't follow it, the other module I'm using (SmallTime) has an issue open about this ~ 1 month discrepancy as well. Tim Posney (author of About-Time) was posting there indicating he was aware he'd introduced a bug in the last version of About-Time in that it interprets a string of 0/0/000 00:00:00:000 incorrectly in his new time offset field. Maybe related to what you had to fix on your end?

**Comment by vigoren** [comment]
It is related, my work around for now is when exporting i set the time offset field to be an empty string instead of 0/0/0 00:00:00 which skips the code in about time that introduces bug.

My doing this should also fix small time for people who use all three modules 

When he fixes his bug I'll make sure things keep working with simple calendar.

**Comment by vigoren** [comment]
With the changes to about-time passing all calendar related functionality to Simple Calendar, this issue is no longer relevant, so I am going to close it.
