### ISSUE TITLE
about-time and simple calendar disagree about the date by 1 month and 2 days

### ISSUE THREAD

**Issue by kdomke** [vigoren/foundryvtt-simple-calendar#89]
**Describe the bug**
I have activated both modules, configured everything with simple calendar. Then I set the integration to self, to use simple-calendar as master of time. 

After reloading the game simple-calendar asked me to sync the settings, and I chose to export to about-time

Instead of showing the same time, about time is one month ahead, but the day is two too low. 

**Browser (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome]
 - Browser Version [90]

simple-calendar and about time:
![image](https://user-images.githubusercontent.com/8623725/117553141-11f3e180-b050-11eb-8fb0-033a9d00a597.png)

month names for reference: 
![image](https://user-images.githubusercontent.com/8623725/117553196-541d2300-b050-11eb-8300-c5fd4793ada5.png)

**Comment by kdomke** [comment]
the debug console shows all months with 28/30 days, even though the calendar has not leap year settings.
![image](https://user-images.githubusercontent.com/8623725/117553229-89c20c00-b050-11eb-9327-6591ac82740f.png)

The month thing looks like a basic of-by-one error with the zero-indexed months in about-time

**Comment by vigoren** [comment]
I have recieved a couple of reports regarding about time not syncing quite right. I noticed about time was updated a couple weeks ago so will have to do some testing.

The day difference shouldn't matter as the second value is only used when the script determines it's a leap year otherwise the first value is used. So if the leap year rule means no year can be a leap year then that second value should never be used but I will test to confirm.

Thanks for the report and sorry you ran into a bug.

**Comment by vigoren** [comment]
I figured out what the bug is and it does have to do with the leap year rule, I think about-time is considering year 0 to be a leap year no matter what so in your case the count is off by 26 days (13 months with a difference of 2 days per month).

I will work on a fix for this.

**Comment by vigoren** [comment]
Ok I think I got this all sorted out in the newest release (v1.2.38).

Update that and please follow the steps in the [release notes](https://github.com/vigoren/foundryvtt-simple-calendar/releases/tag/v1.2.38) and it should sync up with about-time properly.

Thanks again for reporting the bug with all these details!
