### ISSUE TITLE
[FEATURE] Calendar notes to chat

### ISSUE THREAD

**Issue by ditzer252** [vigoren/foundryvtt-simple-calendar#92]
It would be cool if when the date changes, then the calendar notes (or maybe just note titles?) for that date are shown in the chat.  Thanks

**Comment by vigoren** [comment]
This is related to #57 so will look at adding functionality to do this.

**Comment by ditzer252** [comment]
Thanks a lot

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
